{ DO NOT EDIT — generated by pascal_bindgen (Blaise dialect).
  source: /usr/include/ncurses.h
  library: ncurses   -- emitted as external 'ncurses' name '...'
}

unit ncurses_blaise;

interface

type
  __va_list_tag = record
    gp_offset: Cardinal;
    fp_offset: Cardinal;
    overflow_arg_area: Pointer;
    reg_save_area: Pointer;
  end;
  va_list = array[0..0] of __va_list_tag;
  FILE_ = Pointer;  { opaque — layout unknown, assumed pointer-shaped }
  P_win_st = ^_win_st;
  Pattr_t = ^attr_t;
  PCardinal = ^Cardinal;
  Pchtype = ^chtype;
  PFILE_ = ^FILE_;
  PInteger = ^Integer;
  PMEVENT = ^MEVENT;
  Pmmask_t = ^mmask_t;
  PSCREEN = ^SCREEN;
  PSmallInt = ^SmallInt;
  PWINDOW = ^WINDOW;
  chtype = Cardinal;  { ncurses.h:222 }
  mmask_t = Cardinal;  { ncurses.h:223 }
  NCURSES_BOOL = Byte;  { ncurses.h:272 }
  screen = record  { ncurses.h:439 }
  end;
  _win_st = record  { ncurses.h:442 }
  end;
  WINDOW = _win_st;  { ncurses.h:442 }
  attr_t = chtype;  { ncurses.h:444 }
  NCURSES_OUTC = function(arg1: Integer): Integer;  { ncurses.h:597 }
  NCURSES_WINDOW_CB = function(arg1: P_win_st; arg2: Pointer): Integer;  { ncurses.h:928 }
  NCURSES_SCREEN_CB = function(arg1: Pscreen; arg2: Pointer): Integer;  { ncurses.h:929 }
  NCURSES_OUTC_sp = function(arg1: Pscreen; arg2: Integer): Integer;  { ncurses.h:1003 }
  MEVENT = record  { ncurses.h:2021 }
    id: SmallInt;
    x: Integer;
    y: Integer;
    z: Integer;
    bstate: mmask_t;
  end;

const
  CURSES = 1;  { ncurses.h:69 }
  CURSES_H = 1;  { ncurses.h:70 }
  NCURSES_VERSION_MAJOR = 6;  { ncurses.h:73 }
  NCURSES_VERSION_MINOR = 4;  { ncurses.h:74 }
  NCURSES_VERSION_PATCH = 20240113;  { ncurses.h:75 }
  NCURSES_MOUSE_VERSION = 2;  { ncurses.h:84 }
  NCURSES_ENABLE_STDBOOL_H = 1;  { ncurses.h:111 }
  NCURSES_OPAQUE = 1;  { ncurses.h:151 }
  NCURSES_OPAQUE_FORM = 1;  { ncurses.h:152 }
  NCURSES_OPAQUE_MENU = 1;  { ncurses.h:153 }
  NCURSES_OPAQUE_PANEL = 1;  { ncurses.h:154 }
  NCURSES_WATTR_MACROS = 0;  { ncurses.h:163 }
  NCURSES_REENTRANT = 0;  { ncurses.h:170 }
  NCURSES_INTEROP_FUNCS = 1;  { ncurses.h:185 }
  NCURSES_TPARM_VARARGS = 1;  { ncurses.h:197 }
  NCURSES_WCWIDTH_GRAPHICS = 1;  { ncurses.h:211 }
  NCURSES_WIDECHAR = 0;  { ncurses.h:245 }
  TRUE = 1;  { ncurses.h:267 }
  FALSE = 0;  { ncurses.h:270 }
  COLOR_BLACK = 0;  { ncurses.h:329 }
  COLOR_RED = 1;  { ncurses.h:330 }
  COLOR_GREEN = 2;  { ncurses.h:331 }
  COLOR_YELLOW = 3;  { ncurses.h:332 }
  COLOR_BLUE = 4;  { ncurses.h:333 }
  COLOR_MAGENTA = 5;  { ncurses.h:334 }
  COLOR_CYAN = 6;  { ncurses.h:335 }
  COLOR_WHITE = 7;  { ncurses.h:336 }
  _SUBWIN = $01;  { ncurses.h:414 }
  _ENDLINE = $02;  { ncurses.h:415 }
  _FULLWIN = $04;  { ncurses.h:416 }
  _SCROLLWIN = $08;  { ncurses.h:417 }
  _ISPAD = $10;  { ncurses.h:418 }
  _HASMOVED = $20;  { ncurses.h:419 }
  _WRAPPED = $40;  { ncurses.h:420 }
  NCURSES_EXT_FUNCS = 20240113;  { ncurses.h:927 }
  NCURSES_XNAMES = 1;  { ncurses.h:964 }
  NCURSES_SP_FUNCS = 20240113;  { ncurses.h:998 }
  NCURSES_ATTR_SHIFT = 8;  { ncurses.h:1118 }
  KEY_CODE_YES = 0400;  { ncurses.h:1517 }
  KEY_MIN = 0401;  { ncurses.h:1518 }
  KEY_BREAK = 0401;  { ncurses.h:1519 }
  KEY_SRESET = 0530;  { ncurses.h:1520 }
  KEY_RESET = 0531;  { ncurses.h:1521 }
  KEY_DOWN = 0402;  { ncurses.h:1525 }
  KEY_UP = 0403;  { ncurses.h:1526 }
  KEY_LEFT = 0404;  { ncurses.h:1527 }
  KEY_RIGHT = 0405;  { ncurses.h:1528 }
  KEY_HOME = 0406;  { ncurses.h:1529 }
  KEY_BACKSPACE = 0407;  { ncurses.h:1530 }
  KEY_F0 = 0410;  { ncurses.h:1531 }
  KEY_DL = 0510;  { ncurses.h:1533 }
  KEY_IL = 0511;  { ncurses.h:1534 }
  KEY_DC = 0512;  { ncurses.h:1535 }
  KEY_IC = 0513;  { ncurses.h:1536 }
  KEY_EIC = 0514;  { ncurses.h:1537 }
  KEY_CLEAR = 0515;  { ncurses.h:1538 }
  KEY_EOS = 0516;  { ncurses.h:1539 }
  KEY_EOL = 0517;  { ncurses.h:1540 }
  KEY_SF = 0520;  { ncurses.h:1541 }
  KEY_SR = 0521;  { ncurses.h:1542 }
  KEY_NPAGE = 0522;  { ncurses.h:1543 }
  KEY_PPAGE = 0523;  { ncurses.h:1544 }
  KEY_STAB = 0524;  { ncurses.h:1545 }
  KEY_CTAB = 0525;  { ncurses.h:1546 }
  KEY_CATAB = 0526;  { ncurses.h:1547 }
  KEY_ENTER = 0527;  { ncurses.h:1548 }
  KEY_PRINT = 0532;  { ncurses.h:1549 }
  KEY_LL = 0533;  { ncurses.h:1550 }
  KEY_A1 = 0534;  { ncurses.h:1551 }
  KEY_A3 = 0535;  { ncurses.h:1552 }
  KEY_B2 = 0536;  { ncurses.h:1553 }
  KEY_C1 = 0537;  { ncurses.h:1554 }
  KEY_C3 = 0540;  { ncurses.h:1555 }
  KEY_BTAB = 0541;  { ncurses.h:1556 }
  KEY_BEG = 0542;  { ncurses.h:1557 }
  KEY_CANCEL = 0543;  { ncurses.h:1558 }
  KEY_CLOSE = 0544;  { ncurses.h:1559 }
  KEY_COMMAND = 0545;  { ncurses.h:1560 }
  KEY_COPY = 0546;  { ncurses.h:1561 }
  KEY_CREATE = 0547;  { ncurses.h:1562 }
  KEY_END = 0550;  { ncurses.h:1563 }
  KEY_EXIT = 0551;  { ncurses.h:1564 }
  KEY_FIND = 0552;  { ncurses.h:1565 }
  KEY_HELP = 0553;  { ncurses.h:1566 }
  KEY_MARK = 0554;  { ncurses.h:1567 }
  KEY_MESSAGE = 0555;  { ncurses.h:1568 }
  KEY_MOVE = 0556;  { ncurses.h:1569 }
  KEY_NEXT = 0557;  { ncurses.h:1570 }
  KEY_OPEN = 0560;  { ncurses.h:1571 }
  KEY_OPTIONS = 0561;  { ncurses.h:1572 }
  KEY_PREVIOUS = 0562;  { ncurses.h:1573 }
  KEY_REDO = 0563;  { ncurses.h:1574 }
  KEY_REFERENCE = 0564;  { ncurses.h:1575 }
  KEY_REFRESH = 0565;  { ncurses.h:1576 }
  KEY_REPLACE = 0566;  { ncurses.h:1577 }
  KEY_RESTART = 0567;  { ncurses.h:1578 }
  KEY_RESUME = 0570;  { ncurses.h:1579 }
  KEY_SAVE = 0571;  { ncurses.h:1580 }
  KEY_SBEG = 0572;  { ncurses.h:1581 }
  KEY_SCANCEL = 0573;  { ncurses.h:1582 }
  KEY_SCOMMAND = 0574;  { ncurses.h:1583 }
  KEY_SCOPY = 0575;  { ncurses.h:1584 }
  KEY_SCREATE = 0576;  { ncurses.h:1585 }
  KEY_SDC = 0577;  { ncurses.h:1586 }
  KEY_SDL = 0600;  { ncurses.h:1587 }
  KEY_SELECT = 0601;  { ncurses.h:1588 }
  KEY_SEND = 0602;  { ncurses.h:1589 }
  KEY_SEOL = 0603;  { ncurses.h:1590 }
  KEY_SEXIT = 0604;  { ncurses.h:1591 }
  KEY_SFIND = 0605;  { ncurses.h:1592 }
  KEY_SHELP = 0606;  { ncurses.h:1593 }
  KEY_SHOME = 0607;  { ncurses.h:1594 }
  KEY_SIC = 0610;  { ncurses.h:1595 }
  KEY_SLEFT = 0611;  { ncurses.h:1596 }
  KEY_SMESSAGE = 0612;  { ncurses.h:1597 }
  KEY_SMOVE = 0613;  { ncurses.h:1598 }
  KEY_SNEXT = 0614;  { ncurses.h:1599 }
  KEY_SOPTIONS = 0615;  { ncurses.h:1600 }
  KEY_SPREVIOUS = 0616;  { ncurses.h:1601 }
  KEY_SPRINT = 0617;  { ncurses.h:1602 }
  KEY_SREDO = 0620;  { ncurses.h:1603 }
  KEY_SREPLACE = 0621;  { ncurses.h:1604 }
  KEY_SRIGHT = 0622;  { ncurses.h:1605 }
  KEY_SRSUME = 0623;  { ncurses.h:1606 }
  KEY_SSAVE = 0624;  { ncurses.h:1607 }
  KEY_SSUSPEND = 0625;  { ncurses.h:1608 }
  KEY_SUNDO = 0626;  { ncurses.h:1609 }
  KEY_SUSPEND = 0627;  { ncurses.h:1610 }
  KEY_UNDO = 0630;  { ncurses.h:1611 }
  KEY_MOUSE = 0631;  { ncurses.h:1612 }
  KEY_RESIZE = 0632;  { ncurses.h:1615 }
  KEY_MAX = 0777;  { ncurses.h:1618 }
  _XOPEN_CURSES = 1;  { ncurses.h:1625 }
  NCURSES_BUTTON_RELEASED = 001;  { ncurses.h:1948 }
  NCURSES_BUTTON_PRESSED = 002;  { ncurses.h:1949 }
  NCURSES_BUTTON_CLICKED = 004;  { ncurses.h:1950 }
  NCURSES_DOUBLE_CLICKED = 010;  { ncurses.h:1951 }
  NCURSES_TRIPLE_CLICKED = 020;  { ncurses.h:1952 }
  NCURSES_RESERVED_EVENT = 040;  { ncurses.h:1953 }
  TRACE_DISABLE = $0000;  { ncurses.h:2081 }
  TRACE_TIMES = $0001;  { ncurses.h:2082 }
  TRACE_TPUTS = $0002;  { ncurses.h:2083 }
  TRACE_UPDATE = $0004;  { ncurses.h:2084 }
  TRACE_MOVE = $0008;  { ncurses.h:2085 }
  TRACE_CHARPUT = $0010;  { ncurses.h:2086 }
  TRACE_ORDINARY = $001F;  { ncurses.h:2087 }
  TRACE_CALLS = $0020;  { ncurses.h:2088 }
  TRACE_VIRTPUT = $0040;  { ncurses.h:2089 }
  TRACE_IEVENT = $0080;  { ncurses.h:2090 }
  TRACE_BITS = $0100;  { ncurses.h:2091 }
  TRACE_ICALLS = $0200;  { ncurses.h:2092 }
  TRACE_CCALLS = $0400;  { ncurses.h:2093 }
  TRACE_DATABASE = $0800;  { ncurses.h:2094 }
  TRACE_ATTRS = $1000;  { ncurses.h:2095 }
  TRACE_SHIFT = 13;  { ncurses.h:2097 }

function addch(const arg1: Cardinal): Integer; external 'ncurses' name 'addch';  { ncurses.h:606 }
function addchnstr(arg1: PCardinal; arg2: Integer): Integer; external 'ncurses' name 'addchnstr';  { ncurses.h:607 }
function addchstr(arg1: PCardinal): Integer; external 'ncurses' name 'addchstr';  { ncurses.h:608 }
function addnstr(arg1: PChar; arg2: Integer): Integer; external 'ncurses' name 'addnstr';  { ncurses.h:609 }
function addstr(arg1: PChar): Integer; external 'ncurses' name 'addstr';  { ncurses.h:610 }
function attroff(arg1: Integer): Integer; external 'ncurses' name 'attroff';  { ncurses.h:611 }
function attron(arg1: Integer): Integer; external 'ncurses' name 'attron';  { ncurses.h:612 }
function attrset(arg1: Integer): Integer; external 'ncurses' name 'attrset';  { ncurses.h:613 }
function attr_get(arg1: Pattr_t; arg2: PSmallInt; arg3: Pointer): Integer; external 'ncurses' name 'attr_get';  { ncurses.h:614 }
function attr_off(arg1: attr_t; arg2: Pointer): Integer; external 'ncurses' name 'attr_off';  { ncurses.h:615 }
function attr_on(arg1: attr_t; arg2: Pointer): Integer; external 'ncurses' name 'attr_on';  { ncurses.h:616 }
function attr_set(arg1: attr_t; arg2: SmallInt; arg3: Pointer): Integer; external 'ncurses' name 'attr_set';  { ncurses.h:617 }
function baudrate: Integer; external 'ncurses' name 'baudrate';  { ncurses.h:618 }
function beep: Integer; external 'ncurses' name 'beep';  { ncurses.h:619 }
function bkgd(arg1: chtype): Integer; external 'ncurses' name 'bkgd';  { ncurses.h:620 }
procedure bkgdset(arg1: chtype); external 'ncurses' name 'bkgdset';  { ncurses.h:621 }
function border(arg1: chtype; arg2: chtype; arg3: chtype; arg4: chtype; arg5: chtype; arg6: chtype; arg7: chtype; arg8: chtype): Integer; external 'ncurses' name 'border';  { ncurses.h:622 }
function box(arg1: PWINDOW; arg2: chtype; arg3: chtype): Integer; external 'ncurses' name 'box';  { ncurses.h:623 }
function can_change_color: Boolean; external 'ncurses' name 'can_change_color';  { ncurses.h:624 }
function cbreak: Integer; external 'ncurses' name 'cbreak';  { ncurses.h:625 }
function chgat(arg1: Integer; arg2: attr_t; arg3: SmallInt; arg4: Pointer): Integer; external 'ncurses' name 'chgat';  { ncurses.h:626 }
function clear: Integer; external 'ncurses' name 'clear';  { ncurses.h:627 }
function clearok(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'clearok';  { ncurses.h:628 }
function clrtobot: Integer; external 'ncurses' name 'clrtobot';  { ncurses.h:629 }
function clrtoeol: Integer; external 'ncurses' name 'clrtoeol';  { ncurses.h:630 }
function color_content(arg1: SmallInt; arg2: PSmallInt; arg3: PSmallInt; arg4: PSmallInt): Integer; external 'ncurses' name 'color_content';  { ncurses.h:631 }
function color_set(arg1: SmallInt; arg2: Pointer): Integer; external 'ncurses' name 'color_set';  { ncurses.h:632 }
function COLOR_PAIR(arg1: Integer): Integer; external 'ncurses' name 'COLOR_PAIR';  { ncurses.h:633 }
function copywin(arg1: PWINDOW; arg2: PWINDOW; arg3: Integer; arg4: Integer; arg5: Integer; arg6: Integer; arg7: Integer; arg8: Integer; arg9: Integer): Integer; external 'ncurses' name 'copywin';  { ncurses.h:634 }
function curs_set(arg1: Integer): Integer; external 'ncurses' name 'curs_set';  { ncurses.h:635 }
function def_prog_mode: Integer; external 'ncurses' name 'def_prog_mode';  { ncurses.h:636 }
function def_shell_mode: Integer; external 'ncurses' name 'def_shell_mode';  { ncurses.h:637 }
function delay_output(arg1: Integer): Integer; external 'ncurses' name 'delay_output';  { ncurses.h:638 }
function delch: Integer; external 'ncurses' name 'delch';  { ncurses.h:639 }
procedure delscreen(arg1: PSCREEN); external 'ncurses' name 'delscreen';  { ncurses.h:640 }
function delwin(arg1: PWINDOW): Integer; external 'ncurses' name 'delwin';  { ncurses.h:641 }
function deleteln: Integer; external 'ncurses' name 'deleteln';  { ncurses.h:642 }
function derwin(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Integer; arg5: Integer): PWINDOW; external 'ncurses' name 'derwin';  { ncurses.h:643 }
function doupdate: Integer; external 'ncurses' name 'doupdate';  { ncurses.h:644 }
function dupwin(arg1: PWINDOW): PWINDOW; external 'ncurses' name 'dupwin';  { ncurses.h:645 }
function echo: Integer; external 'ncurses' name 'echo';  { ncurses.h:646 }
function echochar(const arg1: Cardinal): Integer; external 'ncurses' name 'echochar';  { ncurses.h:647 }
function erase: Integer; external 'ncurses' name 'erase';  { ncurses.h:648 }
function endwin: Integer; external 'ncurses' name 'endwin';  { ncurses.h:649 }
function erasechar: Byte; external 'ncurses' name 'erasechar';  { ncurses.h:650 }
procedure filter; external 'ncurses' name 'filter';  { ncurses.h:651 }
function flash: Integer; external 'ncurses' name 'flash';  { ncurses.h:652 }
function flushinp: Integer; external 'ncurses' name 'flushinp';  { ncurses.h:653 }
function getbkgd(arg1: PWINDOW): chtype; external 'ncurses' name 'getbkgd';  { ncurses.h:654 }
function getch: Integer; external 'ncurses' name 'getch';  { ncurses.h:655 }
function getnstr(arg1: PChar; arg2: Integer): Integer; external 'ncurses' name 'getnstr';  { ncurses.h:656 }
function getstr(arg1: PChar): Integer; external 'ncurses' name 'getstr';  { ncurses.h:657 }
function getwin(arg1: PFILE_): PWINDOW; external 'ncurses' name 'getwin';  { ncurses.h:658 }
function halfdelay(arg1: Integer): Integer; external 'ncurses' name 'halfdelay';  { ncurses.h:659 }
function has_colors: Boolean; external 'ncurses' name 'has_colors';  { ncurses.h:660 }
function has_ic: Boolean; external 'ncurses' name 'has_ic';  { ncurses.h:661 }
function has_il: Boolean; external 'ncurses' name 'has_il';  { ncurses.h:662 }
function hline(arg1: chtype; arg2: Integer): Integer; external 'ncurses' name 'hline';  { ncurses.h:663 }
procedure idcok(arg1: PWINDOW; arg2: Boolean); external 'ncurses' name 'idcok';  { ncurses.h:664 }
function idlok(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'idlok';  { ncurses.h:665 }
procedure immedok(arg1: PWINDOW; arg2: Boolean); external 'ncurses' name 'immedok';  { ncurses.h:666 }
function inch: chtype; external 'ncurses' name 'inch';  { ncurses.h:667 }
function inchnstr(arg1: Pchtype; arg2: Integer): Integer; external 'ncurses' name 'inchnstr';  { ncurses.h:668 }
function inchstr(arg1: Pchtype): Integer; external 'ncurses' name 'inchstr';  { ncurses.h:669 }
function initscr: PWINDOW; external 'ncurses' name 'initscr';  { ncurses.h:670 }
function init_color(arg1: SmallInt; arg2: SmallInt; arg3: SmallInt; arg4: SmallInt): Integer; external 'ncurses' name 'init_color';  { ncurses.h:671 }
function init_pair(arg1: SmallInt; arg2: SmallInt; arg3: SmallInt): Integer; external 'ncurses' name 'init_pair';  { ncurses.h:672 }
function innstr(arg1: PChar; arg2: Integer): Integer; external 'ncurses' name 'innstr';  { ncurses.h:673 }
function insch(arg1: chtype): Integer; external 'ncurses' name 'insch';  { ncurses.h:674 }
function insdelln(arg1: Integer): Integer; external 'ncurses' name 'insdelln';  { ncurses.h:675 }
function insertln: Integer; external 'ncurses' name 'insertln';  { ncurses.h:676 }
function insnstr(arg1: PChar; arg2: Integer): Integer; external 'ncurses' name 'insnstr';  { ncurses.h:677 }
function insstr(arg1: PChar): Integer; external 'ncurses' name 'insstr';  { ncurses.h:678 }
function instr(arg1: PChar): Integer; external 'ncurses' name 'instr';  { ncurses.h:679 }
function intrflush(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'intrflush';  { ncurses.h:680 }
function isendwin: Boolean; external 'ncurses' name 'isendwin';  { ncurses.h:681 }
function is_linetouched(arg1: PWINDOW; arg2: Integer): Boolean; external 'ncurses' name 'is_linetouched';  { ncurses.h:682 }
function is_wintouched(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_wintouched';  { ncurses.h:683 }
function keyname(arg1: Integer): PChar; external 'ncurses' name 'keyname';  { ncurses.h:684 }
function keypad(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'keypad';  { ncurses.h:685 }
function killchar: Byte; external 'ncurses' name 'killchar';  { ncurses.h:686 }
function leaveok(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'leaveok';  { ncurses.h:687 }
function longname: PChar; external 'ncurses' name 'longname';  { ncurses.h:688 }
function meta(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'meta';  { ncurses.h:689 }
function move(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'move';  { ncurses.h:690 }
function mvaddch(arg1: Integer; arg2: Integer; const arg3: Cardinal): Integer; external 'ncurses' name 'mvaddch';  { ncurses.h:691 }
function mvaddchnstr(arg1: Integer; arg2: Integer; arg3: PCardinal; arg4: Integer): Integer; external 'ncurses' name 'mvaddchnstr';  { ncurses.h:692 }
function mvaddchstr(arg1: Integer; arg2: Integer; arg3: PCardinal): Integer; external 'ncurses' name 'mvaddchstr';  { ncurses.h:693 }
function mvaddnstr(arg1: Integer; arg2: Integer; arg3: PChar; arg4: Integer): Integer; external 'ncurses' name 'mvaddnstr';  { ncurses.h:694 }
function mvaddstr(arg1: Integer; arg2: Integer; arg3: PChar): Integer; external 'ncurses' name 'mvaddstr';  { ncurses.h:695 }
function mvchgat(arg1: Integer; arg2: Integer; arg3: Integer; arg4: attr_t; arg5: SmallInt; arg6: Pointer): Integer; external 'ncurses' name 'mvchgat';  { ncurses.h:696 }
function mvcur(arg1: Integer; arg2: Integer; arg3: Integer; arg4: Integer): Integer; external 'ncurses' name 'mvcur';  { ncurses.h:697 }
function mvdelch(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'mvdelch';  { ncurses.h:698 }
function mvderwin(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'mvderwin';  { ncurses.h:699 }
function mvgetch(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'mvgetch';  { ncurses.h:700 }
function mvgetnstr(arg1: Integer; arg2: Integer; arg3: PChar; arg4: Integer): Integer; external 'ncurses' name 'mvgetnstr';  { ncurses.h:701 }
function mvgetstr(arg1: Integer; arg2: Integer; arg3: PChar): Integer; external 'ncurses' name 'mvgetstr';  { ncurses.h:702 }
function mvhline(arg1: Integer; arg2: Integer; arg3: chtype; arg4: Integer): Integer; external 'ncurses' name 'mvhline';  { ncurses.h:703 }
function mvinch(arg1: Integer; arg2: Integer): chtype; external 'ncurses' name 'mvinch';  { ncurses.h:704 }
function mvinchnstr(arg1: Integer; arg2: Integer; arg3: Pchtype; arg4: Integer): Integer; external 'ncurses' name 'mvinchnstr';  { ncurses.h:705 }
function mvinchstr(arg1: Integer; arg2: Integer; arg3: Pchtype): Integer; external 'ncurses' name 'mvinchstr';  { ncurses.h:706 }
function mvinnstr(arg1: Integer; arg2: Integer; arg3: PChar; arg4: Integer): Integer; external 'ncurses' name 'mvinnstr';  { ncurses.h:707 }
function mvinsch(arg1: Integer; arg2: Integer; arg3: chtype): Integer; external 'ncurses' name 'mvinsch';  { ncurses.h:708 }
function mvinsnstr(arg1: Integer; arg2: Integer; arg3: PChar; arg4: Integer): Integer; external 'ncurses' name 'mvinsnstr';  { ncurses.h:709 }
function mvinsstr(arg1: Integer; arg2: Integer; arg3: PChar): Integer; external 'ncurses' name 'mvinsstr';  { ncurses.h:710 }
function mvinstr(arg1: Integer; arg2: Integer; arg3: PChar): Integer; external 'ncurses' name 'mvinstr';  { ncurses.h:711 }
function mvprintw(arg1: Integer; arg2: Integer; arg3: PChar): Integer; external 'ncurses' name 'mvprintw'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:712 }
function mvscanw(arg1: Integer; arg2: Integer; arg3: PChar): Integer; external 'ncurses' name 'mvscanw'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:714 }
function mvvline(arg1: Integer; arg2: Integer; arg3: chtype; arg4: Integer): Integer; external 'ncurses' name 'mvvline';  { ncurses.h:716 }
function mvwaddch(arg1: PWINDOW; arg2: Integer; arg3: Integer; const arg4: Cardinal): Integer; external 'ncurses' name 'mvwaddch';  { ncurses.h:717 }
function mvwaddchnstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PCardinal; arg5: Integer): Integer; external 'ncurses' name 'mvwaddchnstr';  { ncurses.h:718 }
function mvwaddchstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PCardinal): Integer; external 'ncurses' name 'mvwaddchstr';  { ncurses.h:719 }
function mvwaddnstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar; arg5: Integer): Integer; external 'ncurses' name 'mvwaddnstr';  { ncurses.h:720 }
function mvwaddstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar): Integer; external 'ncurses' name 'mvwaddstr';  { ncurses.h:721 }
function mvwchgat(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Integer; arg5: attr_t; arg6: SmallInt; arg7: Pointer): Integer; external 'ncurses' name 'mvwchgat';  { ncurses.h:722 }
function mvwdelch(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'mvwdelch';  { ncurses.h:723 }
function mvwgetch(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'mvwgetch';  { ncurses.h:724 }
function mvwgetnstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar; arg5: Integer): Integer; external 'ncurses' name 'mvwgetnstr';  { ncurses.h:725 }
function mvwgetstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar): Integer; external 'ncurses' name 'mvwgetstr';  { ncurses.h:726 }
function mvwhline(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: chtype; arg5: Integer): Integer; external 'ncurses' name 'mvwhline';  { ncurses.h:727 }
function mvwin(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'mvwin';  { ncurses.h:728 }
function mvwinch(arg1: PWINDOW; arg2: Integer; arg3: Integer): chtype; external 'ncurses' name 'mvwinch';  { ncurses.h:729 }
function mvwinchnstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Pchtype; arg5: Integer): Integer; external 'ncurses' name 'mvwinchnstr';  { ncurses.h:730 }
function mvwinchstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Pchtype): Integer; external 'ncurses' name 'mvwinchstr';  { ncurses.h:731 }
function mvwinnstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar; arg5: Integer): Integer; external 'ncurses' name 'mvwinnstr';  { ncurses.h:732 }
function mvwinsch(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: chtype): Integer; external 'ncurses' name 'mvwinsch';  { ncurses.h:733 }
function mvwinsnstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar; arg5: Integer): Integer; external 'ncurses' name 'mvwinsnstr';  { ncurses.h:734 }
function mvwinsstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar): Integer; external 'ncurses' name 'mvwinsstr';  { ncurses.h:735 }
function mvwinstr(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar): Integer; external 'ncurses' name 'mvwinstr';  { ncurses.h:736 }
function mvwprintw(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar): Integer; external 'ncurses' name 'mvwprintw'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:737 }
function mvwscanw(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: PChar): Integer; external 'ncurses' name 'mvwscanw'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:739 }
function mvwvline(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: chtype; arg5: Integer): Integer; external 'ncurses' name 'mvwvline';  { ncurses.h:741 }
function napms(arg1: Integer): Integer; external 'ncurses' name 'napms';  { ncurses.h:742 }
function newpad(arg1: Integer; arg2: Integer): PWINDOW; external 'ncurses' name 'newpad';  { ncurses.h:743 }
function newterm(arg1: PChar; arg2: PFILE_; arg3: PFILE_): PSCREEN; external 'ncurses' name 'newterm';  { ncurses.h:744 }
function newwin(arg1: Integer; arg2: Integer; arg3: Integer; arg4: Integer): PWINDOW; external 'ncurses' name 'newwin';  { ncurses.h:745 }
function nl: Integer; external 'ncurses' name 'nl';  { ncurses.h:746 }
function nocbreak: Integer; external 'ncurses' name 'nocbreak';  { ncurses.h:747 }
function nodelay(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'nodelay';  { ncurses.h:748 }
function noecho: Integer; external 'ncurses' name 'noecho';  { ncurses.h:749 }
function nonl: Integer; external 'ncurses' name 'nonl';  { ncurses.h:750 }
procedure noqiflush; external 'ncurses' name 'noqiflush';  { ncurses.h:751 }
function noraw: Integer; external 'ncurses' name 'noraw';  { ncurses.h:752 }
function notimeout(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'notimeout';  { ncurses.h:753 }
function overlay(arg1: PWINDOW; arg2: PWINDOW): Integer; external 'ncurses' name 'overlay';  { ncurses.h:754 }
function overwrite(arg1: PWINDOW; arg2: PWINDOW): Integer; external 'ncurses' name 'overwrite';  { ncurses.h:755 }
function pair_content(arg1: SmallInt; arg2: PSmallInt; arg3: PSmallInt): Integer; external 'ncurses' name 'pair_content';  { ncurses.h:756 }
function PAIR_NUMBER(arg1: Integer): Integer; external 'ncurses' name 'PAIR_NUMBER';  { ncurses.h:757 }
function pechochar(arg1: PWINDOW; const arg2: Cardinal): Integer; external 'ncurses' name 'pechochar';  { ncurses.h:758 }
function pnoutrefresh(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Integer; arg5: Integer; arg6: Integer; arg7: Integer): Integer; external 'ncurses' name 'pnoutrefresh';  { ncurses.h:759 }
function prefresh(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Integer; arg5: Integer; arg6: Integer; arg7: Integer): Integer; external 'ncurses' name 'prefresh';  { ncurses.h:760 }
function printw(arg1: PChar): Integer; external 'ncurses' name 'printw'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:761 }
function putwin(arg1: PWINDOW; arg2: PFILE_): Integer; external 'ncurses' name 'putwin';  { ncurses.h:763 }
procedure qiflush; external 'ncurses' name 'qiflush';  { ncurses.h:764 }
function raw: Integer; external 'ncurses' name 'raw';  { ncurses.h:765 }
function redrawwin(arg1: PWINDOW): Integer; external 'ncurses' name 'redrawwin';  { ncurses.h:766 }
function refresh: Integer; external 'ncurses' name 'refresh';  { ncurses.h:767 }
function resetty: Integer; external 'ncurses' name 'resetty';  { ncurses.h:768 }
function reset_prog_mode: Integer; external 'ncurses' name 'reset_prog_mode';  { ncurses.h:769 }
function reset_shell_mode: Integer; external 'ncurses' name 'reset_shell_mode';  { ncurses.h:770 }
function ripoffline(arg1: Integer; arg2: Pointer): Integer; external 'ncurses' name 'ripoffline';  { ncurses.h:771 }
function savetty: Integer; external 'ncurses' name 'savetty';  { ncurses.h:772 }
function scanw(arg1: PChar): Integer; external 'ncurses' name 'scanw'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:773 }
function scr_dump(arg1: PChar): Integer; external 'ncurses' name 'scr_dump';  { ncurses.h:775 }
function scr_init(arg1: PChar): Integer; external 'ncurses' name 'scr_init';  { ncurses.h:776 }
function scrl(arg1: Integer): Integer; external 'ncurses' name 'scrl';  { ncurses.h:777 }
function scroll(arg1: PWINDOW): Integer; external 'ncurses' name 'scroll';  { ncurses.h:778 }
function scrollok(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'scrollok';  { ncurses.h:779 }
function scr_restore(arg1: PChar): Integer; external 'ncurses' name 'scr_restore';  { ncurses.h:780 }
function scr_set(arg1: PChar): Integer; external 'ncurses' name 'scr_set';  { ncurses.h:781 }
function setscrreg(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'setscrreg';  { ncurses.h:782 }
function set_term(arg1: PSCREEN): PSCREEN; external 'ncurses' name 'set_term';  { ncurses.h:783 }
function slk_attroff(const arg1: Cardinal): Integer; external 'ncurses' name 'slk_attroff';  { ncurses.h:784 }
function slk_attr_off(const arg1: Cardinal; arg2: Pointer): Integer; external 'ncurses' name 'slk_attr_off';  { ncurses.h:785 }
function slk_attron(const arg1: Cardinal): Integer; external 'ncurses' name 'slk_attron';  { ncurses.h:786 }
function slk_attr_on(arg1: attr_t; arg2: Pointer): Integer; external 'ncurses' name 'slk_attr_on';  { ncurses.h:787 }
function slk_attrset(const arg1: Cardinal): Integer; external 'ncurses' name 'slk_attrset';  { ncurses.h:788 }
function slk_attr: attr_t; external 'ncurses' name 'slk_attr';  { ncurses.h:789 }
function slk_attr_set(const arg1: Cardinal; arg2: SmallInt; arg3: Pointer): Integer; external 'ncurses' name 'slk_attr_set';  { ncurses.h:790 }
function slk_clear: Integer; external 'ncurses' name 'slk_clear';  { ncurses.h:791 }
function slk_color(arg1: SmallInt): Integer; external 'ncurses' name 'slk_color';  { ncurses.h:792 }
function slk_init(arg1: Integer): Integer; external 'ncurses' name 'slk_init';  { ncurses.h:793 }
function slk_label(arg1: Integer): PChar; external 'ncurses' name 'slk_label';  { ncurses.h:794 }
function slk_noutrefresh: Integer; external 'ncurses' name 'slk_noutrefresh';  { ncurses.h:795 }
function slk_refresh: Integer; external 'ncurses' name 'slk_refresh';  { ncurses.h:796 }
function slk_restore: Integer; external 'ncurses' name 'slk_restore';  { ncurses.h:797 }
function slk_set(arg1: Integer; arg2: PChar; arg3: Integer): Integer; external 'ncurses' name 'slk_set';  { ncurses.h:798 }
function slk_touch: Integer; external 'ncurses' name 'slk_touch';  { ncurses.h:799 }
function standout: Integer; external 'ncurses' name 'standout';  { ncurses.h:800 }
function standend: Integer; external 'ncurses' name 'standend';  { ncurses.h:801 }
function start_color: Integer; external 'ncurses' name 'start_color';  { ncurses.h:802 }
function subpad(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Integer; arg5: Integer): PWINDOW; external 'ncurses' name 'subpad';  { ncurses.h:803 }
function subwin(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Integer; arg5: Integer): PWINDOW; external 'ncurses' name 'subwin';  { ncurses.h:804 }
function syncok(arg1: PWINDOW; arg2: Boolean): Integer; external 'ncurses' name 'syncok';  { ncurses.h:805 }
function termattrs: chtype; external 'ncurses' name 'termattrs';  { ncurses.h:806 }
function termname: PChar; external 'ncurses' name 'termname';  { ncurses.h:807 }
procedure timeout(arg1: Integer); external 'ncurses' name 'timeout';  { ncurses.h:808 }
function touchline(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'touchline';  { ncurses.h:809 }
function touchwin(arg1: PWINDOW): Integer; external 'ncurses' name 'touchwin';  { ncurses.h:810 }
function typeahead(arg1: Integer): Integer; external 'ncurses' name 'typeahead';  { ncurses.h:811 }
function ungetch(arg1: Integer): Integer; external 'ncurses' name 'ungetch';  { ncurses.h:812 }
function untouchwin(arg1: PWINDOW): Integer; external 'ncurses' name 'untouchwin';  { ncurses.h:813 }
procedure use_env(arg1: Boolean); external 'ncurses' name 'use_env';  { ncurses.h:814 }
procedure use_tioctl(arg1: Boolean); external 'ncurses' name 'use_tioctl';  { ncurses.h:815 }
function vidattr(arg1: chtype): Integer; external 'ncurses' name 'vidattr';  { ncurses.h:816 }
function vidputs(arg1: chtype; arg2: NCURSES_OUTC): Integer; external 'ncurses' name 'vidputs';  { ncurses.h:817 }
function vline(arg1: chtype; arg2: Integer): Integer; external 'ncurses' name 'vline';  { ncurses.h:818 }
function vwprintw(arg1: PWINDOW; arg2: PChar; arg3: va_list): Integer; external 'ncurses' name 'vwprintw';  { ncurses.h:819 }
function vw_printw(arg1: PWINDOW; arg2: PChar; arg3: va_list): Integer; external 'ncurses' name 'vw_printw';  { ncurses.h:821 }
function vwscanw(arg1: PWINDOW; arg2: PChar; arg3: va_list): Integer; external 'ncurses' name 'vwscanw';  { ncurses.h:823 }
function vw_scanw(arg1: PWINDOW; arg2: PChar; arg3: va_list): Integer; external 'ncurses' name 'vw_scanw';  { ncurses.h:825 }
function waddch(arg1: PWINDOW; const arg2: Cardinal): Integer; external 'ncurses' name 'waddch';  { ncurses.h:827 }
function waddchnstr(arg1: PWINDOW; arg2: PCardinal; arg3: Integer): Integer; external 'ncurses' name 'waddchnstr';  { ncurses.h:828 }
function waddchstr(arg1: PWINDOW; arg2: PCardinal): Integer; external 'ncurses' name 'waddchstr';  { ncurses.h:829 }
function waddnstr(arg1: PWINDOW; arg2: PChar; arg3: Integer): Integer; external 'ncurses' name 'waddnstr';  { ncurses.h:830 }
function waddstr(arg1: PWINDOW; arg2: PChar): Integer; external 'ncurses' name 'waddstr';  { ncurses.h:831 }
function wattron(arg1: PWINDOW; arg2: Integer): Integer; external 'ncurses' name 'wattron';  { ncurses.h:832 }
function wattroff(arg1: PWINDOW; arg2: Integer): Integer; external 'ncurses' name 'wattroff';  { ncurses.h:833 }
function wattrset(arg1: PWINDOW; arg2: Integer): Integer; external 'ncurses' name 'wattrset';  { ncurses.h:834 }
function wattr_get(arg1: PWINDOW; arg2: Pattr_t; arg3: PSmallInt; arg4: Pointer): Integer; external 'ncurses' name 'wattr_get';  { ncurses.h:835 }
function wattr_on(arg1: PWINDOW; arg2: attr_t; arg3: Pointer): Integer; external 'ncurses' name 'wattr_on';  { ncurses.h:836 }
function wattr_off(arg1: PWINDOW; arg2: attr_t; arg3: Pointer): Integer; external 'ncurses' name 'wattr_off';  { ncurses.h:837 }
function wattr_set(arg1: PWINDOW; arg2: attr_t; arg3: SmallInt; arg4: Pointer): Integer; external 'ncurses' name 'wattr_set';  { ncurses.h:838 }
function wbkgd(arg1: PWINDOW; arg2: chtype): Integer; external 'ncurses' name 'wbkgd';  { ncurses.h:839 }
procedure wbkgdset(arg1: PWINDOW; arg2: chtype); external 'ncurses' name 'wbkgdset';  { ncurses.h:840 }
function wborder(arg1: PWINDOW; arg2: chtype; arg3: chtype; arg4: chtype; arg5: chtype; arg6: chtype; arg7: chtype; arg8: chtype; arg9: chtype): Integer; external 'ncurses' name 'wborder';  { ncurses.h:841 }
function wchgat(arg1: PWINDOW; arg2: Integer; arg3: attr_t; arg4: SmallInt; arg5: Pointer): Integer; external 'ncurses' name 'wchgat';  { ncurses.h:842 }
function wclear(arg1: PWINDOW): Integer; external 'ncurses' name 'wclear';  { ncurses.h:843 }
function wclrtobot(arg1: PWINDOW): Integer; external 'ncurses' name 'wclrtobot';  { ncurses.h:844 }
function wclrtoeol(arg1: PWINDOW): Integer; external 'ncurses' name 'wclrtoeol';  { ncurses.h:845 }
function wcolor_set(arg1: PWINDOW; arg2: SmallInt; arg3: Pointer): Integer; external 'ncurses' name 'wcolor_set';  { ncurses.h:846 }
procedure wcursyncup(arg1: PWINDOW); external 'ncurses' name 'wcursyncup';  { ncurses.h:847 }
function wdelch(arg1: PWINDOW): Integer; external 'ncurses' name 'wdelch';  { ncurses.h:848 }
function wdeleteln(arg1: PWINDOW): Integer; external 'ncurses' name 'wdeleteln';  { ncurses.h:849 }
function wechochar(arg1: PWINDOW; const arg2: Cardinal): Integer; external 'ncurses' name 'wechochar';  { ncurses.h:850 }
function werase(arg1: PWINDOW): Integer; external 'ncurses' name 'werase';  { ncurses.h:851 }
function wgetch(arg1: PWINDOW): Integer; external 'ncurses' name 'wgetch';  { ncurses.h:852 }
function wgetnstr(arg1: PWINDOW; arg2: PChar; arg3: Integer): Integer; external 'ncurses' name 'wgetnstr';  { ncurses.h:853 }
function wgetstr(arg1: PWINDOW; arg2: PChar): Integer; external 'ncurses' name 'wgetstr';  { ncurses.h:854 }
function whline(arg1: PWINDOW; arg2: chtype; arg3: Integer): Integer; external 'ncurses' name 'whline';  { ncurses.h:855 }
function winch(arg1: PWINDOW): chtype; external 'ncurses' name 'winch';  { ncurses.h:856 }
function winchnstr(arg1: PWINDOW; arg2: Pchtype; arg3: Integer): Integer; external 'ncurses' name 'winchnstr';  { ncurses.h:857 }
function winchstr(arg1: PWINDOW; arg2: Pchtype): Integer; external 'ncurses' name 'winchstr';  { ncurses.h:858 }
function winnstr(arg1: PWINDOW; arg2: PChar; arg3: Integer): Integer; external 'ncurses' name 'winnstr';  { ncurses.h:859 }
function winsch(arg1: PWINDOW; arg2: chtype): Integer; external 'ncurses' name 'winsch';  { ncurses.h:860 }
function winsdelln(arg1: PWINDOW; arg2: Integer): Integer; external 'ncurses' name 'winsdelln';  { ncurses.h:861 }
function winsertln(arg1: PWINDOW): Integer; external 'ncurses' name 'winsertln';  { ncurses.h:862 }
function winsnstr(arg1: PWINDOW; arg2: PChar; arg3: Integer): Integer; external 'ncurses' name 'winsnstr';  { ncurses.h:863 }
function winsstr(arg1: PWINDOW; arg2: PChar): Integer; external 'ncurses' name 'winsstr';  { ncurses.h:864 }
function winstr(arg1: PWINDOW; arg2: PChar): Integer; external 'ncurses' name 'winstr';  { ncurses.h:865 }
function wmove(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'wmove';  { ncurses.h:866 }
function wnoutrefresh(arg1: PWINDOW): Integer; external 'ncurses' name 'wnoutrefresh';  { ncurses.h:867 }
function wprintw(arg1: PWINDOW; arg2: PChar): Integer; external 'ncurses' name 'wprintw'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:868 }
function wredrawln(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'wredrawln';  { ncurses.h:870 }
function wrefresh(arg1: PWINDOW): Integer; external 'ncurses' name 'wrefresh';  { ncurses.h:871 }
function wscanw(arg1: PWINDOW; arg2: PChar): Integer; external 'ncurses' name 'wscanw'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:872 }
function wscrl(arg1: PWINDOW; arg2: Integer): Integer; external 'ncurses' name 'wscrl';  { ncurses.h:874 }
function wsetscrreg(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'wsetscrreg';  { ncurses.h:875 }
function wstandout(arg1: PWINDOW): Integer; external 'ncurses' name 'wstandout';  { ncurses.h:876 }
function wstandend(arg1: PWINDOW): Integer; external 'ncurses' name 'wstandend';  { ncurses.h:877 }
procedure wsyncdown(arg1: PWINDOW); external 'ncurses' name 'wsyncdown';  { ncurses.h:878 }
procedure wsyncup(arg1: PWINDOW); external 'ncurses' name 'wsyncup';  { ncurses.h:879 }
procedure wtimeout(arg1: PWINDOW; arg2: Integer); external 'ncurses' name 'wtimeout';  { ncurses.h:880 }
function wtouchln(arg1: PWINDOW; arg2: Integer; arg3: Integer; arg4: Integer): Integer; external 'ncurses' name 'wtouchln';  { ncurses.h:881 }
function wvline(arg1: PWINDOW; arg2: chtype; arg3: Integer): Integer; external 'ncurses' name 'wvline';  { ncurses.h:882 }
function tigetflag(arg1: PChar): Integer; external 'ncurses' name 'tigetflag';  { ncurses.h:887 }
function tigetnum(arg1: PChar): Integer; external 'ncurses' name 'tigetnum';  { ncurses.h:888 }
function tigetstr(arg1: PChar): PChar; external 'ncurses' name 'tigetstr';  { ncurses.h:889 }
function putp(arg1: PChar): Integer; external 'ncurses' name 'putp';  { ncurses.h:890 }
function tparm(arg1: PChar): PChar; external 'ncurses' name 'tparm'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:893 }
function tiparm(arg1: PChar): PChar; external 'ncurses' name 'tiparm'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:898 }
function tiparm_s(arg1: Integer; arg2: Integer; arg3: PChar): PChar; external 'ncurses' name 'tiparm_s'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:899 }
function tiscan_s(arg1: PInteger; arg2: PInteger; arg3: PChar): Integer; external 'ncurses' name 'tiscan_s';  { ncurses.h:900 }
function getattrs(arg1: PWINDOW): Integer; external 'ncurses' name 'getattrs';  { ncurses.h:905 }
function getcurx(arg1: PWINDOW): Integer; external 'ncurses' name 'getcurx';  { ncurses.h:906 }
function getcury(arg1: PWINDOW): Integer; external 'ncurses' name 'getcury';  { ncurses.h:907 }
function getbegx(arg1: PWINDOW): Integer; external 'ncurses' name 'getbegx';  { ncurses.h:908 }
function getbegy(arg1: PWINDOW): Integer; external 'ncurses' name 'getbegy';  { ncurses.h:909 }
function getmaxx(arg1: PWINDOW): Integer; external 'ncurses' name 'getmaxx';  { ncurses.h:910 }
function getmaxy(arg1: PWINDOW): Integer; external 'ncurses' name 'getmaxy';  { ncurses.h:911 }
function getparx(arg1: PWINDOW): Integer; external 'ncurses' name 'getparx';  { ncurses.h:912 }
function getpary(arg1: PWINDOW): Integer; external 'ncurses' name 'getpary';  { ncurses.h:913 }
function alloc_pair(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'alloc_pair';  { ncurses.h:930 }
function assume_default_colors(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'assume_default_colors';  { ncurses.h:931 }
function curses_version: PChar; external 'ncurses' name 'curses_version';  { ncurses.h:932 }
function define_key(arg1: PChar; arg2: Integer): Integer; external 'ncurses' name 'define_key';  { ncurses.h:933 }
function extended_color_content(arg1: Integer; arg2: PInteger; arg3: PInteger; arg4: PInteger): Integer; external 'ncurses' name 'extended_color_content';  { ncurses.h:934 }
function extended_pair_content(arg1: Integer; arg2: PInteger; arg3: PInteger): Integer; external 'ncurses' name 'extended_pair_content';  { ncurses.h:935 }
function extended_slk_color(arg1: Integer): Integer; external 'ncurses' name 'extended_slk_color';  { ncurses.h:936 }
function find_pair(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'find_pair';  { ncurses.h:937 }
function free_pair(arg1: Integer): Integer; external 'ncurses' name 'free_pair';  { ncurses.h:938 }
function get_escdelay: Integer; external 'ncurses' name 'get_escdelay';  { ncurses.h:939 }
function init_extended_color(arg1: Integer; arg2: Integer; arg3: Integer; arg4: Integer): Integer; external 'ncurses' name 'init_extended_color';  { ncurses.h:940 }
function init_extended_pair(arg1: Integer; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'init_extended_pair';  { ncurses.h:941 }
function is_cbreak: Integer; external 'ncurses' name 'is_cbreak';  { ncurses.h:942 }
function is_echo: Integer; external 'ncurses' name 'is_echo';  { ncurses.h:943 }
function is_nl: Integer; external 'ncurses' name 'is_nl';  { ncurses.h:944 }
function is_raw: Integer; external 'ncurses' name 'is_raw';  { ncurses.h:945 }
function is_term_resized(arg1: Integer; arg2: Integer): Boolean; external 'ncurses' name 'is_term_resized';  { ncurses.h:946 }
function key_defined(arg1: PChar): Integer; external 'ncurses' name 'key_defined';  { ncurses.h:947 }
function keybound(arg1: Integer; arg2: Integer): PChar; external 'ncurses' name 'keybound';  { ncurses.h:948 }
function keyok(arg1: Integer; arg2: Boolean): Integer; external 'ncurses' name 'keyok';  { ncurses.h:949 }
procedure nofilter; external 'ncurses' name 'nofilter';  { ncurses.h:950 }
procedure reset_color_pairs; external 'ncurses' name 'reset_color_pairs';  { ncurses.h:951 }
function resize_term(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'resize_term';  { ncurses.h:952 }
function resizeterm(arg1: Integer; arg2: Integer): Integer; external 'ncurses' name 'resizeterm';  { ncurses.h:953 }
function set_escdelay(arg1: Integer): Integer; external 'ncurses' name 'set_escdelay';  { ncurses.h:954 }
function set_tabsize(arg1: Integer): Integer; external 'ncurses' name 'set_tabsize';  { ncurses.h:955 }
function use_default_colors: Integer; external 'ncurses' name 'use_default_colors';  { ncurses.h:956 }
function use_legacy_coding(arg1: Integer): Integer; external 'ncurses' name 'use_legacy_coding';  { ncurses.h:957 }
function use_screen(arg1: PSCREEN; arg2: NCURSES_SCREEN_CB; arg3: Pointer): Integer; external 'ncurses' name 'use_screen';  { ncurses.h:958 }
function use_window(arg1: PWINDOW; arg2: NCURSES_WINDOW_CB; arg3: Pointer): Integer; external 'ncurses' name 'use_window';  { ncurses.h:959 }
function wresize(arg1: PWINDOW; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'wresize';  { ncurses.h:960 }
function use_extended_names(arg1: Boolean): Integer; external 'ncurses' name 'use_extended_names';  { ncurses.h:965 }
function wgetparent(arg1: PWINDOW): PWINDOW; external 'ncurses' name 'wgetparent';  { ncurses.h:972 }
function is_cleared(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_cleared';  { ncurses.h:973 }
function is_idcok(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_idcok';  { ncurses.h:974 }
function is_idlok(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_idlok';  { ncurses.h:975 }
function is_immedok(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_immedok';  { ncurses.h:976 }
function is_keypad(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_keypad';  { ncurses.h:977 }
function is_leaveok(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_leaveok';  { ncurses.h:978 }
function is_nodelay(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_nodelay';  { ncurses.h:979 }
function is_notimeout(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_notimeout';  { ncurses.h:980 }
function is_pad(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_pad';  { ncurses.h:981 }
function is_scrollok(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_scrollok';  { ncurses.h:982 }
function is_subwin(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_subwin';  { ncurses.h:983 }
function is_syncok(arg1: PWINDOW): Boolean; external 'ncurses' name 'is_syncok';  { ncurses.h:984 }
function wgetdelay(arg1: PWINDOW): Integer; external 'ncurses' name 'wgetdelay';  { ncurses.h:985 }
function wgetscrreg(arg1: PWINDOW; arg2: PInteger; arg3: PInteger): Integer; external 'ncurses' name 'wgetscrreg';  { ncurses.h:986 }
function new_prescr: PSCREEN; external 'ncurses' name 'new_prescr';  { ncurses.h:1005 }
function baudrate_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'baudrate_sp';  { ncurses.h:1007 }
function beep_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'beep_sp';  { ncurses.h:1008 }
function can_change_color_sp(arg1: PSCREEN): Boolean; external 'ncurses' name 'can_change_color_sp';  { ncurses.h:1009 }
function cbreak_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'cbreak_sp';  { ncurses.h:1010 }
function curs_set_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'curs_set_sp';  { ncurses.h:1011 }
function color_content_sp(arg1: PSCREEN; arg2: SmallInt; arg3: PSmallInt; arg4: PSmallInt; arg5: PSmallInt): Integer; external 'ncurses' name 'color_content_sp';  { ncurses.h:1012 }
function def_prog_mode_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'def_prog_mode_sp';  { ncurses.h:1013 }
function def_shell_mode_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'def_shell_mode_sp';  { ncurses.h:1014 }
function delay_output_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'delay_output_sp';  { ncurses.h:1015 }
function doupdate_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'doupdate_sp';  { ncurses.h:1016 }
function echo_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'echo_sp';  { ncurses.h:1017 }
function endwin_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'endwin_sp';  { ncurses.h:1018 }
function erasechar_sp(arg1: PSCREEN): Byte; external 'ncurses' name 'erasechar_sp';  { ncurses.h:1019 }
procedure filter_sp(arg1: PSCREEN); external 'ncurses' name 'filter_sp';  { ncurses.h:1020 }
function flash_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'flash_sp';  { ncurses.h:1021 }
function flushinp_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'flushinp_sp';  { ncurses.h:1022 }
function getwin_sp(arg1: PSCREEN; arg2: PFILE_): PWINDOW; external 'ncurses' name 'getwin_sp';  { ncurses.h:1023 }
function halfdelay_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'halfdelay_sp';  { ncurses.h:1024 }
function has_colors_sp(arg1: PSCREEN): Boolean; external 'ncurses' name 'has_colors_sp';  { ncurses.h:1025 }
function has_ic_sp(arg1: PSCREEN): Boolean; external 'ncurses' name 'has_ic_sp';  { ncurses.h:1026 }
function has_il_sp(arg1: PSCREEN): Boolean; external 'ncurses' name 'has_il_sp';  { ncurses.h:1027 }
function init_color_sp(arg1: PSCREEN; arg2: SmallInt; arg3: SmallInt; arg4: SmallInt; arg5: SmallInt): Integer; external 'ncurses' name 'init_color_sp';  { ncurses.h:1028 }
function init_pair_sp(arg1: PSCREEN; arg2: SmallInt; arg3: SmallInt; arg4: SmallInt): Integer; external 'ncurses' name 'init_pair_sp';  { ncurses.h:1029 }
function intrflush_sp(arg1: PSCREEN; arg2: PWINDOW; arg3: Boolean): Integer; external 'ncurses' name 'intrflush_sp';  { ncurses.h:1030 }
function isendwin_sp(arg1: PSCREEN): Boolean; external 'ncurses' name 'isendwin_sp';  { ncurses.h:1031 }
function keyname_sp(arg1: PSCREEN; arg2: Integer): PChar; external 'ncurses' name 'keyname_sp';  { ncurses.h:1032 }
function killchar_sp(arg1: PSCREEN): Byte; external 'ncurses' name 'killchar_sp';  { ncurses.h:1033 }
function longname_sp(arg1: PSCREEN): PChar; external 'ncurses' name 'longname_sp';  { ncurses.h:1034 }
function mvcur_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer; arg4: Integer; arg5: Integer): Integer; external 'ncurses' name 'mvcur_sp';  { ncurses.h:1035 }
function napms_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'napms_sp';  { ncurses.h:1036 }
function newpad_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer): PWINDOW; external 'ncurses' name 'newpad_sp';  { ncurses.h:1037 }
function newterm_sp(arg1: PSCREEN; arg2: PChar; arg3: PFILE_; arg4: PFILE_): PSCREEN; external 'ncurses' name 'newterm_sp';  { ncurses.h:1038 }
function newwin_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer; arg4: Integer; arg5: Integer): PWINDOW; external 'ncurses' name 'newwin_sp';  { ncurses.h:1039 }
function nl_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'nl_sp';  { ncurses.h:1040 }
function nocbreak_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'nocbreak_sp';  { ncurses.h:1041 }
function noecho_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'noecho_sp';  { ncurses.h:1042 }
function nonl_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'nonl_sp';  { ncurses.h:1043 }
procedure noqiflush_sp(arg1: PSCREEN); external 'ncurses' name 'noqiflush_sp';  { ncurses.h:1044 }
function noraw_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'noraw_sp';  { ncurses.h:1045 }
function pair_content_sp(arg1: PSCREEN; arg2: SmallInt; arg3: PSmallInt; arg4: PSmallInt): Integer; external 'ncurses' name 'pair_content_sp';  { ncurses.h:1046 }
procedure qiflush_sp(arg1: PSCREEN); external 'ncurses' name 'qiflush_sp';  { ncurses.h:1047 }
function raw_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'raw_sp';  { ncurses.h:1048 }
function reset_prog_mode_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'reset_prog_mode_sp';  { ncurses.h:1049 }
function reset_shell_mode_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'reset_shell_mode_sp';  { ncurses.h:1050 }
function resetty_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'resetty_sp';  { ncurses.h:1051 }
function ripoffline_sp(arg1: PSCREEN; arg2: Integer; arg3: Pointer): Integer; external 'ncurses' name 'ripoffline_sp';  { ncurses.h:1052 }
function savetty_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'savetty_sp';  { ncurses.h:1053 }
function scr_init_sp(arg1: PSCREEN; arg2: PChar): Integer; external 'ncurses' name 'scr_init_sp';  { ncurses.h:1054 }
function scr_restore_sp(arg1: PSCREEN; arg2: PChar): Integer; external 'ncurses' name 'scr_restore_sp';  { ncurses.h:1055 }
function scr_set_sp(arg1: PSCREEN; arg2: PChar): Integer; external 'ncurses' name 'scr_set_sp';  { ncurses.h:1056 }
function slk_attroff_sp(arg1: PSCREEN; const arg2: Cardinal): Integer; external 'ncurses' name 'slk_attroff_sp';  { ncurses.h:1057 }
function slk_attron_sp(arg1: PSCREEN; const arg2: Cardinal): Integer; external 'ncurses' name 'slk_attron_sp';  { ncurses.h:1058 }
function slk_attrset_sp(arg1: PSCREEN; const arg2: Cardinal): Integer; external 'ncurses' name 'slk_attrset_sp';  { ncurses.h:1059 }
function slk_attr_sp(arg1: PSCREEN): attr_t; external 'ncurses' name 'slk_attr_sp';  { ncurses.h:1060 }
function slk_attr_set_sp(arg1: PSCREEN; const arg2: Cardinal; arg3: SmallInt; arg4: Pointer): Integer; external 'ncurses' name 'slk_attr_set_sp';  { ncurses.h:1061 }
function slk_clear_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'slk_clear_sp';  { ncurses.h:1062 }
function slk_color_sp(arg1: PSCREEN; arg2: SmallInt): Integer; external 'ncurses' name 'slk_color_sp';  { ncurses.h:1063 }
function slk_init_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'slk_init_sp';  { ncurses.h:1064 }
function slk_label_sp(arg1: PSCREEN; arg2: Integer): PChar; external 'ncurses' name 'slk_label_sp';  { ncurses.h:1065 }
function slk_noutrefresh_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'slk_noutrefresh_sp';  { ncurses.h:1066 }
function slk_refresh_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'slk_refresh_sp';  { ncurses.h:1067 }
function slk_restore_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'slk_restore_sp';  { ncurses.h:1068 }
function slk_set_sp(arg1: PSCREEN; arg2: Integer; arg3: PChar; arg4: Integer): Integer; external 'ncurses' name 'slk_set_sp';  { ncurses.h:1069 }
function slk_touch_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'slk_touch_sp';  { ncurses.h:1070 }
function start_color_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'start_color_sp';  { ncurses.h:1071 }
function termattrs_sp(arg1: PSCREEN): chtype; external 'ncurses' name 'termattrs_sp';  { ncurses.h:1072 }
function termname_sp(arg1: PSCREEN): PChar; external 'ncurses' name 'termname_sp';  { ncurses.h:1073 }
function typeahead_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'typeahead_sp';  { ncurses.h:1074 }
function ungetch_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'ungetch_sp';  { ncurses.h:1075 }
procedure use_env_sp(arg1: PSCREEN; arg2: Boolean); external 'ncurses' name 'use_env_sp';  { ncurses.h:1076 }
procedure use_tioctl_sp(arg1: PSCREEN; arg2: Boolean); external 'ncurses' name 'use_tioctl_sp';  { ncurses.h:1077 }
function vidattr_sp(arg1: PSCREEN; arg2: chtype): Integer; external 'ncurses' name 'vidattr_sp';  { ncurses.h:1078 }
function vidputs_sp(arg1: PSCREEN; arg2: chtype; arg3: NCURSES_OUTC_sp): Integer; external 'ncurses' name 'vidputs_sp';  { ncurses.h:1079 }
function alloc_pair_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'alloc_pair_sp';  { ncurses.h:1081 }
function assume_default_colors_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'assume_default_colors_sp';  { ncurses.h:1082 }
function define_key_sp(arg1: PSCREEN; arg2: PChar; arg3: Integer): Integer; external 'ncurses' name 'define_key_sp';  { ncurses.h:1083 }
function extended_color_content_sp(arg1: PSCREEN; arg2: Integer; arg3: PInteger; arg4: PInteger; arg5: PInteger): Integer; external 'ncurses' name 'extended_color_content_sp';  { ncurses.h:1084 }
function extended_pair_content_sp(arg1: PSCREEN; arg2: Integer; arg3: PInteger; arg4: PInteger): Integer; external 'ncurses' name 'extended_pair_content_sp';  { ncurses.h:1085 }
function extended_slk_color_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'extended_slk_color_sp';  { ncurses.h:1086 }
function find_pair_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'find_pair_sp';  { ncurses.h:1087 }
function free_pair_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'free_pair_sp';  { ncurses.h:1088 }
function get_escdelay_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'get_escdelay_sp';  { ncurses.h:1089 }
function init_extended_color_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer; arg4: Integer; arg5: Integer): Integer; external 'ncurses' name 'init_extended_color_sp';  { ncurses.h:1090 }
function init_extended_pair_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer; arg4: Integer): Integer; external 'ncurses' name 'init_extended_pair_sp';  { ncurses.h:1091 }
function is_cbreak_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'is_cbreak_sp';  { ncurses.h:1092 }
function is_echo_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'is_echo_sp';  { ncurses.h:1093 }
function is_nl_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'is_nl_sp';  { ncurses.h:1094 }
function is_raw_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'is_raw_sp';  { ncurses.h:1095 }
function is_term_resized_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer): Boolean; external 'ncurses' name 'is_term_resized_sp';  { ncurses.h:1096 }
function key_defined_sp(arg1: PSCREEN; arg2: PChar): Integer; external 'ncurses' name 'key_defined_sp';  { ncurses.h:1097 }
function keybound_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer): PChar; external 'ncurses' name 'keybound_sp';  { ncurses.h:1098 }
function keyok_sp(arg1: PSCREEN; arg2: Integer; arg3: Boolean): Integer; external 'ncurses' name 'keyok_sp';  { ncurses.h:1099 }
procedure nofilter_sp(arg1: PSCREEN); external 'ncurses' name 'nofilter_sp';  { ncurses.h:1100 }
procedure reset_color_pairs_sp(arg1: PSCREEN); external 'ncurses' name 'reset_color_pairs_sp';  { ncurses.h:1101 }
function resize_term_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'resize_term_sp';  { ncurses.h:1102 }
function resizeterm_sp(arg1: PSCREEN; arg2: Integer; arg3: Integer): Integer; external 'ncurses' name 'resizeterm_sp';  { ncurses.h:1103 }
function set_escdelay_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'set_escdelay_sp';  { ncurses.h:1104 }
function set_tabsize_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'set_tabsize_sp';  { ncurses.h:1105 }
function use_default_colors_sp(arg1: PSCREEN): Integer; external 'ncurses' name 'use_default_colors_sp';  { ncurses.h:1106 }
function use_legacy_coding_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'use_legacy_coding_sp';  { ncurses.h:1107 }
function has_mouse: Boolean; external 'ncurses' name 'has_mouse';  { ncurses.h:2029 }
function getmouse(arg1: PMEVENT): Integer; external 'ncurses' name 'getmouse';  { ncurses.h:2030 }
function ungetmouse(arg1: PMEVENT): Integer; external 'ncurses' name 'ungetmouse';  { ncurses.h:2031 }
function mousemask(arg1: mmask_t; arg2: Pmmask_t): mmask_t; external 'ncurses' name 'mousemask';  { ncurses.h:2032 }
function wenclose(arg1: PWINDOW; arg2: Integer; arg3: Integer): Boolean; external 'ncurses' name 'wenclose';  { ncurses.h:2033 }
function mouseinterval(arg1: Integer): Integer; external 'ncurses' name 'mouseinterval';  { ncurses.h:2034 }
function wmouse_trafo(arg1: PWINDOW; arg2: PInteger; arg3: PInteger; arg4: Boolean): Boolean; external 'ncurses' name 'wmouse_trafo';  { ncurses.h:2035 }
function mouse_trafo(arg1: PInteger; arg2: PInteger; arg3: Boolean): Boolean; external 'ncurses' name 'mouse_trafo';  { ncurses.h:2036 }
function has_mouse_sp(arg1: PSCREEN): Boolean; external 'ncurses' name 'has_mouse_sp';  { ncurses.h:2039 }
function getmouse_sp(arg1: PSCREEN; arg2: PMEVENT): Integer; external 'ncurses' name 'getmouse_sp';  { ncurses.h:2040 }
function ungetmouse_sp(arg1: PSCREEN; arg2: PMEVENT): Integer; external 'ncurses' name 'ungetmouse_sp';  { ncurses.h:2041 }
function mousemask_sp(arg1: PSCREEN; arg2: mmask_t; arg3: Pmmask_t): mmask_t; external 'ncurses' name 'mousemask_sp';  { ncurses.h:2042 }
function mouseinterval_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'mouseinterval_sp';  { ncurses.h:2043 }
function mcprint(arg1: PChar; arg2: Integer): Integer; external 'ncurses' name 'mcprint';  { ncurses.h:2052 }
function has_key(arg1: Integer): Integer; external 'ncurses' name 'has_key';  { ncurses.h:2053 }
function has_key_sp(arg1: PSCREEN; arg2: Integer): Integer; external 'ncurses' name 'has_key_sp';  { ncurses.h:2056 }
function mcprint_sp(arg1: PSCREEN; arg2: PChar; arg3: Integer): Integer; external 'ncurses' name 'mcprint_sp';  { ncurses.h:2057 }
procedure _tracef(arg1: PChar); external 'ncurses' name '_tracef'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { ncurses.h:2062 }
function _traceattr(arg1: attr_t): PChar; external 'ncurses' name '_traceattr';  { ncurses.h:2063 }
function _traceattr2(arg1: Integer; arg2: chtype): PChar; external 'ncurses' name '_traceattr2';  { ncurses.h:2064 }
function _tracechar(arg1: Integer): PChar; external 'ncurses' name '_tracechar';  { ncurses.h:2065 }
function _tracechtype(arg1: chtype): PChar; external 'ncurses' name '_tracechtype';  { ncurses.h:2066 }
function _tracechtype2(arg1: Integer; arg2: chtype): PChar; external 'ncurses' name '_tracechtype2';  { ncurses.h:2067 }
procedure trace(const arg1: Cardinal); external 'ncurses' name 'trace';  { ncurses.h:2077 }
function curses_trace(const arg1: Cardinal): Cardinal; external 'ncurses' name 'curses_trace';  { ncurses.h:2078 }
procedure exit_curses(arg1: Integer); external 'ncurses' name 'exit_curses';  { ncurses.h:2109 }

implementation

end.
