' demo_rqbasic.bas — a tiny GTK4 window driven by the bindings
' generated by `pascal_bindgen --rqbasic`. Builds against the
' libgtk-4 import baked into the DECLARE LIB clauses; closing
' the window or pressing Ctrl+C exits.

$INCLUDE "gtk4_rqbasic.bas"

DIM running AS INTEGER
DIM loop_ AS POINTER

' Signal handler — "close-request" hands us (window, user_data) and
' expects gboolean (INTEGER): TRUE swallows the event, FALSE lets
' GTK destroy the window. We quit the main loop and return FALSE so
' the window actually closes.
FUNCTION OnClose (win AS POINTER, data AS POINTER) AS INTEGER
  running = 0
  g_main_loop_quit(loop_)
  OnClose = 0
END FUNCTION

' gtk_window_new returns GtkWidget*, not GtkWindow* — that's how
' GTK itself signs it. The window-y entry points still accept the
' widget pointer thanks to the all-P-aliases-are-POINTER-compatible
' rule we chose for rqbasic typed pointers.
DIM win AS P_GtkWidget
DIM label_ AS P_GtkWidget

running = 1
gtk_init

win = gtk_window_new
gtk_window_set_title(win, PCHAR("Hello from pascal_bindgen --rqbasic"))
gtk_window_set_default_size(win, 400, 160)
g_signal_connect_data(win, PCHAR("close-request"), @OnClose, null, null, 0)

label_ = gtk_label_new(PCHAR("Bindings generated by pascal_bindgen." + CHR$(10) + _
                            "Close the window to exit."))
gtk_window_set_child(win, label_)
gtk_window_present(win)

loop_ = g_main_loop_new(null, 0)
g_main_loop_run(loop_)
g_main_loop_unref(loop_)
