' pong_rqbasic.bas — two-player pong driven by the raylib bindings
' generated by pascal_bindgen --rqbasic.
'
'   Controls:  W / S    — left paddle
'              UP/DOWN  — right paddle
'   First to 9 doesn't end the game; closing the window does.
'
' Everything's INTEGER on purpose: rapidq currently has no
' Single→Integer narrowing assignment, so the cleanest path with
' raylib's Integer-typed Draw* surface is to keep positions
' integer and step by a fixed per-frame amount.

$INCLUDE "raylib_rqbasic.bas"

CONST WIN_W = 800
CONST WIN_H = 600
CONST PADDLE_W = 12
CONST PADDLE_H = 90
CONST BALL_R = 9
CONST PADDLE_STEP = 7
CONST BALL_SPEED_X = 6
CONST BALL_SPEED_Y = 5

DIM bg AS Color
DIM fg AS Color
DIM accent AS Color
bg.r     =  18: bg.g     =  18: bg.b     =  28: bg.a     = 255
fg.r     = 230: fg.g     = 230: fg.b     = 240: fg.a     = 255
accent.r = 250: accent.g = 200: accent.b =  80: accent.a = 255

DIM paddle_l_y AS INTEGER
DIM paddle_r_y AS INTEGER
DIM ball_x AS INTEGER
DIM ball_y AS INTEGER
DIM ball_vx AS INTEGER
DIM ball_vy AS INTEGER
DIM score_l AS INTEGER
DIM score_r AS INTEGER
DIM serve_frames AS INTEGER
DIM serve_dir AS INTEGER

SUB ResetBall (toward_dir AS INTEGER)
  ball_x = WIN_W \ 2
  ball_y = WIN_H \ 2
  ball_vx = 0
  ball_vy = 0
  serve_frames = 36
  serve_dir = toward_dir
END SUB

InitWindow(WIN_W, WIN_H, PCHAR("rqbasic + raylib — Pong"))
SetTargetFPS(60)

paddle_l_y = (WIN_H - PADDLE_H) \ 2
paddle_r_y = (WIN_H - PADDLE_H) \ 2
score_l = 0
score_r = 0
ResetBall(1)

DIM key_state AS BYTE

WHILE WindowShouldClose() = 0
  ' --- input ----------------------------------------------------
  ' rapidq's IF predicate doesn't see a BYTE-returning function call
  ' correctly — `IF IsKeyDown(KEY_W) <> 0 THEN ...` never fires
  ' even though IsKeyDown returns 1 when held. Capture into a BYTE
  ' first then compare = 1.
  key_state = IsKeyDown(KEY_W):    IF key_state = 1 THEN paddle_l_y = paddle_l_y - PADDLE_STEP
  key_state = IsKeyDown(KEY_S):    IF key_state = 1 THEN paddle_l_y = paddle_l_y + PADDLE_STEP
  key_state = IsKeyDown(KEY_UP):   IF key_state = 1 THEN paddle_r_y = paddle_r_y - PADDLE_STEP
  key_state = IsKeyDown(KEY_DOWN): IF key_state = 1 THEN paddle_r_y = paddle_r_y + PADDLE_STEP
  IF paddle_l_y < 0 THEN paddle_l_y = 0
  IF paddle_l_y > WIN_H - PADDLE_H THEN paddle_l_y = WIN_H - PADDLE_H
  IF paddle_r_y < 0 THEN paddle_r_y = 0
  IF paddle_r_y > WIN_H - PADDLE_H THEN paddle_r_y = WIN_H - PADDLE_H

  ' --- ball -----------------------------------------------------
  IF serve_frames > 0 THEN
    serve_frames = serve_frames - 1
    IF serve_frames = 0 THEN
      ball_vx = BALL_SPEED_X * serve_dir
      ball_vy = BALL_SPEED_Y
    END IF
  ELSE
    ball_x = ball_x + ball_vx
    ball_y = ball_y + ball_vy

    IF ball_y < BALL_R THEN
      ball_y = BALL_R
      ball_vy = -ball_vy
    END IF
    IF ball_y > WIN_H - BALL_R THEN
      ball_y = WIN_H - BALL_R
      ball_vy = -ball_vy
    END IF

    ' Left paddle
    IF ball_vx < 0 THEN
      IF ball_x - BALL_R < 20 + PADDLE_W THEN
        IF ball_y > paddle_l_y THEN
          IF ball_y < paddle_l_y + PADDLE_H THEN
            ball_x = 20 + PADDLE_W + BALL_R
            ball_vx = -ball_vx
            ' Add english from hit position (-/+ a few px).
            ball_vy = ball_vy + (ball_y - (paddle_l_y + PADDLE_H \ 2)) \ 8
          END IF
        END IF
      END IF
    END IF

    ' Right paddle
    IF ball_vx > 0 THEN
      IF ball_x + BALL_R > WIN_W - 20 - PADDLE_W THEN
        IF ball_y > paddle_r_y THEN
          IF ball_y < paddle_r_y + PADDLE_H THEN
            ball_x = WIN_W - 20 - PADDLE_W - BALL_R
            ball_vx = -ball_vx
            ball_vy = ball_vy + (ball_y - (paddle_r_y + PADDLE_H \ 2)) \ 8
          END IF
        END IF
      END IF
    END IF

    IF ball_x < 0 THEN
      score_r = score_r + 1
      ResetBall(-1)
    END IF
    IF ball_x > WIN_W THEN
      score_l = score_l + 1
      ResetBall(1)
    END IF
  END IF

  ' --- render ---------------------------------------------------
  BeginDrawing()
  ClearBackground(bg)

  DIM net_y AS INTEGER
  net_y = 0
  WHILE net_y < WIN_H
    DrawRectangle(WIN_W \ 2 - 2, net_y, 4, 14, accent)
    net_y = net_y + 28
  WEND

  DrawRectangle(20, paddle_l_y, PADDLE_W, PADDLE_H, fg)
  DrawRectangle(WIN_W - 20 - PADDLE_W, paddle_r_y, PADDLE_W, PADDLE_H, fg)
  DrawCircle(ball_x, ball_y, BALL_R, accent)

  DrawText(PCHAR(STR$(score_l)), WIN_W \ 4,        20, 56, fg)
  DrawText(PCHAR(STR$(score_r)), 3 * WIN_W \ 4 - 30, 20, 56, fg)

  EndDrawing()
WEND

CloseWindow()
