'DO NOT EDIT — generated by pascal_bindgen (RapidQ BASIC dialect).
'  source: /usr/include/raylib.h
'  library: raylib

$CALLING CDECL

TYPE PAutomationEvent AS AutomationEvent Ptr
TYPE PAutomationEventList AS AutomationEventList Ptr
TYPE PBoneInfo AS BoneInfo Ptr
TYPE PColor AS Color Ptr
TYPE PGlyphInfo AS GlyphInfo Ptr
TYPE PImage AS Image Ptr
TYPE PMaterial AS Material Ptr
TYPE PMaterialMap AS MaterialMap Ptr
TYPE PMatrix AS Matrix Ptr
TYPE PMesh AS Mesh Ptr
TYPE PModel AS Model Ptr
TYPE PModelAnimation AS ModelAnimation Ptr
TYPE PrAudioBuffer AS rAudioBuffer Ptr
TYPE PrAudioProcessor AS rAudioProcessor Ptr
TYPE PRectangle AS Rectangle Ptr
TYPE PTransform AS Transform Ptr
TYPE PVector2 AS Vector2 Ptr
TYPE PVector3 AS Vector3 Ptr
TYPE PWave AS Wave Ptr

TYPE Vector2
  x AS SINGLE
  y AS SINGLE
END TYPE
TYPE Vector3
  x AS SINGLE
  y AS SINGLE
  z AS SINGLE
END TYPE
TYPE Vector4
  x AS SINGLE
  y AS SINGLE
  z AS SINGLE
  w AS SINGLE
END TYPE
'typedef Quaternion = Vector4  (' aliased — referenced inline)
TYPE Matrix
  m0 AS SINGLE
  m4 AS SINGLE
  m8 AS SINGLE
  m12 AS SINGLE
  m1 AS SINGLE
  m5 AS SINGLE
  m9 AS SINGLE
  m13 AS SINGLE
  m2 AS SINGLE
  m6 AS SINGLE
  m10 AS SINGLE
  m14 AS SINGLE
  m3 AS SINGLE
  m7 AS SINGLE
  m11 AS SINGLE
  m15 AS SINGLE
END TYPE
TYPE Color
  r AS BYTE
  g AS BYTE
  b AS BYTE
  a AS BYTE
END TYPE
TYPE Rectangle
  x AS SINGLE
  y AS SINGLE
  width AS SINGLE
  height AS SINGLE
END TYPE
TYPE Image
  data AS POINTER
  width AS INTEGER
  height AS INTEGER
  mipmaps AS INTEGER
  format AS INTEGER
END TYPE
TYPE Texture
  id AS DWORD
  width AS INTEGER
  height AS INTEGER
  mipmaps AS INTEGER
  format AS INTEGER
END TYPE
'typedef Texture2D = Texture  (' aliased — referenced inline)
'typedef TextureCubemap = Texture  (' aliased — referenced inline)
TYPE RenderTexture
  id AS DWORD
  texture AS Texture
  depth AS Texture
END TYPE
'typedef RenderTexture2D = RenderTexture  (' aliased — referenced inline)
TYPE NPatchInfo
  source AS Rectangle
  left AS INTEGER
  top AS INTEGER
  right AS INTEGER
  bottom AS INTEGER
  layout AS INTEGER
END TYPE
TYPE GlyphInfo
  value AS INTEGER
  offsetX AS INTEGER
  offsetY AS INTEGER
  advanceX AS INTEGER
  image AS Image
END TYPE
TYPE Font
  baseSize AS INTEGER
  glyphCount AS INTEGER
  glyphPadding AS INTEGER
  texture AS POINTER
  recs AS PRectangle
  glyphs AS PGlyphInfo
END TYPE
TYPE Camera3D
  position AS Vector3
  target AS Vector3
  up AS Vector3
  fovy AS SINGLE
  projection AS INTEGER
END TYPE
'typedef Camera = Camera3D  (' aliased — referenced inline)
TYPE Camera2D
  offset AS Vector2
  target AS Vector2
  rotation AS SINGLE
  zoom AS SINGLE
END TYPE
TYPE Mesh
  vertexCount AS INTEGER
  triangleCount AS INTEGER
  vertices AS POINTER
  texcoords AS POINTER
  texcoords2 AS POINTER
  normals AS POINTER
  tangents AS POINTER
  colors AS POINTER
  indices AS POINTER
  animVertices AS POINTER
  animNormals AS POINTER
  boneIds AS POINTER
  boneWeights AS POINTER
  boneMatrices AS PMatrix
  boneCount AS INTEGER
  vaoId AS DWORD
  vboId AS POINTER
END TYPE
TYPE Shader
  id AS DWORD
  locs AS POINTER
END TYPE
TYPE MaterialMap
  texture AS POINTER
  color AS Color
  value AS SINGLE
END TYPE
TYPE Material
  shader AS Shader
  maps AS PMaterialMap
  params AS SINGLE(3)
END TYPE
TYPE Transform
  translation AS Vector3
  rotation AS POINTER
  scale AS Vector3
END TYPE
TYPE BoneInfo
  name AS BYTE(31)
  parent AS INTEGER
END TYPE
TYPE Model
  transform AS Matrix
  meshCount AS INTEGER
  materialCount AS INTEGER
  meshes AS PMesh
  materials AS PMaterial
  meshMaterial AS POINTER
  boneCount AS INTEGER
  bones AS PBoneInfo
  bindPose AS PTransform
END TYPE
TYPE ModelAnimation
  boneCount AS INTEGER
  frameCount AS INTEGER
  bones AS PBoneInfo
  framePoses AS POINTER
  name AS BYTE(31)
END TYPE
TYPE Ray
  position AS Vector3
  direction AS Vector3
END TYPE
TYPE RayCollision
  hit AS BYTE
  distance AS SINGLE
  point AS Vector3
  normal AS Vector3
END TYPE
TYPE BoundingBox
  min AS Vector3
  max AS Vector3
END TYPE
TYPE Wave
  frameCount AS DWORD
  sampleRate AS DWORD
  sampleSize AS DWORD
  channels AS DWORD
  data AS POINTER
END TYPE
TYPE rAudioBuffer
END TYPE
TYPE rAudioProcessor
END TYPE
TYPE AudioStream
  buffer AS PrAudioBuffer
  processor AS PrAudioProcessor
  sampleRate AS DWORD
  sampleSize AS DWORD
  channels AS DWORD
END TYPE
TYPE Sound
  stream AS AudioStream
  frameCount AS DWORD
END TYPE
TYPE Music
  stream AS AudioStream
  frameCount AS DWORD
  looping AS BYTE
  ctxType AS INTEGER
  ctxData AS POINTER
END TYPE
TYPE VrDeviceInfo
  hResolution AS INTEGER
  vResolution AS INTEGER
  hScreenSize AS SINGLE
  vScreenSize AS SINGLE
  eyeToScreenDistance AS SINGLE
  lensSeparationDistance AS SINGLE
  interpupillaryDistance AS SINGLE
  lensDistortionValues AS SINGLE(3)
  chromaAbCorrection AS SINGLE(3)
END TYPE
TYPE VrStereoConfig
  projection AS Matrix(1)
  viewOffset AS Matrix(1)
  leftLensCenter AS SINGLE(1)
  rightLensCenter AS SINGLE(1)
  leftScreenCenter AS SINGLE(1)
  rightScreenCenter AS SINGLE(1)
  scale AS SINGLE(1)
  scaleIn AS SINGLE(1)
END TYPE
TYPE FilePathList
  capacity AS DWORD
  count AS DWORD
  paths AS POINTER
END TYPE
TYPE AutomationEvent
  frame AS DWORD
  type_ AS DWORD
  params AS INTEGER(3)
END TYPE
TYPE AutomationEventList
  capacity AS DWORD
  count AS DWORD
  events AS PAutomationEvent
END TYPE
CONST FLAG_VSYNC_HINT = 64
CONST FLAG_FULLSCREEN_MODE = 2
CONST FLAG_WINDOW_RESIZABLE = 4
CONST FLAG_WINDOW_UNDECORATED = 8
CONST FLAG_WINDOW_HIDDEN = 128
CONST FLAG_WINDOW_MINIMIZED = 512
CONST FLAG_WINDOW_MAXIMIZED = 1024
CONST FLAG_WINDOW_UNFOCUSED = 2048
CONST FLAG_WINDOW_TOPMOST = 4096
CONST FLAG_WINDOW_ALWAYS_RUN = 256
CONST FLAG_WINDOW_TRANSPARENT = 16
CONST FLAG_WINDOW_HIGHDPI = 8192
CONST FLAG_WINDOW_MOUSE_PASSTHROUGH = 16384
CONST FLAG_BORDERLESS_WINDOWED_MODE = 32768
CONST FLAG_MSAA_4X_HINT = 32
CONST FLAG_INTERLACED_HINT = 65536
CONST LOG_ALL = 0
CONST LOG_TRACE = 1
CONST LOG_DEBUG = 2
CONST LOG_INFO = 3
CONST LOG_WARNING = 4
CONST LOG_ERROR = 5
CONST LOG_FATAL = 6
CONST LOG_NONE = 7
CONST KEY_NULL = 0
CONST KEY_APOSTROPHE = 39
CONST KEY_COMMA = 44
CONST KEY_MINUS = 45
CONST KEY_PERIOD = 46
CONST KEY_SLASH = 47
CONST KEY_ZERO = 48
CONST KEY_ONE = 49
CONST KEY_TWO = 50
CONST KEY_THREE = 51
CONST KEY_FOUR = 52
CONST KEY_FIVE = 53
CONST KEY_SIX = 54
CONST KEY_SEVEN = 55
CONST KEY_EIGHT = 56
CONST KEY_NINE = 57
CONST KEY_SEMICOLON = 59
CONST KEY_EQUAL = 61
CONST KEY_A = 65
CONST KEY_B = 66
CONST KEY_C = 67
CONST KEY_D = 68
CONST KEY_E = 69
CONST KEY_F = 70
CONST KEY_G = 71
CONST KEY_H = 72
CONST KEY_I = 73
CONST KEY_J = 74
CONST KEY_K = 75
CONST KEY_L = 76
CONST KEY_M = 77
CONST KEY_N = 78
CONST KEY_O = 79
CONST KEY_P = 80
CONST KEY_Q = 81
CONST KEY_R = 82
CONST KEY_S = 83
CONST KEY_T = 84
CONST KEY_U = 85
CONST KEY_V = 86
CONST KEY_W = 87
CONST KEY_X = 88
CONST KEY_Y = 89
CONST KEY_Z = 90
CONST KEY_LEFT_BRACKET = 91
CONST KEY_BACKSLASH = 92
CONST KEY_RIGHT_BRACKET = 93
CONST KEY_GRAVE = 96
CONST KEY_SPACE = 32
CONST KEY_ESCAPE = 256
CONST KEY_ENTER = 257
CONST KEY_TAB = 258
CONST KEY_BACKSPACE = 259
CONST KEY_INSERT = 260
CONST KEY_DELETE = 261
CONST KEY_RIGHT = 262
CONST KEY_LEFT = 263
CONST KEY_DOWN = 264
CONST KEY_UP = 265
CONST KEY_PAGE_UP = 266
CONST KEY_PAGE_DOWN = 267
CONST KEY_HOME = 268
CONST KEY_END = 269
CONST KEY_CAPS_LOCK = 280
CONST KEY_SCROLL_LOCK = 281
CONST KEY_NUM_LOCK = 282
CONST KEY_PRINT_SCREEN = 283
CONST KEY_PAUSE = 284
CONST KEY_F1 = 290
CONST KEY_F2 = 291
CONST KEY_F3 = 292
CONST KEY_F4 = 293
CONST KEY_F5 = 294
CONST KEY_F6 = 295
CONST KEY_F7 = 296
CONST KEY_F8 = 297
CONST KEY_F9 = 298
CONST KEY_F10 = 299
CONST KEY_F11 = 300
CONST KEY_F12 = 301
CONST KEY_LEFT_SHIFT = 340
CONST KEY_LEFT_CONTROL = 341
CONST KEY_LEFT_ALT = 342
CONST KEY_LEFT_SUPER = 343
CONST KEY_RIGHT_SHIFT = 344
CONST KEY_RIGHT_CONTROL = 345
CONST KEY_RIGHT_ALT = 346
CONST KEY_RIGHT_SUPER = 347
CONST KEY_KB_MENU = 348
CONST KEY_KP_0 = 320
CONST KEY_KP_1 = 321
CONST KEY_KP_2 = 322
CONST KEY_KP_3 = 323
CONST KEY_KP_4 = 324
CONST KEY_KP_5 = 325
CONST KEY_KP_6 = 326
CONST KEY_KP_7 = 327
CONST KEY_KP_8 = 328
CONST KEY_KP_9 = 329
CONST KEY_KP_DECIMAL = 330
CONST KEY_KP_DIVIDE = 331
CONST KEY_KP_MULTIPLY = 332
CONST KEY_KP_SUBTRACT = 333
CONST KEY_KP_ADD = 334
CONST KEY_KP_ENTER = 335
CONST KEY_KP_EQUAL = 336
CONST KEY_BACK = 4
CONST KEY_MENU = 5
CONST KEY_VOLUME_UP = 24
CONST KEY_VOLUME_DOWN = 25
CONST MOUSE_BUTTON_LEFT = 0
CONST MOUSE_BUTTON_RIGHT = 1
CONST MOUSE_BUTTON_MIDDLE = 2
CONST MOUSE_BUTTON_SIDE = 3
CONST MOUSE_BUTTON_EXTRA = 4
CONST MOUSE_BUTTON_FORWARD = 5
CONST MOUSE_BUTTON_BACK = 6
CONST MOUSE_CURSOR_DEFAULT = 0
CONST MOUSE_CURSOR_ARROW = 1
CONST MOUSE_CURSOR_IBEAM = 2
CONST MOUSE_CURSOR_CROSSHAIR = 3
CONST MOUSE_CURSOR_POINTING_HAND = 4
CONST MOUSE_CURSOR_RESIZE_EW = 5
CONST MOUSE_CURSOR_RESIZE_NS = 6
CONST MOUSE_CURSOR_RESIZE_NWSE = 7
CONST MOUSE_CURSOR_RESIZE_NESW = 8
CONST MOUSE_CURSOR_RESIZE_ALL = 9
CONST MOUSE_CURSOR_NOT_ALLOWED = 10
CONST GAMEPAD_BUTTON_UNKNOWN = 0
CONST GAMEPAD_BUTTON_LEFT_FACE_UP = 1
CONST GAMEPAD_BUTTON_LEFT_FACE_RIGHT = 2
CONST GAMEPAD_BUTTON_LEFT_FACE_DOWN = 3
CONST GAMEPAD_BUTTON_LEFT_FACE_LEFT = 4
CONST GAMEPAD_BUTTON_RIGHT_FACE_UP = 5
CONST GAMEPAD_BUTTON_RIGHT_FACE_RIGHT = 6
CONST GAMEPAD_BUTTON_RIGHT_FACE_DOWN = 7
CONST GAMEPAD_BUTTON_RIGHT_FACE_LEFT = 8
CONST GAMEPAD_BUTTON_LEFT_TRIGGER_1 = 9
CONST GAMEPAD_BUTTON_LEFT_TRIGGER_2 = 10
CONST GAMEPAD_BUTTON_RIGHT_TRIGGER_1 = 11
CONST GAMEPAD_BUTTON_RIGHT_TRIGGER_2 = 12
CONST GAMEPAD_BUTTON_MIDDLE_LEFT = 13
CONST GAMEPAD_BUTTON_MIDDLE = 14
CONST GAMEPAD_BUTTON_MIDDLE_RIGHT = 15
CONST GAMEPAD_BUTTON_LEFT_THUMB = 16
CONST GAMEPAD_BUTTON_RIGHT_THUMB = 17
CONST GAMEPAD_AXIS_LEFT_X = 0
CONST GAMEPAD_AXIS_LEFT_Y = 1
CONST GAMEPAD_AXIS_RIGHT_X = 2
CONST GAMEPAD_AXIS_RIGHT_Y = 3
CONST GAMEPAD_AXIS_LEFT_TRIGGER = 4
CONST GAMEPAD_AXIS_RIGHT_TRIGGER = 5
CONST MATERIAL_MAP_ALBEDO = 0
CONST MATERIAL_MAP_METALNESS = 1
CONST MATERIAL_MAP_NORMAL = 2
CONST MATERIAL_MAP_ROUGHNESS = 3
CONST MATERIAL_MAP_OCCLUSION = 4
CONST MATERIAL_MAP_EMISSION = 5
CONST MATERIAL_MAP_HEIGHT = 6
CONST MATERIAL_MAP_CUBEMAP = 7
CONST MATERIAL_MAP_IRRADIANCE = 8
CONST MATERIAL_MAP_PREFILTER = 9
CONST MATERIAL_MAP_BRDF = 10
CONST SHADER_LOC_VERTEX_POSITION = 0
CONST SHADER_LOC_VERTEX_TEXCOORD01 = 1
CONST SHADER_LOC_VERTEX_TEXCOORD02 = 2
CONST SHADER_LOC_VERTEX_NORMAL = 3
CONST SHADER_LOC_VERTEX_TANGENT = 4
CONST SHADER_LOC_VERTEX_COLOR = 5
CONST SHADER_LOC_MATRIX_MVP = 6
CONST SHADER_LOC_MATRIX_VIEW = 7
CONST SHADER_LOC_MATRIX_PROJECTION = 8
CONST SHADER_LOC_MATRIX_MODEL = 9
CONST SHADER_LOC_MATRIX_NORMAL = 10
CONST SHADER_LOC_VECTOR_VIEW = 11
CONST SHADER_LOC_COLOR_DIFFUSE = 12
CONST SHADER_LOC_COLOR_SPECULAR = 13
CONST SHADER_LOC_COLOR_AMBIENT = 14
CONST SHADER_LOC_MAP_ALBEDO = 15
CONST SHADER_LOC_MAP_METALNESS = 16
CONST SHADER_LOC_MAP_NORMAL = 17
CONST SHADER_LOC_MAP_ROUGHNESS = 18
CONST SHADER_LOC_MAP_OCCLUSION = 19
CONST SHADER_LOC_MAP_EMISSION = 20
CONST SHADER_LOC_MAP_HEIGHT = 21
CONST SHADER_LOC_MAP_CUBEMAP = 22
CONST SHADER_LOC_MAP_IRRADIANCE = 23
CONST SHADER_LOC_MAP_PREFILTER = 24
CONST SHADER_LOC_MAP_BRDF = 25
CONST SHADER_LOC_VERTEX_BONEIDS = 26
CONST SHADER_LOC_VERTEX_BONEWEIGHTS = 27
CONST SHADER_LOC_BONE_MATRICES = 28
CONST SHADER_UNIFORM_FLOAT = 0
CONST SHADER_UNIFORM_VEC2 = 1
CONST SHADER_UNIFORM_VEC3 = 2
CONST SHADER_UNIFORM_VEC4 = 3
CONST SHADER_UNIFORM_INT = 4
CONST SHADER_UNIFORM_IVEC2 = 5
CONST SHADER_UNIFORM_IVEC3 = 6
CONST SHADER_UNIFORM_IVEC4 = 7
CONST SHADER_UNIFORM_SAMPLER2D = 8
CONST SHADER_ATTRIB_FLOAT = 0
CONST SHADER_ATTRIB_VEC2 = 1
CONST SHADER_ATTRIB_VEC3 = 2
CONST SHADER_ATTRIB_VEC4 = 3
CONST PIXELFORMAT_UNCOMPRESSED_GRAYSCALE = 1
CONST PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA = 2
CONST PIXELFORMAT_UNCOMPRESSED_R5G6B5 = 3
CONST PIXELFORMAT_UNCOMPRESSED_R8G8B8 = 4
CONST PIXELFORMAT_UNCOMPRESSED_R5G5B5A1 = 5
CONST PIXELFORMAT_UNCOMPRESSED_R4G4B4A4 = 6
CONST PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 = 7
CONST PIXELFORMAT_UNCOMPRESSED_R32 = 8
CONST PIXELFORMAT_UNCOMPRESSED_R32G32B32 = 9
CONST PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 = 10
CONST PIXELFORMAT_UNCOMPRESSED_R16 = 11
CONST PIXELFORMAT_UNCOMPRESSED_R16G16B16 = 12
CONST PIXELFORMAT_UNCOMPRESSED_R16G16B16A16 = 13
CONST PIXELFORMAT_COMPRESSED_DXT1_RGB = 14
CONST PIXELFORMAT_COMPRESSED_DXT1_RGBA = 15
CONST PIXELFORMAT_COMPRESSED_DXT3_RGBA = 16
CONST PIXELFORMAT_COMPRESSED_DXT5_RGBA = 17
CONST PIXELFORMAT_COMPRESSED_ETC1_RGB = 18
CONST PIXELFORMAT_COMPRESSED_ETC2_RGB = 19
CONST PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA = 20
CONST PIXELFORMAT_COMPRESSED_PVRT_RGB = 21
CONST PIXELFORMAT_COMPRESSED_PVRT_RGBA = 22
CONST PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA = 23
CONST PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA = 24
CONST TEXTURE_FILTER_POINT = 0
CONST TEXTURE_FILTER_BILINEAR = 1
CONST TEXTURE_FILTER_TRILINEAR = 2
CONST TEXTURE_FILTER_ANISOTROPIC_4X = 3
CONST TEXTURE_FILTER_ANISOTROPIC_8X = 4
CONST TEXTURE_FILTER_ANISOTROPIC_16X = 5
CONST TEXTURE_WRAP_REPEAT = 0
CONST TEXTURE_WRAP_CLAMP = 1
CONST TEXTURE_WRAP_MIRROR_REPEAT = 2
CONST TEXTURE_WRAP_MIRROR_CLAMP = 3
CONST CUBEMAP_LAYOUT_AUTO_DETECT = 0
CONST CUBEMAP_LAYOUT_LINE_VERTICAL = 1
CONST CUBEMAP_LAYOUT_LINE_HORIZONTAL = 2
CONST CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR = 3
CONST CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE = 4
CONST FONT_DEFAULT = 0
CONST FONT_BITMAP = 1
CONST FONT_SDF = 2
CONST BLEND_ALPHA = 0
CONST BLEND_ADDITIVE = 1
CONST BLEND_MULTIPLIED = 2
CONST BLEND_ADD_COLORS = 3
CONST BLEND_SUBTRACT_COLORS = 4
CONST BLEND_ALPHA_PREMULTIPLY = 5
CONST BLEND_CUSTOM = 6
CONST BLEND_CUSTOM_SEPARATE = 7
CONST GESTURE_NONE = 0
CONST GESTURE_TAP = 1
CONST GESTURE_DOUBLETAP = 2
CONST GESTURE_HOLD = 4
CONST GESTURE_DRAG = 8
CONST GESTURE_SWIPE_RIGHT = 16
CONST GESTURE_SWIPE_LEFT = 32
CONST GESTURE_SWIPE_UP = 64
CONST GESTURE_SWIPE_DOWN = 128
CONST GESTURE_PINCH_IN = 256
CONST GESTURE_PINCH_OUT = 512
CONST CAMERA_CUSTOM = 0
CONST CAMERA_FREE = 1
CONST CAMERA_ORBITAL = 2
CONST CAMERA_FIRST_PERSON = 3
CONST CAMERA_THIRD_PERSON = 4
CONST CAMERA_PERSPECTIVE = 0
CONST CAMERA_ORTHOGRAPHIC = 1
CONST NPATCH_NINE_PATCH = 0
CONST NPATCH_THREE_PATCH_VERTICAL = 1
CONST NPATCH_THREE_PATCH_HORIZONTAL = 2
'typedef TraceLogCallback = POINTER  (' aliased — referenced inline)
'typedef LoadFileDataCallback = POINTER  (' aliased — referenced inline)
'typedef SaveFileDataCallback = POINTER  (' aliased — referenced inline)
'typedef LoadFileTextCallback = POINTER  (' aliased — referenced inline)
'typedef SaveFileTextCallback = POINTER  (' aliased — referenced inline)
'typedef AudioCallback = POINTER  (' aliased — referenced inline)

CONST RAYLIB_VERSION_MAJOR = 5
CONST RAYLIB_VERSION_MINOR = 5
CONST RAYLIB_VERSION_PATCH = 0

DECLARE SUB      InitWindow LIB "raylib" ALIAS "InitWindow" (width AS INTEGER, height AS INTEGER, title AS POINTER)
DECLARE SUB      CloseWindow LIB "raylib" ALIAS "CloseWindow" ()
DECLARE FUNCTION WindowShouldClose LIB "raylib" ALIAS "WindowShouldClose" () AS BYTE
DECLARE FUNCTION IsWindowReady LIB "raylib" ALIAS "IsWindowReady" () AS BYTE
DECLARE FUNCTION IsWindowFullscreen LIB "raylib" ALIAS "IsWindowFullscreen" () AS BYTE
DECLARE FUNCTION IsWindowHidden LIB "raylib" ALIAS "IsWindowHidden" () AS BYTE
DECLARE FUNCTION IsWindowMinimized LIB "raylib" ALIAS "IsWindowMinimized" () AS BYTE
DECLARE FUNCTION IsWindowMaximized LIB "raylib" ALIAS "IsWindowMaximized" () AS BYTE
DECLARE FUNCTION IsWindowFocused LIB "raylib" ALIAS "IsWindowFocused" () AS BYTE
DECLARE FUNCTION IsWindowResized LIB "raylib" ALIAS "IsWindowResized" () AS BYTE
DECLARE FUNCTION IsWindowState LIB "raylib" ALIAS "IsWindowState" (flag AS DWORD) AS BYTE
DECLARE SUB      SetWindowState LIB "raylib" ALIAS "SetWindowState" (flags AS DWORD)
DECLARE SUB      ClearWindowState LIB "raylib" ALIAS "ClearWindowState" (flags AS DWORD)
DECLARE SUB      ToggleFullscreen LIB "raylib" ALIAS "ToggleFullscreen" ()
DECLARE SUB      ToggleBorderlessWindowed LIB "raylib" ALIAS "ToggleBorderlessWindowed" ()
DECLARE SUB      MaximizeWindow LIB "raylib" ALIAS "MaximizeWindow" ()
DECLARE SUB      MinimizeWindow LIB "raylib" ALIAS "MinimizeWindow" ()
DECLARE SUB      RestoreWindow LIB "raylib" ALIAS "RestoreWindow" ()
DECLARE SUB      SetWindowIcon LIB "raylib" ALIAS "SetWindowIcon" (image AS Image)
DECLARE SUB      SetWindowIcons LIB "raylib" ALIAS "SetWindowIcons" (images AS PImage, count AS INTEGER)
DECLARE SUB      SetWindowTitle LIB "raylib" ALIAS "SetWindowTitle" (title AS POINTER)
DECLARE SUB      SetWindowPosition LIB "raylib" ALIAS "SetWindowPosition" (x AS INTEGER, y AS INTEGER)
DECLARE SUB      SetWindowMonitor LIB "raylib" ALIAS "SetWindowMonitor" (monitor AS INTEGER)
DECLARE SUB      SetWindowMinSize LIB "raylib" ALIAS "SetWindowMinSize" (width AS INTEGER, height AS INTEGER)
DECLARE SUB      SetWindowMaxSize LIB "raylib" ALIAS "SetWindowMaxSize" (width AS INTEGER, height AS INTEGER)
DECLARE SUB      SetWindowSize LIB "raylib" ALIAS "SetWindowSize" (width AS INTEGER, height AS INTEGER)
DECLARE SUB      SetWindowOpacity LIB "raylib" ALIAS "SetWindowOpacity" (opacity AS SINGLE)
DECLARE SUB      SetWindowFocused LIB "raylib" ALIAS "SetWindowFocused" ()
DECLARE FUNCTION GetWindowHandle LIB "raylib" ALIAS "GetWindowHandle" () AS POINTER
DECLARE FUNCTION GetScreenWidth LIB "raylib" ALIAS "GetScreenWidth" () AS INTEGER
DECLARE FUNCTION GetScreenHeight LIB "raylib" ALIAS "GetScreenHeight" () AS INTEGER
DECLARE FUNCTION GetRenderWidth LIB "raylib" ALIAS "GetRenderWidth" () AS INTEGER
DECLARE FUNCTION GetRenderHeight LIB "raylib" ALIAS "GetRenderHeight" () AS INTEGER
DECLARE FUNCTION GetMonitorCount LIB "raylib" ALIAS "GetMonitorCount" () AS INTEGER
DECLARE FUNCTION GetCurrentMonitor LIB "raylib" ALIAS "GetCurrentMonitor" () AS INTEGER
DECLARE FUNCTION GetMonitorPosition LIB "raylib" ALIAS "GetMonitorPosition" (monitor AS INTEGER) AS Vector2
DECLARE FUNCTION GetMonitorWidth LIB "raylib" ALIAS "GetMonitorWidth" (monitor AS INTEGER) AS INTEGER
DECLARE FUNCTION GetMonitorHeight LIB "raylib" ALIAS "GetMonitorHeight" (monitor AS INTEGER) AS INTEGER
DECLARE FUNCTION GetMonitorPhysicalWidth LIB "raylib" ALIAS "GetMonitorPhysicalWidth" (monitor AS INTEGER) AS INTEGER
DECLARE FUNCTION GetMonitorPhysicalHeight LIB "raylib" ALIAS "GetMonitorPhysicalHeight" (monitor AS INTEGER) AS INTEGER
DECLARE FUNCTION GetMonitorRefreshRate LIB "raylib" ALIAS "GetMonitorRefreshRate" (monitor AS INTEGER) AS INTEGER
DECLARE FUNCTION GetWindowPosition LIB "raylib" ALIAS "GetWindowPosition" () AS Vector2
DECLARE FUNCTION GetWindowScaleDPI LIB "raylib" ALIAS "GetWindowScaleDPI" () AS Vector2
DECLARE FUNCTION GetMonitorName LIB "raylib" ALIAS "GetMonitorName" (monitor AS INTEGER) AS POINTER
DECLARE SUB      SetClipboardText LIB "raylib" ALIAS "SetClipboardText" (text AS POINTER)
DECLARE FUNCTION GetClipboardText LIB "raylib" ALIAS "GetClipboardText" () AS POINTER
DECLARE FUNCTION GetClipboardImage LIB "raylib" ALIAS "GetClipboardImage" () AS Image
DECLARE SUB      EnableEventWaiting LIB "raylib" ALIAS "EnableEventWaiting" ()
DECLARE SUB      DisableEventWaiting LIB "raylib" ALIAS "DisableEventWaiting" ()
DECLARE SUB      ShowCursor LIB "raylib" ALIAS "ShowCursor" ()
DECLARE SUB      HideCursor LIB "raylib" ALIAS "HideCursor" ()
DECLARE FUNCTION IsCursorHidden LIB "raylib" ALIAS "IsCursorHidden" () AS BYTE
DECLARE SUB      EnableCursor LIB "raylib" ALIAS "EnableCursor" ()
DECLARE SUB      DisableCursor LIB "raylib" ALIAS "DisableCursor" ()
DECLARE FUNCTION IsCursorOnScreen LIB "raylib" ALIAS "IsCursorOnScreen" () AS BYTE
DECLARE SUB      ClearBackground LIB "raylib" ALIAS "ClearBackground" (color AS Color)
DECLARE SUB      BeginDrawing LIB "raylib" ALIAS "BeginDrawing" ()
DECLARE SUB      EndDrawing LIB "raylib" ALIAS "EndDrawing" ()
DECLARE SUB      BeginMode2D LIB "raylib" ALIAS "BeginMode2D" (camera AS Camera2D)
DECLARE SUB      EndMode2D LIB "raylib" ALIAS "EndMode2D" ()
DECLARE SUB      BeginMode3D LIB "raylib" ALIAS "BeginMode3D" (camera AS Camera3D)
DECLARE SUB      EndMode3D LIB "raylib" ALIAS "EndMode3D" ()
DECLARE SUB      BeginTextureMode LIB "raylib" ALIAS "BeginTextureMode" (target AS POINTER)
DECLARE SUB      EndTextureMode LIB "raylib" ALIAS "EndTextureMode" ()
DECLARE SUB      BeginShaderMode LIB "raylib" ALIAS "BeginShaderMode" (shader AS Shader)
DECLARE SUB      EndShaderMode LIB "raylib" ALIAS "EndShaderMode" ()
DECLARE SUB      BeginBlendMode LIB "raylib" ALIAS "BeginBlendMode" (mode AS INTEGER)
DECLARE SUB      EndBlendMode LIB "raylib" ALIAS "EndBlendMode" ()
DECLARE SUB      BeginScissorMode LIB "raylib" ALIAS "BeginScissorMode" (x AS INTEGER, y AS INTEGER, width AS INTEGER, height AS INTEGER)
DECLARE SUB      EndScissorMode LIB "raylib" ALIAS "EndScissorMode" ()
DECLARE SUB      BeginVrStereoMode LIB "raylib" ALIAS "BeginVrStereoMode" (config AS VrStereoConfig)
DECLARE SUB      EndVrStereoMode LIB "raylib" ALIAS "EndVrStereoMode" ()
DECLARE FUNCTION LoadVrStereoConfig LIB "raylib" ALIAS "LoadVrStereoConfig" (device AS VrDeviceInfo) AS VrStereoConfig
DECLARE SUB      UnloadVrStereoConfig LIB "raylib" ALIAS "UnloadVrStereoConfig" (config AS VrStereoConfig)
DECLARE FUNCTION LoadShader LIB "raylib" ALIAS "LoadShader" (vsFileName AS POINTER, fsFileName AS POINTER) AS Shader
DECLARE FUNCTION LoadShaderFromMemory LIB "raylib" ALIAS "LoadShaderFromMemory" (vsCode AS POINTER, fsCode AS POINTER) AS Shader
DECLARE FUNCTION IsShaderValid LIB "raylib" ALIAS "IsShaderValid" (shader AS Shader) AS BYTE
DECLARE FUNCTION GetShaderLocation LIB "raylib" ALIAS "GetShaderLocation" (shader AS Shader, uniformName AS POINTER) AS INTEGER
DECLARE FUNCTION GetShaderLocationAttrib LIB "raylib" ALIAS "GetShaderLocationAttrib" (shader AS Shader, attribName AS POINTER) AS INTEGER
DECLARE SUB      SetShaderValue LIB "raylib" ALIAS "SetShaderValue" (shader AS Shader, locIndex AS INTEGER, value AS POINTER, uniformType AS INTEGER)
DECLARE SUB      SetShaderValueV LIB "raylib" ALIAS "SetShaderValueV" (shader AS Shader, locIndex AS INTEGER, value AS POINTER, uniformType AS INTEGER, count AS INTEGER)
DECLARE SUB      SetShaderValueMatrix LIB "raylib" ALIAS "SetShaderValueMatrix" (shader AS Shader, locIndex AS INTEGER, mat AS Matrix)
DECLARE SUB      SetShaderValueTexture LIB "raylib" ALIAS "SetShaderValueTexture" (shader AS Shader, locIndex AS INTEGER, texture AS POINTER)
DECLARE SUB      UnloadShader LIB "raylib" ALIAS "UnloadShader" (shader AS Shader)
DECLARE FUNCTION GetScreenToWorldRay LIB "raylib" ALIAS "GetScreenToWorldRay" (position AS Vector2, camera AS POINTER) AS Ray
DECLARE FUNCTION GetScreenToWorldRayEx LIB "raylib" ALIAS "GetScreenToWorldRayEx" (position AS Vector2, camera AS POINTER, width AS INTEGER, height AS INTEGER) AS Ray
DECLARE FUNCTION GetWorldToScreen LIB "raylib" ALIAS "GetWorldToScreen" (position AS Vector3, camera AS POINTER) AS Vector2
DECLARE FUNCTION GetWorldToScreenEx LIB "raylib" ALIAS "GetWorldToScreenEx" (position AS Vector3, camera AS POINTER, width AS INTEGER, height AS INTEGER) AS Vector2
DECLARE FUNCTION GetWorldToScreen2D LIB "raylib" ALIAS "GetWorldToScreen2D" (position AS Vector2, camera AS Camera2D) AS Vector2
DECLARE FUNCTION GetScreenToWorld2D LIB "raylib" ALIAS "GetScreenToWorld2D" (position AS Vector2, camera AS Camera2D) AS Vector2
DECLARE FUNCTION GetCameraMatrix LIB "raylib" ALIAS "GetCameraMatrix" (camera AS POINTER) AS Matrix
DECLARE FUNCTION GetCameraMatrix2D LIB "raylib" ALIAS "GetCameraMatrix2D" (camera AS Camera2D) AS Matrix
DECLARE SUB      SetTargetFPS LIB "raylib" ALIAS "SetTargetFPS" (fps AS INTEGER)
DECLARE FUNCTION GetFrameTime LIB "raylib" ALIAS "GetFrameTime" () AS SINGLE
DECLARE FUNCTION GetTime LIB "raylib" ALIAS "GetTime" () AS DOUBLE
DECLARE FUNCTION GetFPS LIB "raylib" ALIAS "GetFPS" () AS INTEGER
DECLARE SUB      SwapScreenBuffer LIB "raylib" ALIAS "SwapScreenBuffer" ()
DECLARE SUB      PollInputEvents LIB "raylib" ALIAS "PollInputEvents" ()
DECLARE SUB      WaitTime LIB "raylib" ALIAS "WaitTime" (seconds AS DOUBLE)
DECLARE SUB      SetRandomSeed LIB "raylib" ALIAS "SetRandomSeed" (seed AS DWORD)
DECLARE FUNCTION GetRandomValue LIB "raylib" ALIAS "GetRandomValue" (min AS INTEGER, max AS INTEGER) AS INTEGER
DECLARE FUNCTION LoadRandomSequence LIB "raylib" ALIAS "LoadRandomSequence" (count AS DWORD, min AS INTEGER, max AS INTEGER) AS POINTER
DECLARE SUB      UnloadRandomSequence LIB "raylib" ALIAS "UnloadRandomSequence" (sequence AS POINTER)
DECLARE SUB      TakeScreenshot LIB "raylib" ALIAS "TakeScreenshot" (fileName AS POINTER)
DECLARE SUB      SetConfigFlags LIB "raylib" ALIAS "SetConfigFlags" (flags AS DWORD)
DECLARE SUB      OpenURL LIB "raylib" ALIAS "OpenURL" (url AS POINTER)
DECLARE SUB      TraceLog LIB "raylib" ALIAS "TraceLog" (logLevel AS INTEGER, text AS POINTER)  ' varargs — call via wrapper
DECLARE SUB      SetTraceLogLevel LIB "raylib" ALIAS "SetTraceLogLevel" (logLevel AS INTEGER)
DECLARE FUNCTION MemAlloc LIB "raylib" ALIAS "MemAlloc" (size AS DWORD) AS POINTER
DECLARE FUNCTION MemRealloc LIB "raylib" ALIAS "MemRealloc" (ptr AS POINTER, size AS DWORD) AS POINTER
DECLARE SUB      MemFree LIB "raylib" ALIAS "MemFree" (ptr AS POINTER)
DECLARE SUB      SetTraceLogCallback LIB "raylib" ALIAS "SetTraceLogCallback" (callback AS POINTER)
DECLARE SUB      SetLoadFileDataCallback LIB "raylib" ALIAS "SetLoadFileDataCallback" (callback AS POINTER)
DECLARE SUB      SetSaveFileDataCallback LIB "raylib" ALIAS "SetSaveFileDataCallback" (callback AS POINTER)
DECLARE SUB      SetLoadFileTextCallback LIB "raylib" ALIAS "SetLoadFileTextCallback" (callback AS POINTER)
DECLARE SUB      SetSaveFileTextCallback LIB "raylib" ALIAS "SetSaveFileTextCallback" (callback AS POINTER)
DECLARE FUNCTION LoadFileData LIB "raylib" ALIAS "LoadFileData" (fileName AS POINTER, dataSize AS POINTER) AS POINTER
DECLARE SUB      UnloadFileData LIB "raylib" ALIAS "UnloadFileData" (data AS POINTER)
DECLARE FUNCTION SaveFileData LIB "raylib" ALIAS "SaveFileData" (fileName AS POINTER, data AS POINTER, dataSize AS INTEGER) AS BYTE
DECLARE FUNCTION ExportDataAsCode LIB "raylib" ALIAS "ExportDataAsCode" (data AS POINTER, dataSize AS INTEGER, fileName AS POINTER) AS BYTE
DECLARE FUNCTION LoadFileText LIB "raylib" ALIAS "LoadFileText" (fileName AS POINTER) AS POINTER
DECLARE SUB      UnloadFileText LIB "raylib" ALIAS "UnloadFileText" (text AS POINTER)
DECLARE FUNCTION SaveFileText LIB "raylib" ALIAS "SaveFileText" (fileName AS POINTER, text AS POINTER) AS BYTE
DECLARE FUNCTION FileExists LIB "raylib" ALIAS "FileExists" (fileName AS POINTER) AS BYTE
DECLARE FUNCTION DirectoryExists LIB "raylib" ALIAS "DirectoryExists" (dirPath AS POINTER) AS BYTE
DECLARE FUNCTION IsFileExtension LIB "raylib" ALIAS "IsFileExtension" (fileName AS POINTER, ext AS POINTER) AS BYTE
DECLARE FUNCTION GetFileLength LIB "raylib" ALIAS "GetFileLength" (fileName AS POINTER) AS INTEGER
DECLARE FUNCTION GetFileExtension LIB "raylib" ALIAS "GetFileExtension" (fileName AS POINTER) AS POINTER
DECLARE FUNCTION GetFileName LIB "raylib" ALIAS "GetFileName" (filePath AS POINTER) AS POINTER
DECLARE FUNCTION GetFileNameWithoutExt LIB "raylib" ALIAS "GetFileNameWithoutExt" (filePath AS POINTER) AS POINTER
DECLARE FUNCTION GetDirectoryPath LIB "raylib" ALIAS "GetDirectoryPath" (filePath AS POINTER) AS POINTER
DECLARE FUNCTION GetPrevDirectoryPath LIB "raylib" ALIAS "GetPrevDirectoryPath" (dirPath AS POINTER) AS POINTER
DECLARE FUNCTION GetWorkingDirectory LIB "raylib" ALIAS "GetWorkingDirectory" () AS POINTER
DECLARE FUNCTION GetApplicationDirectory LIB "raylib" ALIAS "GetApplicationDirectory" () AS POINTER
DECLARE FUNCTION MakeDirectory LIB "raylib" ALIAS "MakeDirectory" (dirPath AS POINTER) AS INTEGER
DECLARE FUNCTION ChangeDirectory LIB "raylib" ALIAS "ChangeDirectory" (dir AS POINTER) AS BYTE
DECLARE FUNCTION IsPathFile LIB "raylib" ALIAS "IsPathFile" (path AS POINTER) AS BYTE
DECLARE FUNCTION IsFileNameValid LIB "raylib" ALIAS "IsFileNameValid" (fileName AS POINTER) AS BYTE
DECLARE FUNCTION LoadDirectoryFiles LIB "raylib" ALIAS "LoadDirectoryFiles" (dirPath AS POINTER) AS FilePathList
DECLARE FUNCTION LoadDirectoryFilesEx LIB "raylib" ALIAS "LoadDirectoryFilesEx" (basePath AS POINTER, filter AS POINTER, scanSubdirs AS BYTE) AS FilePathList
DECLARE SUB      UnloadDirectoryFiles LIB "raylib" ALIAS "UnloadDirectoryFiles" (files AS FilePathList)
DECLARE FUNCTION IsFileDropped LIB "raylib" ALIAS "IsFileDropped" () AS BYTE
DECLARE FUNCTION LoadDroppedFiles LIB "raylib" ALIAS "LoadDroppedFiles" () AS FilePathList
DECLARE SUB      UnloadDroppedFiles LIB "raylib" ALIAS "UnloadDroppedFiles" (files AS FilePathList)
DECLARE FUNCTION GetFileModTime LIB "raylib" ALIAS "GetFileModTime" (fileName AS POINTER) AS INT64
DECLARE FUNCTION CompressData LIB "raylib" ALIAS "CompressData" (data AS POINTER, dataSize AS INTEGER, compDataSize AS POINTER) AS POINTER
DECLARE FUNCTION DecompressData LIB "raylib" ALIAS "DecompressData" (compData AS POINTER, compDataSize AS INTEGER, dataSize AS POINTER) AS POINTER
DECLARE FUNCTION EncodeDataBase64 LIB "raylib" ALIAS "EncodeDataBase64" (data AS POINTER, dataSize AS INTEGER, outputSize AS POINTER) AS POINTER
DECLARE FUNCTION DecodeDataBase64 LIB "raylib" ALIAS "DecodeDataBase64" (data AS POINTER, outputSize AS POINTER) AS POINTER
DECLARE FUNCTION ComputeCRC32 LIB "raylib" ALIAS "ComputeCRC32" (data AS POINTER, dataSize AS INTEGER) AS DWORD
DECLARE FUNCTION ComputeMD5 LIB "raylib" ALIAS "ComputeMD5" (data AS POINTER, dataSize AS INTEGER) AS POINTER
DECLARE FUNCTION ComputeSHA1 LIB "raylib" ALIAS "ComputeSHA1" (data AS POINTER, dataSize AS INTEGER) AS POINTER
DECLARE FUNCTION LoadAutomationEventList LIB "raylib" ALIAS "LoadAutomationEventList" (fileName AS POINTER) AS AutomationEventList
DECLARE SUB      UnloadAutomationEventList LIB "raylib" ALIAS "UnloadAutomationEventList" (list AS AutomationEventList)
DECLARE FUNCTION ExportAutomationEventList LIB "raylib" ALIAS "ExportAutomationEventList" (list AS AutomationEventList, fileName AS POINTER) AS BYTE
DECLARE SUB      SetAutomationEventList LIB "raylib" ALIAS "SetAutomationEventList" (list AS PAutomationEventList)
DECLARE SUB      SetAutomationEventBaseFrame LIB "raylib" ALIAS "SetAutomationEventBaseFrame" (frame AS INTEGER)
DECLARE SUB      StartAutomationEventRecording LIB "raylib" ALIAS "StartAutomationEventRecording" ()
DECLARE SUB      StopAutomationEventRecording LIB "raylib" ALIAS "StopAutomationEventRecording" ()
DECLARE SUB      PlayAutomationEvent LIB "raylib" ALIAS "PlayAutomationEvent" (event_ AS AutomationEvent)
DECLARE FUNCTION IsKeyPressed LIB "raylib" ALIAS "IsKeyPressed" (key AS INTEGER) AS BYTE
DECLARE FUNCTION IsKeyPressedRepeat LIB "raylib" ALIAS "IsKeyPressedRepeat" (key AS INTEGER) AS BYTE
DECLARE FUNCTION IsKeyDown LIB "raylib" ALIAS "IsKeyDown" (key AS INTEGER) AS BYTE
DECLARE FUNCTION IsKeyReleased LIB "raylib" ALIAS "IsKeyReleased" (key AS INTEGER) AS BYTE
DECLARE FUNCTION IsKeyUp LIB "raylib" ALIAS "IsKeyUp" (key AS INTEGER) AS BYTE
DECLARE FUNCTION GetKeyPressed LIB "raylib" ALIAS "GetKeyPressed" () AS INTEGER
DECLARE FUNCTION GetCharPressed LIB "raylib" ALIAS "GetCharPressed" () AS INTEGER
DECLARE SUB      SetExitKey LIB "raylib" ALIAS "SetExitKey" (key AS INTEGER)
DECLARE FUNCTION IsGamepadAvailable LIB "raylib" ALIAS "IsGamepadAvailable" (gamepad AS INTEGER) AS BYTE
DECLARE FUNCTION GetGamepadName LIB "raylib" ALIAS "GetGamepadName" (gamepad AS INTEGER) AS POINTER
DECLARE FUNCTION IsGamepadButtonPressed LIB "raylib" ALIAS "IsGamepadButtonPressed" (gamepad AS INTEGER, button AS INTEGER) AS BYTE
DECLARE FUNCTION IsGamepadButtonDown LIB "raylib" ALIAS "IsGamepadButtonDown" (gamepad AS INTEGER, button AS INTEGER) AS BYTE
DECLARE FUNCTION IsGamepadButtonReleased LIB "raylib" ALIAS "IsGamepadButtonReleased" (gamepad AS INTEGER, button AS INTEGER) AS BYTE
DECLARE FUNCTION IsGamepadButtonUp LIB "raylib" ALIAS "IsGamepadButtonUp" (gamepad AS INTEGER, button AS INTEGER) AS BYTE
DECLARE FUNCTION GetGamepadButtonPressed LIB "raylib" ALIAS "GetGamepadButtonPressed" () AS INTEGER
DECLARE FUNCTION GetGamepadAxisCount LIB "raylib" ALIAS "GetGamepadAxisCount" (gamepad AS INTEGER) AS INTEGER
DECLARE FUNCTION GetGamepadAxisMovement LIB "raylib" ALIAS "GetGamepadAxisMovement" (gamepad AS INTEGER, axis AS INTEGER) AS SINGLE
DECLARE FUNCTION SetGamepadMappings LIB "raylib" ALIAS "SetGamepadMappings" (mappings AS POINTER) AS INTEGER
DECLARE SUB      SetGamepadVibration LIB "raylib" ALIAS "SetGamepadVibration" (gamepad AS INTEGER, leftMotor AS SINGLE, rightMotor AS SINGLE, duration AS SINGLE)
DECLARE FUNCTION IsMouseButtonPressed LIB "raylib" ALIAS "IsMouseButtonPressed" (button AS INTEGER) AS BYTE
DECLARE FUNCTION IsMouseButtonDown LIB "raylib" ALIAS "IsMouseButtonDown" (button AS INTEGER) AS BYTE
DECLARE FUNCTION IsMouseButtonReleased LIB "raylib" ALIAS "IsMouseButtonReleased" (button AS INTEGER) AS BYTE
DECLARE FUNCTION IsMouseButtonUp LIB "raylib" ALIAS "IsMouseButtonUp" (button AS INTEGER) AS BYTE
DECLARE FUNCTION GetMouseX LIB "raylib" ALIAS "GetMouseX" () AS INTEGER
DECLARE FUNCTION GetMouseY LIB "raylib" ALIAS "GetMouseY" () AS INTEGER
DECLARE FUNCTION GetMousePosition LIB "raylib" ALIAS "GetMousePosition" () AS Vector2
DECLARE FUNCTION GetMouseDelta LIB "raylib" ALIAS "GetMouseDelta" () AS Vector2
DECLARE SUB      SetMousePosition LIB "raylib" ALIAS "SetMousePosition" (x AS INTEGER, y AS INTEGER)
DECLARE SUB      SetMouseOffset LIB "raylib" ALIAS "SetMouseOffset" (offsetX AS INTEGER, offsetY AS INTEGER)
DECLARE SUB      SetMouseScale LIB "raylib" ALIAS "SetMouseScale" (scaleX AS SINGLE, scaleY AS SINGLE)
DECLARE FUNCTION GetMouseWheelMove LIB "raylib" ALIAS "GetMouseWheelMove" () AS SINGLE
DECLARE FUNCTION GetMouseWheelMoveV LIB "raylib" ALIAS "GetMouseWheelMoveV" () AS Vector2
DECLARE SUB      SetMouseCursor LIB "raylib" ALIAS "SetMouseCursor" (cursor AS INTEGER)
DECLARE FUNCTION GetTouchX LIB "raylib" ALIAS "GetTouchX" () AS INTEGER
DECLARE FUNCTION GetTouchY LIB "raylib" ALIAS "GetTouchY" () AS INTEGER
DECLARE FUNCTION GetTouchPosition LIB "raylib" ALIAS "GetTouchPosition" (index AS INTEGER) AS Vector2
DECLARE FUNCTION GetTouchPointId LIB "raylib" ALIAS "GetTouchPointId" (index AS INTEGER) AS INTEGER
DECLARE FUNCTION GetTouchPointCount LIB "raylib" ALIAS "GetTouchPointCount" () AS INTEGER
DECLARE SUB      SetGesturesEnabled LIB "raylib" ALIAS "SetGesturesEnabled" (flags AS DWORD)
DECLARE FUNCTION IsGestureDetected LIB "raylib" ALIAS "IsGestureDetected" (gesture AS DWORD) AS BYTE
DECLARE FUNCTION GetGestureDetected LIB "raylib" ALIAS "GetGestureDetected" () AS INTEGER
DECLARE FUNCTION GetGestureHoldDuration LIB "raylib" ALIAS "GetGestureHoldDuration" () AS SINGLE
DECLARE FUNCTION GetGestureDragVector LIB "raylib" ALIAS "GetGestureDragVector" () AS Vector2
DECLARE FUNCTION GetGestureDragAngle LIB "raylib" ALIAS "GetGestureDragAngle" () AS SINGLE
DECLARE FUNCTION GetGesturePinchVector LIB "raylib" ALIAS "GetGesturePinchVector" () AS Vector2
DECLARE FUNCTION GetGesturePinchAngle LIB "raylib" ALIAS "GetGesturePinchAngle" () AS SINGLE
DECLARE SUB      UpdateCamera LIB "raylib" ALIAS "UpdateCamera" (camera AS POINTER, mode AS INTEGER)
DECLARE SUB      UpdateCameraPro LIB "raylib" ALIAS "UpdateCameraPro" (camera AS POINTER, movement AS Vector3, rotation AS Vector3, zoom AS SINGLE)
DECLARE SUB      SetShapesTexture LIB "raylib" ALIAS "SetShapesTexture" (texture AS POINTER, source AS Rectangle)
DECLARE FUNCTION GetShapesTexture LIB "raylib" ALIAS "GetShapesTexture" () AS POINTER
DECLARE FUNCTION GetShapesTextureRectangle LIB "raylib" ALIAS "GetShapesTextureRectangle" () AS Rectangle
DECLARE SUB      DrawPixel LIB "raylib" ALIAS "DrawPixel" (posX AS INTEGER, posY AS INTEGER, color AS Color)
DECLARE SUB      DrawPixelV LIB "raylib" ALIAS "DrawPixelV" (position AS Vector2, color AS Color)
DECLARE SUB      DrawLine LIB "raylib" ALIAS "DrawLine" (startPosX AS INTEGER, startPosY AS INTEGER, endPosX AS INTEGER, endPosY AS INTEGER, color AS Color)
DECLARE SUB      DrawLineV LIB "raylib" ALIAS "DrawLineV" (startPos AS Vector2, endPos AS Vector2, color AS Color)
DECLARE SUB      DrawLineEx LIB "raylib" ALIAS "DrawLineEx" (startPos AS Vector2, endPos AS Vector2, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawLineStrip LIB "raylib" ALIAS "DrawLineStrip" (points AS PVector2, pointCount AS INTEGER, color AS Color)
DECLARE SUB      DrawLineBezier LIB "raylib" ALIAS "DrawLineBezier" (startPos AS Vector2, endPos AS Vector2, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawCircle LIB "raylib" ALIAS "DrawCircle" (centerX AS INTEGER, centerY AS INTEGER, radius AS SINGLE, color AS Color)
DECLARE SUB      DrawCircleSector LIB "raylib" ALIAS "DrawCircleSector" (center AS Vector2, radius AS SINGLE, startAngle AS SINGLE, endAngle AS SINGLE, segments AS INTEGER, color AS Color)
DECLARE SUB      DrawCircleSectorLines LIB "raylib" ALIAS "DrawCircleSectorLines" (center AS Vector2, radius AS SINGLE, startAngle AS SINGLE, endAngle AS SINGLE, segments AS INTEGER, color AS Color)
DECLARE SUB      DrawCircleGradient LIB "raylib" ALIAS "DrawCircleGradient" (centerX AS INTEGER, centerY AS INTEGER, radius AS SINGLE, inner AS Color, outer AS Color)
DECLARE SUB      DrawCircleV LIB "raylib" ALIAS "DrawCircleV" (center AS Vector2, radius AS SINGLE, color AS Color)
DECLARE SUB      DrawCircleLines LIB "raylib" ALIAS "DrawCircleLines" (centerX AS INTEGER, centerY AS INTEGER, radius AS SINGLE, color AS Color)
DECLARE SUB      DrawCircleLinesV LIB "raylib" ALIAS "DrawCircleLinesV" (center AS Vector2, radius AS SINGLE, color AS Color)
DECLARE SUB      DrawEllipse LIB "raylib" ALIAS "DrawEllipse" (centerX AS INTEGER, centerY AS INTEGER, radiusH AS SINGLE, radiusV AS SINGLE, color AS Color)
DECLARE SUB      DrawEllipseLines LIB "raylib" ALIAS "DrawEllipseLines" (centerX AS INTEGER, centerY AS INTEGER, radiusH AS SINGLE, radiusV AS SINGLE, color AS Color)
DECLARE SUB      DrawRing LIB "raylib" ALIAS "DrawRing" (center AS Vector2, innerRadius AS SINGLE, outerRadius AS SINGLE, startAngle AS SINGLE, endAngle AS SINGLE, segments AS INTEGER, color AS Color)
DECLARE SUB      DrawRingLines LIB "raylib" ALIAS "DrawRingLines" (center AS Vector2, innerRadius AS SINGLE, outerRadius AS SINGLE, startAngle AS SINGLE, endAngle AS SINGLE, segments AS INTEGER, color AS Color)
DECLARE SUB      DrawRectangle LIB "raylib" ALIAS "DrawRectangle" (posX AS INTEGER, posY AS INTEGER, width AS INTEGER, height AS INTEGER, color AS Color)
DECLARE SUB      DrawRectangleV LIB "raylib" ALIAS "DrawRectangleV" (position AS Vector2, size AS Vector2, color AS Color)
DECLARE SUB      DrawRectangleRec LIB "raylib" ALIAS "DrawRectangleRec" (rec AS Rectangle, color AS Color)
DECLARE SUB      DrawRectanglePro LIB "raylib" ALIAS "DrawRectanglePro" (rec AS Rectangle, origin AS Vector2, rotation AS SINGLE, color AS Color)
DECLARE SUB      DrawRectangleGradientV LIB "raylib" ALIAS "DrawRectangleGradientV" (posX AS INTEGER, posY AS INTEGER, width AS INTEGER, height AS INTEGER, top AS Color, bottom AS Color)
DECLARE SUB      DrawRectangleGradientH LIB "raylib" ALIAS "DrawRectangleGradientH" (posX AS INTEGER, posY AS INTEGER, width AS INTEGER, height AS INTEGER, left AS Color, right AS Color)
DECLARE SUB      DrawRectangleGradientEx LIB "raylib" ALIAS "DrawRectangleGradientEx" (rec AS Rectangle, topLeft AS Color, bottomLeft AS Color, topRight AS Color, bottomRight AS Color)
DECLARE SUB      DrawRectangleLines LIB "raylib" ALIAS "DrawRectangleLines" (posX AS INTEGER, posY AS INTEGER, width AS INTEGER, height AS INTEGER, color AS Color)
DECLARE SUB      DrawRectangleLinesEx LIB "raylib" ALIAS "DrawRectangleLinesEx" (rec AS Rectangle, lineThick AS SINGLE, color AS Color)
DECLARE SUB      DrawRectangleRounded LIB "raylib" ALIAS "DrawRectangleRounded" (rec AS Rectangle, roundness AS SINGLE, segments AS INTEGER, color AS Color)
DECLARE SUB      DrawRectangleRoundedLines LIB "raylib" ALIAS "DrawRectangleRoundedLines" (rec AS Rectangle, roundness AS SINGLE, segments AS INTEGER, color AS Color)
DECLARE SUB      DrawRectangleRoundedLinesEx LIB "raylib" ALIAS "DrawRectangleRoundedLinesEx" (rec AS Rectangle, roundness AS SINGLE, segments AS INTEGER, lineThick AS SINGLE, color AS Color)
DECLARE SUB      DrawTriangle LIB "raylib" ALIAS "DrawTriangle" (v1 AS Vector2, v2 AS Vector2, v3 AS Vector2, color AS Color)
DECLARE SUB      DrawTriangleLines LIB "raylib" ALIAS "DrawTriangleLines" (v1 AS Vector2, v2 AS Vector2, v3 AS Vector2, color AS Color)
DECLARE SUB      DrawTriangleFan LIB "raylib" ALIAS "DrawTriangleFan" (points AS PVector2, pointCount AS INTEGER, color AS Color)
DECLARE SUB      DrawTriangleStrip LIB "raylib" ALIAS "DrawTriangleStrip" (points AS PVector2, pointCount AS INTEGER, color AS Color)
DECLARE SUB      DrawPoly LIB "raylib" ALIAS "DrawPoly" (center AS Vector2, sides AS INTEGER, radius AS SINGLE, rotation AS SINGLE, color AS Color)
DECLARE SUB      DrawPolyLines LIB "raylib" ALIAS "DrawPolyLines" (center AS Vector2, sides AS INTEGER, radius AS SINGLE, rotation AS SINGLE, color AS Color)
DECLARE SUB      DrawPolyLinesEx LIB "raylib" ALIAS "DrawPolyLinesEx" (center AS Vector2, sides AS INTEGER, radius AS SINGLE, rotation AS SINGLE, lineThick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineLinear LIB "raylib" ALIAS "DrawSplineLinear" (points AS PVector2, pointCount AS INTEGER, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineBasis LIB "raylib" ALIAS "DrawSplineBasis" (points AS PVector2, pointCount AS INTEGER, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineCatmullRom LIB "raylib" ALIAS "DrawSplineCatmullRom" (points AS PVector2, pointCount AS INTEGER, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineBezierQuadratic LIB "raylib" ALIAS "DrawSplineBezierQuadratic" (points AS PVector2, pointCount AS INTEGER, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineBezierCubic LIB "raylib" ALIAS "DrawSplineBezierCubic" (points AS PVector2, pointCount AS INTEGER, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineSegmentLinear LIB "raylib" ALIAS "DrawSplineSegmentLinear" (p1 AS Vector2, p2 AS Vector2, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineSegmentBasis LIB "raylib" ALIAS "DrawSplineSegmentBasis" (p1 AS Vector2, p2 AS Vector2, p3 AS Vector2, p4 AS Vector2, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineSegmentCatmullRom LIB "raylib" ALIAS "DrawSplineSegmentCatmullRom" (p1 AS Vector2, p2 AS Vector2, p3 AS Vector2, p4 AS Vector2, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineSegmentBezierQuadratic LIB "raylib" ALIAS "DrawSplineSegmentBezierQuadratic" (p1 AS Vector2, c2 AS Vector2, p3 AS Vector2, thick AS SINGLE, color AS Color)
DECLARE SUB      DrawSplineSegmentBezierCubic LIB "raylib" ALIAS "DrawSplineSegmentBezierCubic" (p1 AS Vector2, c2 AS Vector2, c3 AS Vector2, p4 AS Vector2, thick AS SINGLE, color AS Color)
DECLARE FUNCTION GetSplinePointLinear LIB "raylib" ALIAS "GetSplinePointLinear" (startPos AS Vector2, endPos AS Vector2, t AS SINGLE) AS Vector2
DECLARE FUNCTION GetSplinePointBasis LIB "raylib" ALIAS "GetSplinePointBasis" (p1 AS Vector2, p2 AS Vector2, p3 AS Vector2, p4 AS Vector2, t AS SINGLE) AS Vector2
DECLARE FUNCTION GetSplinePointCatmullRom LIB "raylib" ALIAS "GetSplinePointCatmullRom" (p1 AS Vector2, p2 AS Vector2, p3 AS Vector2, p4 AS Vector2, t AS SINGLE) AS Vector2
DECLARE FUNCTION GetSplinePointBezierQuad LIB "raylib" ALIAS "GetSplinePointBezierQuad" (p1 AS Vector2, c2 AS Vector2, p3 AS Vector2, t AS SINGLE) AS Vector2
DECLARE FUNCTION GetSplinePointBezierCubic LIB "raylib" ALIAS "GetSplinePointBezierCubic" (p1 AS Vector2, c2 AS Vector2, c3 AS Vector2, p4 AS Vector2, t AS SINGLE) AS Vector2
DECLARE FUNCTION CheckCollisionRecs LIB "raylib" ALIAS "CheckCollisionRecs" (rec1 AS Rectangle, rec2 AS Rectangle) AS BYTE
DECLARE FUNCTION CheckCollisionCircles LIB "raylib" ALIAS "CheckCollisionCircles" (center1 AS Vector2, radius1 AS SINGLE, center2 AS Vector2, radius2 AS SINGLE) AS BYTE
DECLARE FUNCTION CheckCollisionCircleRec LIB "raylib" ALIAS "CheckCollisionCircleRec" (center AS Vector2, radius AS SINGLE, rec AS Rectangle) AS BYTE
DECLARE FUNCTION CheckCollisionCircleLine LIB "raylib" ALIAS "CheckCollisionCircleLine" (center AS Vector2, radius AS SINGLE, p1 AS Vector2, p2 AS Vector2) AS BYTE
DECLARE FUNCTION CheckCollisionPointRec LIB "raylib" ALIAS "CheckCollisionPointRec" (point AS Vector2, rec AS Rectangle) AS BYTE
DECLARE FUNCTION CheckCollisionPointCircle LIB "raylib" ALIAS "CheckCollisionPointCircle" (point AS Vector2, center AS Vector2, radius AS SINGLE) AS BYTE
DECLARE FUNCTION CheckCollisionPointTriangle LIB "raylib" ALIAS "CheckCollisionPointTriangle" (point AS Vector2, p1 AS Vector2, p2 AS Vector2, p3 AS Vector2) AS BYTE
DECLARE FUNCTION CheckCollisionPointLine LIB "raylib" ALIAS "CheckCollisionPointLine" (point AS Vector2, p1 AS Vector2, p2 AS Vector2, threshold AS INTEGER) AS BYTE
DECLARE FUNCTION CheckCollisionPointPoly LIB "raylib" ALIAS "CheckCollisionPointPoly" (point AS Vector2, points AS PVector2, pointCount AS INTEGER) AS BYTE
DECLARE FUNCTION CheckCollisionLines LIB "raylib" ALIAS "CheckCollisionLines" (startPos1 AS Vector2, endPos1 AS Vector2, startPos2 AS Vector2, endPos2 AS Vector2, collisionPoint AS PVector2) AS BYTE
DECLARE FUNCTION GetCollisionRec LIB "raylib" ALIAS "GetCollisionRec" (rec1 AS Rectangle, rec2 AS Rectangle) AS Rectangle
DECLARE FUNCTION LoadImage LIB "raylib" ALIAS "LoadImage" (fileName AS POINTER) AS Image
DECLARE FUNCTION LoadImageRaw LIB "raylib" ALIAS "LoadImageRaw" (fileName AS POINTER, width AS INTEGER, height AS INTEGER, format AS INTEGER, headerSize AS INTEGER) AS Image
DECLARE FUNCTION LoadImageAnim LIB "raylib" ALIAS "LoadImageAnim" (fileName AS POINTER, frames AS POINTER) AS Image
DECLARE FUNCTION LoadImageAnimFromMemory LIB "raylib" ALIAS "LoadImageAnimFromMemory" (fileType AS POINTER, fileData AS POINTER, dataSize AS INTEGER, frames AS POINTER) AS Image
DECLARE FUNCTION LoadImageFromMemory LIB "raylib" ALIAS "LoadImageFromMemory" (fileType AS POINTER, fileData AS POINTER, dataSize AS INTEGER) AS Image
DECLARE FUNCTION LoadImageFromTexture LIB "raylib" ALIAS "LoadImageFromTexture" (texture AS POINTER) AS Image
DECLARE FUNCTION LoadImageFromScreen LIB "raylib" ALIAS "LoadImageFromScreen" () AS Image
DECLARE FUNCTION IsImageValid LIB "raylib" ALIAS "IsImageValid" (image AS Image) AS BYTE
DECLARE SUB      UnloadImage LIB "raylib" ALIAS "UnloadImage" (image AS Image)
DECLARE FUNCTION ExportImage LIB "raylib" ALIAS "ExportImage" (image AS Image, fileName AS POINTER) AS BYTE
DECLARE FUNCTION ExportImageToMemory LIB "raylib" ALIAS "ExportImageToMemory" (image AS Image, fileType AS POINTER, fileSize AS POINTER) AS POINTER
DECLARE FUNCTION ExportImageAsCode LIB "raylib" ALIAS "ExportImageAsCode" (image AS Image, fileName AS POINTER) AS BYTE
DECLARE FUNCTION GenImageColor LIB "raylib" ALIAS "GenImageColor" (width AS INTEGER, height AS INTEGER, color AS Color) AS Image
DECLARE FUNCTION GenImageGradientLinear LIB "raylib" ALIAS "GenImageGradientLinear" (width AS INTEGER, height AS INTEGER, direction AS INTEGER, start AS Color, end_ AS Color) AS Image
DECLARE FUNCTION GenImageGradientRadial LIB "raylib" ALIAS "GenImageGradientRadial" (width AS INTEGER, height AS INTEGER, density AS SINGLE, inner AS Color, outer AS Color) AS Image
DECLARE FUNCTION GenImageGradientSquare LIB "raylib" ALIAS "GenImageGradientSquare" (width AS INTEGER, height AS INTEGER, density AS SINGLE, inner AS Color, outer AS Color) AS Image
DECLARE FUNCTION GenImageChecked LIB "raylib" ALIAS "GenImageChecked" (width AS INTEGER, height AS INTEGER, checksX AS INTEGER, checksY AS INTEGER, col1 AS Color, col2 AS Color) AS Image
DECLARE FUNCTION GenImageWhiteNoise LIB "raylib" ALIAS "GenImageWhiteNoise" (width AS INTEGER, height AS INTEGER, factor AS SINGLE) AS Image
DECLARE FUNCTION GenImagePerlinNoise LIB "raylib" ALIAS "GenImagePerlinNoise" (width AS INTEGER, height AS INTEGER, offsetX AS INTEGER, offsetY AS INTEGER, scale AS SINGLE) AS Image
DECLARE FUNCTION GenImageCellular LIB "raylib" ALIAS "GenImageCellular" (width AS INTEGER, height AS INTEGER, tileSize AS INTEGER) AS Image
DECLARE FUNCTION GenImageText LIB "raylib" ALIAS "GenImageText" (width AS INTEGER, height AS INTEGER, text AS POINTER) AS Image
DECLARE FUNCTION ImageCopy LIB "raylib" ALIAS "ImageCopy" (image AS Image) AS Image
DECLARE FUNCTION ImageFromImage LIB "raylib" ALIAS "ImageFromImage" (image AS Image, rec AS Rectangle) AS Image
DECLARE FUNCTION ImageFromChannel LIB "raylib" ALIAS "ImageFromChannel" (image AS Image, selectedChannel AS INTEGER) AS Image
DECLARE FUNCTION ImageText LIB "raylib" ALIAS "ImageText" (text AS POINTER, fontSize AS INTEGER, color AS Color) AS Image
DECLARE FUNCTION ImageTextEx LIB "raylib" ALIAS "ImageTextEx" (font AS Font, text AS POINTER, fontSize AS SINGLE, spacing AS SINGLE, tint AS Color) AS Image
DECLARE SUB      ImageFormat LIB "raylib" ALIAS "ImageFormat" (image AS PImage, newFormat AS INTEGER)
DECLARE SUB      ImageToPOT LIB "raylib" ALIAS "ImageToPOT" (image AS PImage, fill AS Color)
DECLARE SUB      ImageCrop LIB "raylib" ALIAS "ImageCrop" (image AS PImage, crop AS Rectangle)
DECLARE SUB      ImageAlphaCrop LIB "raylib" ALIAS "ImageAlphaCrop" (image AS PImage, threshold AS SINGLE)
DECLARE SUB      ImageAlphaClear LIB "raylib" ALIAS "ImageAlphaClear" (image AS PImage, color AS Color, threshold AS SINGLE)
DECLARE SUB      ImageAlphaMask LIB "raylib" ALIAS "ImageAlphaMask" (image AS PImage, alphaMask AS Image)
DECLARE SUB      ImageAlphaPremultiply LIB "raylib" ALIAS "ImageAlphaPremultiply" (image AS PImage)
DECLARE SUB      ImageBlurGaussian LIB "raylib" ALIAS "ImageBlurGaussian" (image AS PImage, blurSize AS INTEGER)
DECLARE SUB      ImageKernelConvolution LIB "raylib" ALIAS "ImageKernelConvolution" (image AS PImage, kernel AS POINTER, kernelSize AS INTEGER)
DECLARE SUB      ImageResize LIB "raylib" ALIAS "ImageResize" (image AS PImage, newWidth AS INTEGER, newHeight AS INTEGER)
DECLARE SUB      ImageResizeNN LIB "raylib" ALIAS "ImageResizeNN" (image AS PImage, newWidth AS INTEGER, newHeight AS INTEGER)
DECLARE SUB      ImageResizeCanvas LIB "raylib" ALIAS "ImageResizeCanvas" (image AS PImage, newWidth AS INTEGER, newHeight AS INTEGER, offsetX AS INTEGER, offsetY AS INTEGER, fill AS Color)
DECLARE SUB      ImageMipmaps LIB "raylib" ALIAS "ImageMipmaps" (image AS PImage)
DECLARE SUB      ImageDither LIB "raylib" ALIAS "ImageDither" (image AS PImage, rBpp AS INTEGER, gBpp AS INTEGER, bBpp AS INTEGER, aBpp AS INTEGER)
DECLARE SUB      ImageFlipVertical LIB "raylib" ALIAS "ImageFlipVertical" (image AS PImage)
DECLARE SUB      ImageFlipHorizontal LIB "raylib" ALIAS "ImageFlipHorizontal" (image AS PImage)
DECLARE SUB      ImageRotate LIB "raylib" ALIAS "ImageRotate" (image AS PImage, degrees AS INTEGER)
DECLARE SUB      ImageRotateCW LIB "raylib" ALIAS "ImageRotateCW" (image AS PImage)
DECLARE SUB      ImageRotateCCW LIB "raylib" ALIAS "ImageRotateCCW" (image AS PImage)
DECLARE SUB      ImageColorTint LIB "raylib" ALIAS "ImageColorTint" (image AS PImage, color AS Color)
DECLARE SUB      ImageColorInvert LIB "raylib" ALIAS "ImageColorInvert" (image AS PImage)
DECLARE SUB      ImageColorGrayscale LIB "raylib" ALIAS "ImageColorGrayscale" (image AS PImage)
DECLARE SUB      ImageColorContrast LIB "raylib" ALIAS "ImageColorContrast" (image AS PImage, contrast AS SINGLE)
DECLARE SUB      ImageColorBrightness LIB "raylib" ALIAS "ImageColorBrightness" (image AS PImage, brightness AS INTEGER)
DECLARE SUB      ImageColorReplace LIB "raylib" ALIAS "ImageColorReplace" (image AS PImage, color AS Color, replace AS Color)
DECLARE FUNCTION LoadImageColors LIB "raylib" ALIAS "LoadImageColors" (image AS Image) AS PColor
DECLARE FUNCTION LoadImagePalette LIB "raylib" ALIAS "LoadImagePalette" (image AS Image, maxPaletteSize AS INTEGER, colorCount AS POINTER) AS PColor
DECLARE SUB      UnloadImageColors LIB "raylib" ALIAS "UnloadImageColors" (colors AS PColor)
DECLARE SUB      UnloadImagePalette LIB "raylib" ALIAS "UnloadImagePalette" (colors AS PColor)
DECLARE FUNCTION GetImageAlphaBorder LIB "raylib" ALIAS "GetImageAlphaBorder" (image AS Image, threshold AS SINGLE) AS Rectangle
DECLARE FUNCTION GetImageColor LIB "raylib" ALIAS "GetImageColor" (image AS Image, x AS INTEGER, y AS INTEGER) AS Color
DECLARE SUB      ImageClearBackground LIB "raylib" ALIAS "ImageClearBackground" (dst AS PImage, color AS Color)
DECLARE SUB      ImageDrawPixel LIB "raylib" ALIAS "ImageDrawPixel" (dst AS PImage, posX AS INTEGER, posY AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawPixelV LIB "raylib" ALIAS "ImageDrawPixelV" (dst AS PImage, position AS Vector2, color AS Color)
DECLARE SUB      ImageDrawLine LIB "raylib" ALIAS "ImageDrawLine" (dst AS PImage, startPosX AS INTEGER, startPosY AS INTEGER, endPosX AS INTEGER, endPosY AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawLineV LIB "raylib" ALIAS "ImageDrawLineV" (dst AS PImage, start AS Vector2, end_ AS Vector2, color AS Color)
DECLARE SUB      ImageDrawLineEx LIB "raylib" ALIAS "ImageDrawLineEx" (dst AS PImage, start AS Vector2, end_ AS Vector2, thick AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawCircle LIB "raylib" ALIAS "ImageDrawCircle" (dst AS PImage, centerX AS INTEGER, centerY AS INTEGER, radius AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawCircleV LIB "raylib" ALIAS "ImageDrawCircleV" (dst AS PImage, center AS Vector2, radius AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawCircleLines LIB "raylib" ALIAS "ImageDrawCircleLines" (dst AS PImage, centerX AS INTEGER, centerY AS INTEGER, radius AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawCircleLinesV LIB "raylib" ALIAS "ImageDrawCircleLinesV" (dst AS PImage, center AS Vector2, radius AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawRectangle LIB "raylib" ALIAS "ImageDrawRectangle" (dst AS PImage, posX AS INTEGER, posY AS INTEGER, width AS INTEGER, height AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawRectangleV LIB "raylib" ALIAS "ImageDrawRectangleV" (dst AS PImage, position AS Vector2, size AS Vector2, color AS Color)
DECLARE SUB      ImageDrawRectangleRec LIB "raylib" ALIAS "ImageDrawRectangleRec" (dst AS PImage, rec AS Rectangle, color AS Color)
DECLARE SUB      ImageDrawRectangleLines LIB "raylib" ALIAS "ImageDrawRectangleLines" (dst AS PImage, rec AS Rectangle, thick AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawTriangle LIB "raylib" ALIAS "ImageDrawTriangle" (dst AS PImage, v1 AS Vector2, v2 AS Vector2, v3 AS Vector2, color AS Color)
DECLARE SUB      ImageDrawTriangleEx LIB "raylib" ALIAS "ImageDrawTriangleEx" (dst AS PImage, v1 AS Vector2, v2 AS Vector2, v3 AS Vector2, c1 AS Color, c2 AS Color, c3 AS Color)
DECLARE SUB      ImageDrawTriangleLines LIB "raylib" ALIAS "ImageDrawTriangleLines" (dst AS PImage, v1 AS Vector2, v2 AS Vector2, v3 AS Vector2, color AS Color)
DECLARE SUB      ImageDrawTriangleFan LIB "raylib" ALIAS "ImageDrawTriangleFan" (dst AS PImage, points AS PVector2, pointCount AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawTriangleStrip LIB "raylib" ALIAS "ImageDrawTriangleStrip" (dst AS PImage, points AS PVector2, pointCount AS INTEGER, color AS Color)
DECLARE SUB      ImageDraw LIB "raylib" ALIAS "ImageDraw" (dst AS PImage, src AS Image, srcRec AS Rectangle, dstRec AS Rectangle, tint AS Color)
DECLARE SUB      ImageDrawText LIB "raylib" ALIAS "ImageDrawText" (dst AS PImage, text AS POINTER, posX AS INTEGER, posY AS INTEGER, fontSize AS INTEGER, color AS Color)
DECLARE SUB      ImageDrawTextEx LIB "raylib" ALIAS "ImageDrawTextEx" (dst AS PImage, font AS Font, text AS POINTER, position AS Vector2, fontSize AS SINGLE, spacing AS SINGLE, tint AS Color)
DECLARE FUNCTION LoadTexture LIB "raylib" ALIAS "LoadTexture" (fileName AS POINTER) AS POINTER
DECLARE FUNCTION LoadTextureFromImage LIB "raylib" ALIAS "LoadTextureFromImage" (image AS Image) AS POINTER
DECLARE FUNCTION LoadTextureCubemap LIB "raylib" ALIAS "LoadTextureCubemap" (image AS Image, layout AS INTEGER) AS POINTER
DECLARE FUNCTION LoadRenderTexture LIB "raylib" ALIAS "LoadRenderTexture" (width AS INTEGER, height AS INTEGER) AS POINTER
DECLARE FUNCTION IsTextureValid LIB "raylib" ALIAS "IsTextureValid" (texture AS POINTER) AS BYTE
DECLARE SUB      UnloadTexture LIB "raylib" ALIAS "UnloadTexture" (texture AS POINTER)
DECLARE FUNCTION IsRenderTextureValid LIB "raylib" ALIAS "IsRenderTextureValid" (target AS POINTER) AS BYTE
DECLARE SUB      UnloadRenderTexture LIB "raylib" ALIAS "UnloadRenderTexture" (target AS POINTER)
DECLARE SUB      UpdateTexture LIB "raylib" ALIAS "UpdateTexture" (texture AS POINTER, pixels AS POINTER)
DECLARE SUB      UpdateTextureRec LIB "raylib" ALIAS "UpdateTextureRec" (texture AS POINTER, rec AS Rectangle, pixels AS POINTER)
DECLARE SUB      GenTextureMipmaps LIB "raylib" ALIAS "GenTextureMipmaps" (texture AS POINTER)
DECLARE SUB      SetTextureFilter LIB "raylib" ALIAS "SetTextureFilter" (texture AS POINTER, filter AS INTEGER)
DECLARE SUB      SetTextureWrap LIB "raylib" ALIAS "SetTextureWrap" (texture AS POINTER, wrap AS INTEGER)
DECLARE SUB      DrawTexture LIB "raylib" ALIAS "DrawTexture" (texture AS POINTER, posX AS INTEGER, posY AS INTEGER, tint AS Color)
DECLARE SUB      DrawTextureV LIB "raylib" ALIAS "DrawTextureV" (texture AS POINTER, position AS Vector2, tint AS Color)
DECLARE SUB      DrawTextureEx LIB "raylib" ALIAS "DrawTextureEx" (texture AS POINTER, position AS Vector2, rotation AS SINGLE, scale AS SINGLE, tint AS Color)
DECLARE SUB      DrawTextureRec LIB "raylib" ALIAS "DrawTextureRec" (texture AS POINTER, source AS Rectangle, position AS Vector2, tint AS Color)
DECLARE SUB      DrawTexturePro LIB "raylib" ALIAS "DrawTexturePro" (texture AS POINTER, source AS Rectangle, dest AS Rectangle, origin AS Vector2, rotation AS SINGLE, tint AS Color)
DECLARE SUB      DrawTextureNPatch LIB "raylib" ALIAS "DrawTextureNPatch" (texture AS POINTER, nPatchInfo AS NPatchInfo, dest AS Rectangle, origin AS Vector2, rotation AS SINGLE, tint AS Color)
DECLARE FUNCTION ColorIsEqual LIB "raylib" ALIAS "ColorIsEqual" (col1 AS Color, col2 AS Color) AS BYTE
DECLARE FUNCTION Fade LIB "raylib" ALIAS "Fade" (color AS Color, alpha AS SINGLE) AS Color
DECLARE FUNCTION ColorToInt LIB "raylib" ALIAS "ColorToInt" (color AS Color) AS INTEGER
DECLARE FUNCTION ColorNormalize LIB "raylib" ALIAS "ColorNormalize" (color AS Color) AS Vector4
DECLARE FUNCTION ColorFromNormalized LIB "raylib" ALIAS "ColorFromNormalized" (normalized AS Vector4) AS Color
DECLARE FUNCTION ColorToHSV LIB "raylib" ALIAS "ColorToHSV" (color AS Color) AS Vector3
DECLARE FUNCTION ColorFromHSV LIB "raylib" ALIAS "ColorFromHSV" (hue AS SINGLE, saturation AS SINGLE, value AS SINGLE) AS Color
DECLARE FUNCTION ColorTint LIB "raylib" ALIAS "ColorTint" (color AS Color, tint AS Color) AS Color
DECLARE FUNCTION ColorBrightness LIB "raylib" ALIAS "ColorBrightness" (color AS Color, factor AS SINGLE) AS Color
DECLARE FUNCTION ColorContrast LIB "raylib" ALIAS "ColorContrast" (color AS Color, contrast AS SINGLE) AS Color
DECLARE FUNCTION ColorAlpha LIB "raylib" ALIAS "ColorAlpha" (color AS Color, alpha AS SINGLE) AS Color
DECLARE FUNCTION ColorAlphaBlend LIB "raylib" ALIAS "ColorAlphaBlend" (dst AS Color, src AS Color, tint AS Color) AS Color
DECLARE FUNCTION ColorLerp LIB "raylib" ALIAS "ColorLerp" (color1 AS Color, color2 AS Color, factor AS SINGLE) AS Color
DECLARE FUNCTION GetColor LIB "raylib" ALIAS "GetColor" (hexValue AS DWORD) AS Color
DECLARE FUNCTION GetPixelColor LIB "raylib" ALIAS "GetPixelColor" (srcPtr AS POINTER, format AS INTEGER) AS Color
DECLARE SUB      SetPixelColor LIB "raylib" ALIAS "SetPixelColor" (dstPtr AS POINTER, color AS Color, format AS INTEGER)
DECLARE FUNCTION GetPixelDataSize LIB "raylib" ALIAS "GetPixelDataSize" (width AS INTEGER, height AS INTEGER, format AS INTEGER) AS INTEGER
DECLARE FUNCTION GetFontDefault LIB "raylib" ALIAS "GetFontDefault" () AS Font
DECLARE FUNCTION LoadFont LIB "raylib" ALIAS "LoadFont" (fileName AS POINTER) AS Font
DECLARE FUNCTION LoadFontEx LIB "raylib" ALIAS "LoadFontEx" (fileName AS POINTER, fontSize AS INTEGER, codepoints AS POINTER, codepointCount AS INTEGER) AS Font
DECLARE FUNCTION LoadFontFromImage LIB "raylib" ALIAS "LoadFontFromImage" (image AS Image, key AS Color, firstChar AS INTEGER) AS Font
DECLARE FUNCTION LoadFontFromMemory LIB "raylib" ALIAS "LoadFontFromMemory" (fileType AS POINTER, fileData AS POINTER, dataSize AS INTEGER, fontSize AS INTEGER, codepoints AS POINTER, codepointCount AS INTEGER) AS Font
DECLARE FUNCTION IsFontValid LIB "raylib" ALIAS "IsFontValid" (font AS Font) AS BYTE
DECLARE FUNCTION LoadFontData LIB "raylib" ALIAS "LoadFontData" (fileData AS POINTER, dataSize AS INTEGER, fontSize AS INTEGER, codepoints AS POINTER, codepointCount AS INTEGER, type_ AS INTEGER) AS PGlyphInfo
DECLARE FUNCTION GenImageFontAtlas LIB "raylib" ALIAS "GenImageFontAtlas" (glyphs AS PGlyphInfo, glyphRecs AS POINTER, glyphCount AS INTEGER, fontSize AS INTEGER, padding AS INTEGER, packMethod AS INTEGER) AS Image
DECLARE SUB      UnloadFontData LIB "raylib" ALIAS "UnloadFontData" (glyphs AS PGlyphInfo, glyphCount AS INTEGER)
DECLARE SUB      UnloadFont LIB "raylib" ALIAS "UnloadFont" (font AS Font)
DECLARE FUNCTION ExportFontAsCode LIB "raylib" ALIAS "ExportFontAsCode" (font AS Font, fileName AS POINTER) AS BYTE
DECLARE SUB      DrawFPS LIB "raylib" ALIAS "DrawFPS" (posX AS INTEGER, posY AS INTEGER)
DECLARE SUB      DrawText LIB "raylib" ALIAS "DrawText" (text AS POINTER, posX AS INTEGER, posY AS INTEGER, fontSize AS INTEGER, color AS Color)
DECLARE SUB      DrawTextEx LIB "raylib" ALIAS "DrawTextEx" (font AS Font, text AS POINTER, position AS Vector2, fontSize AS SINGLE, spacing AS SINGLE, tint AS Color)
DECLARE SUB      DrawTextPro LIB "raylib" ALIAS "DrawTextPro" (font AS Font, text AS POINTER, position AS Vector2, origin AS Vector2, rotation AS SINGLE, fontSize AS SINGLE, spacing AS SINGLE, tint AS Color)
DECLARE SUB      DrawTextCodepoint LIB "raylib" ALIAS "DrawTextCodepoint" (font AS Font, codepoint AS INTEGER, position AS Vector2, fontSize AS SINGLE, tint AS Color)
DECLARE SUB      DrawTextCodepoints LIB "raylib" ALIAS "DrawTextCodepoints" (font AS Font, codepoints AS POINTER, codepointCount AS INTEGER, position AS Vector2, fontSize AS SINGLE, spacing AS SINGLE, tint AS Color)
DECLARE SUB      SetTextLineSpacing LIB "raylib" ALIAS "SetTextLineSpacing" (spacing AS INTEGER)
DECLARE FUNCTION MeasureText LIB "raylib" ALIAS "MeasureText" (text AS POINTER, fontSize AS INTEGER) AS INTEGER
DECLARE FUNCTION MeasureTextEx LIB "raylib" ALIAS "MeasureTextEx" (font AS Font, text AS POINTER, fontSize AS SINGLE, spacing AS SINGLE) AS Vector2
DECLARE FUNCTION GetGlyphIndex LIB "raylib" ALIAS "GetGlyphIndex" (font AS Font, codepoint AS INTEGER) AS INTEGER
DECLARE FUNCTION GetGlyphInfo LIB "raylib" ALIAS "GetGlyphInfo" (font AS Font, codepoint AS INTEGER) AS GlyphInfo
DECLARE FUNCTION GetGlyphAtlasRec LIB "raylib" ALIAS "GetGlyphAtlasRec" (font AS Font, codepoint AS INTEGER) AS Rectangle
DECLARE FUNCTION LoadUTF8 LIB "raylib" ALIAS "LoadUTF8" (codepoints AS POINTER, length AS INTEGER) AS POINTER
DECLARE SUB      UnloadUTF8 LIB "raylib" ALIAS "UnloadUTF8" (text AS POINTER)
DECLARE FUNCTION LoadCodepoints LIB "raylib" ALIAS "LoadCodepoints" (text AS POINTER, count AS POINTER) AS POINTER
DECLARE SUB      UnloadCodepoints LIB "raylib" ALIAS "UnloadCodepoints" (codepoints AS POINTER)
DECLARE FUNCTION GetCodepointCount LIB "raylib" ALIAS "GetCodepointCount" (text AS POINTER) AS INTEGER
DECLARE FUNCTION GetCodepoint LIB "raylib" ALIAS "GetCodepoint" (text AS POINTER, codepointSize AS POINTER) AS INTEGER
DECLARE FUNCTION GetCodepointNext LIB "raylib" ALIAS "GetCodepointNext" (text AS POINTER, codepointSize AS POINTER) AS INTEGER
DECLARE FUNCTION GetCodepointPrevious LIB "raylib" ALIAS "GetCodepointPrevious" (text AS POINTER, codepointSize AS POINTER) AS INTEGER
DECLARE FUNCTION CodepointToUTF8 LIB "raylib" ALIAS "CodepointToUTF8" (codepoint AS INTEGER, utf8Size AS POINTER) AS POINTER
DECLARE FUNCTION TextCopy LIB "raylib" ALIAS "TextCopy" (dst AS POINTER, src AS POINTER) AS INTEGER
DECLARE FUNCTION TextIsEqual LIB "raylib" ALIAS "TextIsEqual" (text1 AS POINTER, text2 AS POINTER) AS BYTE
DECLARE FUNCTION TextLength LIB "raylib" ALIAS "TextLength" (text AS POINTER) AS DWORD
DECLARE FUNCTION TextFormat LIB "raylib" ALIAS "TextFormat" (text AS POINTER) AS POINTER  ' varargs — call via wrapper
DECLARE FUNCTION TextSubtext LIB "raylib" ALIAS "TextSubtext" (text AS POINTER, position AS INTEGER, length AS INTEGER) AS POINTER
DECLARE FUNCTION TextReplace LIB "raylib" ALIAS "TextReplace" (text AS POINTER, replace AS POINTER, by AS POINTER) AS POINTER
DECLARE FUNCTION TextInsert LIB "raylib" ALIAS "TextInsert" (text AS POINTER, insert AS POINTER, position AS INTEGER) AS POINTER
DECLARE FUNCTION TextJoin LIB "raylib" ALIAS "TextJoin" (textList AS POINTER, count AS INTEGER, delimiter AS POINTER) AS POINTER
DECLARE FUNCTION TextSplit LIB "raylib" ALIAS "TextSplit" (text AS POINTER, delimiter AS BYTE, count AS POINTER) AS POINTER
DECLARE SUB      TextAppend LIB "raylib" ALIAS "TextAppend" (text AS POINTER, append AS POINTER, position AS POINTER)
DECLARE FUNCTION TextFindIndex LIB "raylib" ALIAS "TextFindIndex" (text AS POINTER, find AS POINTER) AS INTEGER
DECLARE FUNCTION TextToUpper LIB "raylib" ALIAS "TextToUpper" (text AS POINTER) AS POINTER
DECLARE FUNCTION TextToLower LIB "raylib" ALIAS "TextToLower" (text AS POINTER) AS POINTER
DECLARE FUNCTION TextToPascal LIB "raylib" ALIAS "TextToPascal" (text AS POINTER) AS POINTER
DECLARE FUNCTION TextToSnake LIB "raylib" ALIAS "TextToSnake" (text AS POINTER) AS POINTER
DECLARE FUNCTION TextToCamel LIB "raylib" ALIAS "TextToCamel" (text AS POINTER) AS POINTER
DECLARE FUNCTION TextToInteger LIB "raylib" ALIAS "TextToInteger" (text AS POINTER) AS INTEGER
DECLARE FUNCTION TextToFloat LIB "raylib" ALIAS "TextToFloat" (text AS POINTER) AS SINGLE
DECLARE SUB      DrawLine3D LIB "raylib" ALIAS "DrawLine3D" (startPos AS Vector3, endPos AS Vector3, color AS Color)
DECLARE SUB      DrawPoint3D LIB "raylib" ALIAS "DrawPoint3D" (position AS Vector3, color AS Color)
DECLARE SUB      DrawCircle3D LIB "raylib" ALIAS "DrawCircle3D" (center AS Vector3, radius AS SINGLE, rotationAxis AS Vector3, rotationAngle AS SINGLE, color AS Color)
DECLARE SUB      DrawTriangle3D LIB "raylib" ALIAS "DrawTriangle3D" (v1 AS Vector3, v2 AS Vector3, v3 AS Vector3, color AS Color)
DECLARE SUB      DrawTriangleStrip3D LIB "raylib" ALIAS "DrawTriangleStrip3D" (points AS PVector3, pointCount AS INTEGER, color AS Color)
DECLARE SUB      DrawCube LIB "raylib" ALIAS "DrawCube" (position AS Vector3, width AS SINGLE, height AS SINGLE, length AS SINGLE, color AS Color)
DECLARE SUB      DrawCubeV LIB "raylib" ALIAS "DrawCubeV" (position AS Vector3, size AS Vector3, color AS Color)
DECLARE SUB      DrawCubeWires LIB "raylib" ALIAS "DrawCubeWires" (position AS Vector3, width AS SINGLE, height AS SINGLE, length AS SINGLE, color AS Color)
DECLARE SUB      DrawCubeWiresV LIB "raylib" ALIAS "DrawCubeWiresV" (position AS Vector3, size AS Vector3, color AS Color)
DECLARE SUB      DrawSphere LIB "raylib" ALIAS "DrawSphere" (centerPos AS Vector3, radius AS SINGLE, color AS Color)
DECLARE SUB      DrawSphereEx LIB "raylib" ALIAS "DrawSphereEx" (centerPos AS Vector3, radius AS SINGLE, rings AS INTEGER, slices AS INTEGER, color AS Color)
DECLARE SUB      DrawSphereWires LIB "raylib" ALIAS "DrawSphereWires" (centerPos AS Vector3, radius AS SINGLE, rings AS INTEGER, slices AS INTEGER, color AS Color)
DECLARE SUB      DrawCylinder LIB "raylib" ALIAS "DrawCylinder" (position AS Vector3, radiusTop AS SINGLE, radiusBottom AS SINGLE, height AS SINGLE, slices AS INTEGER, color AS Color)
DECLARE SUB      DrawCylinderEx LIB "raylib" ALIAS "DrawCylinderEx" (startPos AS Vector3, endPos AS Vector3, startRadius AS SINGLE, endRadius AS SINGLE, sides AS INTEGER, color AS Color)
DECLARE SUB      DrawCylinderWires LIB "raylib" ALIAS "DrawCylinderWires" (position AS Vector3, radiusTop AS SINGLE, radiusBottom AS SINGLE, height AS SINGLE, slices AS INTEGER, color AS Color)
DECLARE SUB      DrawCylinderWiresEx LIB "raylib" ALIAS "DrawCylinderWiresEx" (startPos AS Vector3, endPos AS Vector3, startRadius AS SINGLE, endRadius AS SINGLE, sides AS INTEGER, color AS Color)
DECLARE SUB      DrawCapsule LIB "raylib" ALIAS "DrawCapsule" (startPos AS Vector3, endPos AS Vector3, radius AS SINGLE, slices AS INTEGER, rings AS INTEGER, color AS Color)
DECLARE SUB      DrawCapsuleWires LIB "raylib" ALIAS "DrawCapsuleWires" (startPos AS Vector3, endPos AS Vector3, radius AS SINGLE, slices AS INTEGER, rings AS INTEGER, color AS Color)
DECLARE SUB      DrawPlane LIB "raylib" ALIAS "DrawPlane" (centerPos AS Vector3, size AS Vector2, color AS Color)
DECLARE SUB      DrawRay LIB "raylib" ALIAS "DrawRay" (ray AS Ray, color AS Color)
DECLARE SUB      DrawGrid LIB "raylib" ALIAS "DrawGrid" (slices AS INTEGER, spacing AS SINGLE)
DECLARE FUNCTION LoadModel LIB "raylib" ALIAS "LoadModel" (fileName AS POINTER) AS Model
DECLARE FUNCTION LoadModelFromMesh LIB "raylib" ALIAS "LoadModelFromMesh" (mesh AS Mesh) AS Model
DECLARE FUNCTION IsModelValid LIB "raylib" ALIAS "IsModelValid" (model AS Model) AS BYTE
DECLARE SUB      UnloadModel LIB "raylib" ALIAS "UnloadModel" (model AS Model)
DECLARE FUNCTION GetModelBoundingBox LIB "raylib" ALIAS "GetModelBoundingBox" (model AS Model) AS BoundingBox
DECLARE SUB      DrawModel LIB "raylib" ALIAS "DrawModel" (model AS Model, position AS Vector3, scale AS SINGLE, tint AS Color)
DECLARE SUB      DrawModelEx LIB "raylib" ALIAS "DrawModelEx" (model AS Model, position AS Vector3, rotationAxis AS Vector3, rotationAngle AS SINGLE, scale AS Vector3, tint AS Color)
DECLARE SUB      DrawModelWires LIB "raylib" ALIAS "DrawModelWires" (model AS Model, position AS Vector3, scale AS SINGLE, tint AS Color)
DECLARE SUB      DrawModelWiresEx LIB "raylib" ALIAS "DrawModelWiresEx" (model AS Model, position AS Vector3, rotationAxis AS Vector3, rotationAngle AS SINGLE, scale AS Vector3, tint AS Color)
DECLARE SUB      DrawModelPoints LIB "raylib" ALIAS "DrawModelPoints" (model AS Model, position AS Vector3, scale AS SINGLE, tint AS Color)
DECLARE SUB      DrawModelPointsEx LIB "raylib" ALIAS "DrawModelPointsEx" (model AS Model, position AS Vector3, rotationAxis AS Vector3, rotationAngle AS SINGLE, scale AS Vector3, tint AS Color)
DECLARE SUB      DrawBoundingBox LIB "raylib" ALIAS "DrawBoundingBox" (box AS BoundingBox, color AS Color)
DECLARE SUB      DrawBillboard LIB "raylib" ALIAS "DrawBillboard" (camera AS POINTER, texture AS POINTER, position AS Vector3, scale AS SINGLE, tint AS Color)
DECLARE SUB      DrawBillboardRec LIB "raylib" ALIAS "DrawBillboardRec" (camera AS POINTER, texture AS POINTER, source AS Rectangle, position AS Vector3, size AS Vector2, tint AS Color)
DECLARE SUB      DrawBillboardPro LIB "raylib" ALIAS "DrawBillboardPro" (camera AS POINTER, texture AS POINTER, source AS Rectangle, position AS Vector3, up AS Vector3, size AS Vector2, origin AS Vector2, rotation AS SINGLE, tint AS Color)
DECLARE SUB      UploadMesh LIB "raylib" ALIAS "UploadMesh" (mesh AS PMesh, dynamic AS BYTE)
DECLARE SUB      UpdateMeshBuffer LIB "raylib" ALIAS "UpdateMeshBuffer" (mesh AS Mesh, index AS INTEGER, data AS POINTER, dataSize AS INTEGER, offset AS INTEGER)
DECLARE SUB      UnloadMesh LIB "raylib" ALIAS "UnloadMesh" (mesh AS Mesh)
DECLARE SUB      DrawMesh LIB "raylib" ALIAS "DrawMesh" (mesh AS Mesh, material AS Material, transform AS Matrix)
DECLARE SUB      DrawMeshInstanced LIB "raylib" ALIAS "DrawMeshInstanced" (mesh AS Mesh, material AS Material, transforms AS PMatrix, instances AS INTEGER)
DECLARE FUNCTION GetMeshBoundingBox LIB "raylib" ALIAS "GetMeshBoundingBox" (mesh AS Mesh) AS BoundingBox
DECLARE SUB      GenMeshTangents LIB "raylib" ALIAS "GenMeshTangents" (mesh AS PMesh)
DECLARE FUNCTION ExportMesh LIB "raylib" ALIAS "ExportMesh" (mesh AS Mesh, fileName AS POINTER) AS BYTE
DECLARE FUNCTION ExportMeshAsCode LIB "raylib" ALIAS "ExportMeshAsCode" (mesh AS Mesh, fileName AS POINTER) AS BYTE
DECLARE FUNCTION GenMeshPoly LIB "raylib" ALIAS "GenMeshPoly" (sides AS INTEGER, radius AS SINGLE) AS Mesh
DECLARE FUNCTION GenMeshPlane LIB "raylib" ALIAS "GenMeshPlane" (width AS SINGLE, length AS SINGLE, resX AS INTEGER, resZ AS INTEGER) AS Mesh
DECLARE FUNCTION GenMeshCube LIB "raylib" ALIAS "GenMeshCube" (width AS SINGLE, height AS SINGLE, length AS SINGLE) AS Mesh
DECLARE FUNCTION GenMeshSphere LIB "raylib" ALIAS "GenMeshSphere" (radius AS SINGLE, rings AS INTEGER, slices AS INTEGER) AS Mesh
DECLARE FUNCTION GenMeshHemiSphere LIB "raylib" ALIAS "GenMeshHemiSphere" (radius AS SINGLE, rings AS INTEGER, slices AS INTEGER) AS Mesh
DECLARE FUNCTION GenMeshCylinder LIB "raylib" ALIAS "GenMeshCylinder" (radius AS SINGLE, height AS SINGLE, slices AS INTEGER) AS Mesh
DECLARE FUNCTION GenMeshCone LIB "raylib" ALIAS "GenMeshCone" (radius AS SINGLE, height AS SINGLE, slices AS INTEGER) AS Mesh
DECLARE FUNCTION GenMeshTorus LIB "raylib" ALIAS "GenMeshTorus" (radius AS SINGLE, size AS SINGLE, radSeg AS INTEGER, sides AS INTEGER) AS Mesh
DECLARE FUNCTION GenMeshKnot LIB "raylib" ALIAS "GenMeshKnot" (radius AS SINGLE, size AS SINGLE, radSeg AS INTEGER, sides AS INTEGER) AS Mesh
DECLARE FUNCTION GenMeshHeightmap LIB "raylib" ALIAS "GenMeshHeightmap" (heightmap AS Image, size AS Vector3) AS Mesh
DECLARE FUNCTION GenMeshCubicmap LIB "raylib" ALIAS "GenMeshCubicmap" (cubicmap AS Image, cubeSize AS Vector3) AS Mesh
DECLARE FUNCTION LoadMaterials LIB "raylib" ALIAS "LoadMaterials" (fileName AS POINTER, materialCount AS POINTER) AS PMaterial
DECLARE FUNCTION LoadMaterialDefault LIB "raylib" ALIAS "LoadMaterialDefault" () AS Material
DECLARE FUNCTION IsMaterialValid LIB "raylib" ALIAS "IsMaterialValid" (material AS Material) AS BYTE
DECLARE SUB      UnloadMaterial LIB "raylib" ALIAS "UnloadMaterial" (material AS Material)
DECLARE SUB      SetMaterialTexture LIB "raylib" ALIAS "SetMaterialTexture" (material AS PMaterial, mapType AS INTEGER, texture AS POINTER)
DECLARE SUB      SetModelMeshMaterial LIB "raylib" ALIAS "SetModelMeshMaterial" (model AS PModel, meshId AS INTEGER, materialId AS INTEGER)
DECLARE FUNCTION LoadModelAnimations LIB "raylib" ALIAS "LoadModelAnimations" (fileName AS POINTER, animCount AS POINTER) AS PModelAnimation
DECLARE SUB      UpdateModelAnimation LIB "raylib" ALIAS "UpdateModelAnimation" (model AS Model, anim AS ModelAnimation, frame AS INTEGER)
DECLARE SUB      UpdateModelAnimationBones LIB "raylib" ALIAS "UpdateModelAnimationBones" (model AS Model, anim AS ModelAnimation, frame AS INTEGER)
DECLARE SUB      UnloadModelAnimation LIB "raylib" ALIAS "UnloadModelAnimation" (anim AS ModelAnimation)
DECLARE SUB      UnloadModelAnimations LIB "raylib" ALIAS "UnloadModelAnimations" (animations AS PModelAnimation, animCount AS INTEGER)
DECLARE FUNCTION IsModelAnimationValid LIB "raylib" ALIAS "IsModelAnimationValid" (model AS Model, anim AS ModelAnimation) AS BYTE
DECLARE FUNCTION CheckCollisionSpheres LIB "raylib" ALIAS "CheckCollisionSpheres" (center1 AS Vector3, radius1 AS SINGLE, center2 AS Vector3, radius2 AS SINGLE) AS BYTE
DECLARE FUNCTION CheckCollisionBoxes LIB "raylib" ALIAS "CheckCollisionBoxes" (box1 AS BoundingBox, box2 AS BoundingBox) AS BYTE
DECLARE FUNCTION CheckCollisionBoxSphere LIB "raylib" ALIAS "CheckCollisionBoxSphere" (box AS BoundingBox, center AS Vector3, radius AS SINGLE) AS BYTE
DECLARE FUNCTION GetRayCollisionSphere LIB "raylib" ALIAS "GetRayCollisionSphere" (ray AS Ray, center AS Vector3, radius AS SINGLE) AS RayCollision
DECLARE FUNCTION GetRayCollisionBox LIB "raylib" ALIAS "GetRayCollisionBox" (ray AS Ray, box AS BoundingBox) AS RayCollision
DECLARE FUNCTION GetRayCollisionMesh LIB "raylib" ALIAS "GetRayCollisionMesh" (ray AS Ray, mesh AS Mesh, transform AS Matrix) AS RayCollision
DECLARE FUNCTION GetRayCollisionTriangle LIB "raylib" ALIAS "GetRayCollisionTriangle" (ray AS Ray, p1 AS Vector3, p2 AS Vector3, p3 AS Vector3) AS RayCollision
DECLARE FUNCTION GetRayCollisionQuad LIB "raylib" ALIAS "GetRayCollisionQuad" (ray AS Ray, p1 AS Vector3, p2 AS Vector3, p3 AS Vector3, p4 AS Vector3) AS RayCollision
DECLARE SUB      InitAudioDevice LIB "raylib" ALIAS "InitAudioDevice" ()
DECLARE SUB      CloseAudioDevice LIB "raylib" ALIAS "CloseAudioDevice" ()
DECLARE FUNCTION IsAudioDeviceReady LIB "raylib" ALIAS "IsAudioDeviceReady" () AS BYTE
DECLARE SUB      SetMasterVolume LIB "raylib" ALIAS "SetMasterVolume" (volume AS SINGLE)
DECLARE FUNCTION GetMasterVolume LIB "raylib" ALIAS "GetMasterVolume" () AS SINGLE
DECLARE FUNCTION LoadWave LIB "raylib" ALIAS "LoadWave" (fileName AS POINTER) AS Wave
DECLARE FUNCTION LoadWaveFromMemory LIB "raylib" ALIAS "LoadWaveFromMemory" (fileType AS POINTER, fileData AS POINTER, dataSize AS INTEGER) AS Wave
DECLARE FUNCTION IsWaveValid LIB "raylib" ALIAS "IsWaveValid" (wave AS Wave) AS BYTE
DECLARE FUNCTION LoadSound LIB "raylib" ALIAS "LoadSound" (fileName AS POINTER) AS Sound
DECLARE FUNCTION LoadSoundFromWave LIB "raylib" ALIAS "LoadSoundFromWave" (wave AS Wave) AS Sound
DECLARE FUNCTION LoadSoundAlias LIB "raylib" ALIAS "LoadSoundAlias" (source AS Sound) AS Sound
DECLARE FUNCTION IsSoundValid LIB "raylib" ALIAS "IsSoundValid" (sound AS Sound) AS BYTE
DECLARE SUB      UpdateSound LIB "raylib" ALIAS "UpdateSound" (sound AS Sound, data AS POINTER, sampleCount AS INTEGER)
DECLARE SUB      UnloadWave LIB "raylib" ALIAS "UnloadWave" (wave AS Wave)
DECLARE SUB      UnloadSound LIB "raylib" ALIAS "UnloadSound" (sound AS Sound)
DECLARE SUB      UnloadSoundAlias LIB "raylib" ALIAS "UnloadSoundAlias" (alias_ AS Sound)
DECLARE FUNCTION ExportWave LIB "raylib" ALIAS "ExportWave" (wave AS Wave, fileName AS POINTER) AS BYTE
DECLARE FUNCTION ExportWaveAsCode LIB "raylib" ALIAS "ExportWaveAsCode" (wave AS Wave, fileName AS POINTER) AS BYTE
DECLARE SUB      PlaySound LIB "raylib" ALIAS "PlaySound" (sound AS Sound)
DECLARE SUB      StopSound LIB "raylib" ALIAS "StopSound" (sound AS Sound)
DECLARE SUB      PauseSound LIB "raylib" ALIAS "PauseSound" (sound AS Sound)
DECLARE SUB      ResumeSound LIB "raylib" ALIAS "ResumeSound" (sound AS Sound)
DECLARE FUNCTION IsSoundPlaying LIB "raylib" ALIAS "IsSoundPlaying" (sound AS Sound) AS BYTE
DECLARE SUB      SetSoundVolume LIB "raylib" ALIAS "SetSoundVolume" (sound AS Sound, volume AS SINGLE)
DECLARE SUB      SetSoundPitch LIB "raylib" ALIAS "SetSoundPitch" (sound AS Sound, pitch AS SINGLE)
DECLARE SUB      SetSoundPan LIB "raylib" ALIAS "SetSoundPan" (sound AS Sound, pan AS SINGLE)
DECLARE FUNCTION WaveCopy LIB "raylib" ALIAS "WaveCopy" (wave AS Wave) AS Wave
DECLARE SUB      WaveCrop LIB "raylib" ALIAS "WaveCrop" (wave AS PWave, initFrame AS INTEGER, finalFrame AS INTEGER)
DECLARE SUB      WaveFormat LIB "raylib" ALIAS "WaveFormat" (wave AS PWave, sampleRate AS INTEGER, sampleSize AS INTEGER, channels AS INTEGER)
DECLARE FUNCTION LoadWaveSamples LIB "raylib" ALIAS "LoadWaveSamples" (wave AS Wave) AS POINTER
DECLARE SUB      UnloadWaveSamples LIB "raylib" ALIAS "UnloadWaveSamples" (samples AS POINTER)
DECLARE FUNCTION LoadMusicStream LIB "raylib" ALIAS "LoadMusicStream" (fileName AS POINTER) AS Music
DECLARE FUNCTION LoadMusicStreamFromMemory LIB "raylib" ALIAS "LoadMusicStreamFromMemory" (fileType AS POINTER, data AS POINTER, dataSize AS INTEGER) AS Music
DECLARE FUNCTION IsMusicValid LIB "raylib" ALIAS "IsMusicValid" (music AS Music) AS BYTE
DECLARE SUB      UnloadMusicStream LIB "raylib" ALIAS "UnloadMusicStream" (music AS Music)
DECLARE SUB      PlayMusicStream LIB "raylib" ALIAS "PlayMusicStream" (music AS Music)
DECLARE FUNCTION IsMusicStreamPlaying LIB "raylib" ALIAS "IsMusicStreamPlaying" (music AS Music) AS BYTE
DECLARE SUB      UpdateMusicStream LIB "raylib" ALIAS "UpdateMusicStream" (music AS Music)
DECLARE SUB      StopMusicStream LIB "raylib" ALIAS "StopMusicStream" (music AS Music)
DECLARE SUB      PauseMusicStream LIB "raylib" ALIAS "PauseMusicStream" (music AS Music)
DECLARE SUB      ResumeMusicStream LIB "raylib" ALIAS "ResumeMusicStream" (music AS Music)
DECLARE SUB      SeekMusicStream LIB "raylib" ALIAS "SeekMusicStream" (music AS Music, position AS SINGLE)
DECLARE SUB      SetMusicVolume LIB "raylib" ALIAS "SetMusicVolume" (music AS Music, volume AS SINGLE)
DECLARE SUB      SetMusicPitch LIB "raylib" ALIAS "SetMusicPitch" (music AS Music, pitch AS SINGLE)
DECLARE SUB      SetMusicPan LIB "raylib" ALIAS "SetMusicPan" (music AS Music, pan AS SINGLE)
DECLARE FUNCTION GetMusicTimeLength LIB "raylib" ALIAS "GetMusicTimeLength" (music AS Music) AS SINGLE
DECLARE FUNCTION GetMusicTimePlayed LIB "raylib" ALIAS "GetMusicTimePlayed" (music AS Music) AS SINGLE
DECLARE FUNCTION LoadAudioStream LIB "raylib" ALIAS "LoadAudioStream" (sampleRate AS DWORD, sampleSize AS DWORD, channels AS DWORD) AS AudioStream
DECLARE FUNCTION IsAudioStreamValid LIB "raylib" ALIAS "IsAudioStreamValid" (stream AS AudioStream) AS BYTE
DECLARE SUB      UnloadAudioStream LIB "raylib" ALIAS "UnloadAudioStream" (stream AS AudioStream)
DECLARE SUB      UpdateAudioStream LIB "raylib" ALIAS "UpdateAudioStream" (stream AS AudioStream, data AS POINTER, frameCount AS INTEGER)
DECLARE FUNCTION IsAudioStreamProcessed LIB "raylib" ALIAS "IsAudioStreamProcessed" (stream AS AudioStream) AS BYTE
DECLARE SUB      PlayAudioStream LIB "raylib" ALIAS "PlayAudioStream" (stream AS AudioStream)
DECLARE SUB      PauseAudioStream LIB "raylib" ALIAS "PauseAudioStream" (stream AS AudioStream)
DECLARE SUB      ResumeAudioStream LIB "raylib" ALIAS "ResumeAudioStream" (stream AS AudioStream)
DECLARE FUNCTION IsAudioStreamPlaying LIB "raylib" ALIAS "IsAudioStreamPlaying" (stream AS AudioStream) AS BYTE
DECLARE SUB      StopAudioStream LIB "raylib" ALIAS "StopAudioStream" (stream AS AudioStream)
DECLARE SUB      SetAudioStreamVolume LIB "raylib" ALIAS "SetAudioStreamVolume" (stream AS AudioStream, volume AS SINGLE)
DECLARE SUB      SetAudioStreamPitch LIB "raylib" ALIAS "SetAudioStreamPitch" (stream AS AudioStream, pitch AS SINGLE)
DECLARE SUB      SetAudioStreamPan LIB "raylib" ALIAS "SetAudioStreamPan" (stream AS AudioStream, pan AS SINGLE)
DECLARE SUB      SetAudioStreamBufferSizeDefault LIB "raylib" ALIAS "SetAudioStreamBufferSizeDefault" (size AS INTEGER)
DECLARE SUB      SetAudioStreamCallback LIB "raylib" ALIAS "SetAudioStreamCallback" (stream AS AudioStream, callback AS POINTER)
DECLARE SUB      AttachAudioStreamProcessor LIB "raylib" ALIAS "AttachAudioStreamProcessor" (stream AS AudioStream, processor AS POINTER)
DECLARE SUB      DetachAudioStreamProcessor LIB "raylib" ALIAS "DetachAudioStreamProcessor" (stream AS AudioStream, processor AS POINTER)
DECLARE SUB      AttachAudioMixedProcessor LIB "raylib" ALIAS "AttachAudioMixedProcessor" (processor AS POINTER)
DECLARE SUB      DetachAudioMixedProcessor LIB "raylib" ALIAS "DetachAudioMixedProcessor" (processor AS POINTER)
