' demo_rqbasic.bas — exercise the sqlite3 bindings generated by
' `pascal_bindgen --rqbasic`. Opens an in-memory database, creates
' a table, inserts a few rows, and reports back.

$INCLUDE "sqlite3_rqbasic.bas"

DIM db AS Psqlite3
DIM rc AS INTEGER
DIM errmsg AS POINTER

rc = sqlite3_open(PCHAR(":memory:"), VARPTR(db))
IF rc <> 0 THEN
  PRINT "sqlite3_open failed, rc="; rc
  HALT
END IF

rc = sqlite3_exec(db, _
                  PCHAR("CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT)"), _
                  null, null, VARPTR(errmsg))
IF rc <> 0 THEN
  PRINT "CREATE TABLE failed, rc="; rc
  HALT
END IF

rc = sqlite3_exec(db, _
                  PCHAR("INSERT INTO t (name) VALUES ('alice'), ('bob'), ('carol')"), _
                  null, null, VARPTR(errmsg))
IF rc <> 0 THEN
  PRINT "INSERT failed, rc="; rc
  HALT
END IF

PRINT "sqlite demo OK — 3 rows inserted into :memory: db"

sqlite3_close(db)
