{ DO NOT EDIT — generated by pascal_bindgen (Blaise dialect).
  source: /usr/include/sqlite3.h
  library: libsqlite3   -- informational; Blaise resolves externs at link time
}

unit sqlite3_blaise;

interface

type
  __va_list_tag = record
    gp_offset: Cardinal;
    fp_offset: Cardinal;
    overflow_arg_area: Pointer;
    reg_save_area: Pointer;
  end;
  va_list = array[0..0] of __va_list_tag;
  sqlite3_index_constraint = record end;
  sqlite3_index_constraint_usage = record end;
  sqlite3_index_orderby = record end;
  PByte = ^Byte;
  PCardinal = ^Cardinal;
  PDouble = ^Double;
  Pfts5_api = ^fts5_api;
  Pfts5_tokenizer = ^fts5_tokenizer;
  PFts5Context = ^Fts5Context;
  PFts5ExtensionApi = ^Fts5ExtensionApi;
  PFts5PhraseIter = ^Fts5PhraseIter;
  PFts5Tokenizer = ^Fts5Tokenizer;
  PInt64 = ^Int64;
  PInteger = ^Integer_;
  PPChar = ^PChar_;
  PPFts5Tokenizer = ^PFts5Tokenizer;
  PPointer = ^Pointer_;
  PPPChar = ^PPChar;
  PPsqlite3 = ^Psqlite3;
  PPsqlite3_blob = ^Psqlite3_blob;
  PPsqlite3_snapshot = ^Psqlite3_snapshot;
  PPsqlite3_stmt = ^Psqlite3_stmt;
  PPsqlite3_value = ^Psqlite3_value;
  PPsqlite3_vtab = ^Psqlite3_vtab;
  PPsqlite3_vtab_cursor = ^Psqlite3_vtab_cursor;
  Psqlite3 = ^sqlite3;
  Psqlite3_backup = ^sqlite3_backup;
  Psqlite3_blob = ^sqlite3_blob;
  Psqlite3_context = ^sqlite3_context;
  Psqlite3_file = ^sqlite3_file;
  Psqlite3_index_constraint = ^sqlite3_index_constraint;
  Psqlite3_index_constraint_usage = ^sqlite3_index_constraint_usage;
  Psqlite3_index_info = ^sqlite3_index_info;
  Psqlite3_index_orderby = ^sqlite3_index_orderby;
  Psqlite3_int64 = ^sqlite3_int64;
  Psqlite3_io_methods = ^sqlite3_io_methods;
  Psqlite3_module = ^sqlite3_module;
  Psqlite3_mutex = ^sqlite3_mutex;
  Psqlite3_pcache = ^sqlite3_pcache;
  Psqlite3_pcache_page = ^sqlite3_pcache_page;
  Psqlite3_rtree_dbl = ^sqlite3_rtree_dbl;
  Psqlite3_rtree_geometry = ^sqlite3_rtree_geometry;
  Psqlite3_rtree_query_info = ^sqlite3_rtree_query_info;
  Psqlite3_snapshot = ^sqlite3_snapshot;
  Psqlite3_stmt = ^sqlite3_stmt;
  Psqlite3_str = ^sqlite3_str;
  Psqlite3_value = ^sqlite3_value;
  Psqlite3_vfs = ^sqlite3_vfs;
  Psqlite3_vtab = ^sqlite3_vtab;
  Psqlite3_vtab_cursor = ^sqlite3_vtab_cursor;
  sqlite3 = record  { sqlite3.h:272 }
  end;
  sqlite_int64 = Int64;  { sqlite3.h:301 }
  sqlite_uint64 = UInt64;  { sqlite3.h:302 }
  sqlite3_int64 = sqlite_int64;  { sqlite3.h:304 }
  sqlite3_uint64 = sqlite_uint64;  { sqlite3.h:305 }
  sqlite3_callback = function(arg1: Pointer; arg2: Integer; arg3: PPChar; arg4: PPChar): Integer;  { sqlite3.h:361 }
  sqlite3_file = record  { sqlite3.h:728 }
  end;
  sqlite3_io_methods = record  { sqlite3.h:835 }
    iVersion: Integer;
    xClose: Pointer;
    xRead: Pointer;
    xWrite: Pointer;
    xTruncate: Pointer;
    xSync: Pointer;
    xFileSize: Pointer;
    xLock: Pointer;
    xUnlock: Pointer;
    xCheckReservedLock: Pointer;
    xFileControl: Pointer;
    xSectorSize: Pointer;
    xDeviceCharacteristics: Pointer;
    xShmMap: Pointer;
    xShmLock: Pointer;
    xShmBarrier: Pointer;
    xShmUnmap: Pointer;
    xFetch: Pointer;
    xUnfetch: Pointer;
  end;
  sqlite3_mutex = record  { sqlite3.h:1262 }
  end;
  sqlite3_api_routines = record  { sqlite3.h:1272 }
  end;
  sqlite3_filename = PChar;  { sqlite3.h:1292 }
  sqlite3_vfs = record  { sqlite3.h:1463 }
  end;
  sqlite3_syscall_ptr = procedure;  { sqlite3.h:1464 }
  sqlite3_mem_methods = record  { sqlite3.h:1764 }
  end;
  sqlite3_stmt = record  { sqlite3.h:4045 }
  end;
  sqlite3_value = record  { sqlite3.h:4548 }
  end;
  sqlite3_context = record  { sqlite3.h:4562 }
  end;
  sqlite3_destructor_type = procedure(arg1: Pointer);  { sqlite3.h:6064 }
  sqlite3_vtab = record  { sqlite3.h:7289 }
  end;
  sqlite3_index_info = record  { sqlite3.h:7290 }
  end;
  sqlite3_vtab_cursor = record  { sqlite3.h:7291 }
  end;
  sqlite3_module = record  { sqlite3.h:7292 }
  end;
  sqlite3_blob = record  { sqlite3.h:7702 }
  end;
  sqlite3_mutex_methods = record  { sqlite3.h:8152 }
  end;
  sqlite3_str = record  { sqlite3.h:8419 }
  end;
  sqlite3_pcache = record  { sqlite3.h:8912 }
  end;
  sqlite3_pcache_page = record  { sqlite3.h:8924 }
  end;
  sqlite3_pcache_methods2 = record  { sqlite3.h:9089 }
  end;
  sqlite3_pcache_methods = record  { sqlite3.h:9112 }
  end;
  sqlite3_backup = record  { sqlite3.h:9138 }
  end;
  sqlite3_snapshot = record  { sqlite3.h:10487 }
    hidden: array[0..47] of Byte;
  end;
  sqlite3_rtree_geometry = record  { sqlite3.h:10848 }
  end;
  sqlite3_rtree_query_info = record  { sqlite3.h:10849 }
  end;
  sqlite3_rtree_dbl = Double;  { sqlite3.h:10857 }
  Fts5ExtensionApi = record  { sqlite3.h:12787 }
  end;
  Fts5Context = record  { sqlite3.h:12788 }
  end;
  Fts5PhraseIter = record  { sqlite3.h:12789 }
  end;
  fts5_extension_function = procedure(arg1: PFts5ExtensionApi; arg2: PFts5Context; arg3: Psqlite3_context; arg4: Integer; arg5: PPsqlite3_value);  { sqlite3.h:12791 }
  Fts5Tokenizer = record  { sqlite3.h:13299 }
  end;
  fts5_tokenizer = record  { sqlite3.h:13300 }
  end;
  fts5_api = record  { sqlite3.h:13336 }
  end;

const
  SQLITE_VERSION_NUMBER = 3045001;  { sqlite3.h:150 }
  SQLITE_OK = 0;  { sqlite3.h:444 }
  SQLITE_ERROR = 1;  { sqlite3.h:446 }
  SQLITE_INTERNAL = 2;  { sqlite3.h:447 }
  SQLITE_PERM = 3;  { sqlite3.h:448 }
  SQLITE_ABORT = 4;  { sqlite3.h:449 }
  SQLITE_BUSY = 5;  { sqlite3.h:450 }
  SQLITE_LOCKED = 6;  { sqlite3.h:451 }
  SQLITE_NOMEM = 7;  { sqlite3.h:452 }
  SQLITE_READONLY = 8;  { sqlite3.h:453 }
  SQLITE_INTERRUPT = 9;  { sqlite3.h:454 }
  SQLITE_IOERR = 10;  { sqlite3.h:455 }
  SQLITE_CORRUPT = 11;  { sqlite3.h:456 }
  SQLITE_NOTFOUND = 12;  { sqlite3.h:457 }
  SQLITE_FULL = 13;  { sqlite3.h:458 }
  SQLITE_CANTOPEN = 14;  { sqlite3.h:459 }
  SQLITE_PROTOCOL = 15;  { sqlite3.h:460 }
  SQLITE_EMPTY = 16;  { sqlite3.h:461 }
  SQLITE_SCHEMA = 17;  { sqlite3.h:462 }
  SQLITE_TOOBIG = 18;  { sqlite3.h:463 }
  SQLITE_CONSTRAINT = 19;  { sqlite3.h:464 }
  SQLITE_MISMATCH = 20;  { sqlite3.h:465 }
  SQLITE_MISUSE = 21;  { sqlite3.h:466 }
  SQLITE_NOLFS = 22;  { sqlite3.h:467 }
  SQLITE_AUTH = 23;  { sqlite3.h:468 }
  SQLITE_FORMAT = 24;  { sqlite3.h:469 }
  SQLITE_RANGE = 25;  { sqlite3.h:470 }
  SQLITE_NOTADB = 26;  { sqlite3.h:471 }
  SQLITE_NOTICE = 27;  { sqlite3.h:472 }
  SQLITE_WARNING = 28;  { sqlite3.h:473 }
  SQLITE_ROW = 100;  { sqlite3.h:474 }
  SQLITE_DONE = 101;  { sqlite3.h:475 }
  SQLITE_OPEN_READONLY = $00000001;  { sqlite3.h:593 }
  SQLITE_OPEN_READWRITE = $00000002;  { sqlite3.h:594 }
  SQLITE_OPEN_CREATE = $00000004;  { sqlite3.h:595 }
  SQLITE_OPEN_DELETEONCLOSE = $00000008;  { sqlite3.h:596 }
  SQLITE_OPEN_EXCLUSIVE = $00000010;  { sqlite3.h:597 }
  SQLITE_OPEN_AUTOPROXY = $00000020;  { sqlite3.h:598 }
  SQLITE_OPEN_URI = $00000040;  { sqlite3.h:599 }
  SQLITE_OPEN_MEMORY = $00000080;  { sqlite3.h:600 }
  SQLITE_OPEN_MAIN_DB = $00000100;  { sqlite3.h:601 }
  SQLITE_OPEN_TEMP_DB = $00000200;  { sqlite3.h:602 }
  SQLITE_OPEN_TRANSIENT_DB = $00000400;  { sqlite3.h:603 }
  SQLITE_OPEN_MAIN_JOURNAL = $00000800;  { sqlite3.h:604 }
  SQLITE_OPEN_TEMP_JOURNAL = $00001000;  { sqlite3.h:605 }
  SQLITE_OPEN_SUBJOURNAL = $00002000;  { sqlite3.h:606 }
  SQLITE_OPEN_SUPER_JOURNAL = $00004000;  { sqlite3.h:607 }
  SQLITE_OPEN_NOMUTEX = $00008000;  { sqlite3.h:608 }
  SQLITE_OPEN_FULLMUTEX = $00010000;  { sqlite3.h:609 }
  SQLITE_OPEN_SHAREDCACHE = $00020000;  { sqlite3.h:610 }
  SQLITE_OPEN_PRIVATECACHE = $00040000;  { sqlite3.h:611 }
  SQLITE_OPEN_WAL = $00080000;  { sqlite3.h:612 }
  SQLITE_OPEN_NOFOLLOW = $01000000;  { sqlite3.h:613 }
  SQLITE_OPEN_EXRESCODE = $02000000;  { sqlite3.h:614 }
  SQLITE_OPEN_MASTER_JOURNAL = $00004000;  { sqlite3.h:618 }
  SQLITE_IOCAP_ATOMIC = $00000001;  { sqlite3.h:654 }
  SQLITE_IOCAP_ATOMIC512 = $00000002;  { sqlite3.h:655 }
  SQLITE_IOCAP_ATOMIC1K = $00000004;  { sqlite3.h:656 }
  SQLITE_IOCAP_ATOMIC2K = $00000008;  { sqlite3.h:657 }
  SQLITE_IOCAP_ATOMIC4K = $00000010;  { sqlite3.h:658 }
  SQLITE_IOCAP_ATOMIC8K = $00000020;  { sqlite3.h:659 }
  SQLITE_IOCAP_ATOMIC16K = $00000040;  { sqlite3.h:660 }
  SQLITE_IOCAP_ATOMIC32K = $00000080;  { sqlite3.h:661 }
  SQLITE_IOCAP_ATOMIC64K = $00000100;  { sqlite3.h:662 }
  SQLITE_IOCAP_SAFE_APPEND = $00000200;  { sqlite3.h:663 }
  SQLITE_IOCAP_SEQUENTIAL = $00000400;  { sqlite3.h:664 }
  SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN = $00000800;  { sqlite3.h:665 }
  SQLITE_IOCAP_POWERSAFE_OVERWRITE = $00001000;  { sqlite3.h:666 }
  SQLITE_IOCAP_IMMUTABLE = $00002000;  { sqlite3.h:667 }
  SQLITE_IOCAP_BATCH_ATOMIC = $00004000;  { sqlite3.h:668 }
  SQLITE_LOCK_NONE = 0;  { sqlite3.h:681 }
  SQLITE_LOCK_SHARED = 1;  { sqlite3.h:682 }
  SQLITE_LOCK_RESERVED = 2;  { sqlite3.h:683 }
  SQLITE_LOCK_PENDING = 3;  { sqlite3.h:684 }
  SQLITE_LOCK_EXCLUSIVE = 4;  { sqlite3.h:685 }
  SQLITE_SYNC_NORMAL = $00002;  { sqlite3.h:713 }
  SQLITE_SYNC_FULL = $00003;  { sqlite3.h:714 }
  SQLITE_SYNC_DATAONLY = $00010;  { sqlite3.h:715 }
  SQLITE_FCNTL_LOCKSTATE = 1;  { sqlite3.h:1204 }
  SQLITE_FCNTL_GET_LOCKPROXYFILE = 2;  { sqlite3.h:1205 }
  SQLITE_FCNTL_SET_LOCKPROXYFILE = 3;  { sqlite3.h:1206 }
  SQLITE_FCNTL_LAST_ERRNO = 4;  { sqlite3.h:1207 }
  SQLITE_FCNTL_SIZE_HINT = 5;  { sqlite3.h:1208 }
  SQLITE_FCNTL_CHUNK_SIZE = 6;  { sqlite3.h:1209 }
  SQLITE_FCNTL_FILE_POINTER = 7;  { sqlite3.h:1210 }
  SQLITE_FCNTL_SYNC_OMITTED = 8;  { sqlite3.h:1211 }
  SQLITE_FCNTL_WIN32_AV_RETRY = 9;  { sqlite3.h:1212 }
  SQLITE_FCNTL_PERSIST_WAL = 10;  { sqlite3.h:1213 }
  SQLITE_FCNTL_OVERWRITE = 11;  { sqlite3.h:1214 }
  SQLITE_FCNTL_VFSNAME = 12;  { sqlite3.h:1215 }
  SQLITE_FCNTL_POWERSAFE_OVERWRITE = 13;  { sqlite3.h:1216 }
  SQLITE_FCNTL_PRAGMA = 14;  { sqlite3.h:1217 }
  SQLITE_FCNTL_BUSYHANDLER = 15;  { sqlite3.h:1218 }
  SQLITE_FCNTL_TEMPFILENAME = 16;  { sqlite3.h:1219 }
  SQLITE_FCNTL_MMAP_SIZE = 18;  { sqlite3.h:1220 }
  SQLITE_FCNTL_TRACE = 19;  { sqlite3.h:1221 }
  SQLITE_FCNTL_HAS_MOVED = 20;  { sqlite3.h:1222 }
  SQLITE_FCNTL_SYNC = 21;  { sqlite3.h:1223 }
  SQLITE_FCNTL_COMMIT_PHASETWO = 22;  { sqlite3.h:1224 }
  SQLITE_FCNTL_WIN32_SET_HANDLE = 23;  { sqlite3.h:1225 }
  SQLITE_FCNTL_WAL_BLOCK = 24;  { sqlite3.h:1226 }
  SQLITE_FCNTL_ZIPVFS = 25;  { sqlite3.h:1227 }
  SQLITE_FCNTL_RBU = 26;  { sqlite3.h:1228 }
  SQLITE_FCNTL_VFS_POINTER = 27;  { sqlite3.h:1229 }
  SQLITE_FCNTL_JOURNAL_POINTER = 28;  { sqlite3.h:1230 }
  SQLITE_FCNTL_WIN32_GET_HANDLE = 29;  { sqlite3.h:1231 }
  SQLITE_FCNTL_PDB = 30;  { sqlite3.h:1232 }
  SQLITE_FCNTL_BEGIN_ATOMIC_WRITE = 31;  { sqlite3.h:1233 }
  SQLITE_FCNTL_COMMIT_ATOMIC_WRITE = 32;  { sqlite3.h:1234 }
  SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE = 33;  { sqlite3.h:1235 }
  SQLITE_FCNTL_LOCK_TIMEOUT = 34;  { sqlite3.h:1236 }
  SQLITE_FCNTL_DATA_VERSION = 35;  { sqlite3.h:1237 }
  SQLITE_FCNTL_SIZE_LIMIT = 36;  { sqlite3.h:1238 }
  SQLITE_FCNTL_CKPT_DONE = 37;  { sqlite3.h:1239 }
  SQLITE_FCNTL_RESERVE_BYTES = 38;  { sqlite3.h:1240 }
  SQLITE_FCNTL_CKPT_START = 39;  { sqlite3.h:1241 }
  SQLITE_FCNTL_EXTERNAL_READER = 40;  { sqlite3.h:1242 }
  SQLITE_FCNTL_CKSM_FILE = 41;  { sqlite3.h:1243 }
  SQLITE_FCNTL_RESET_CACHE = 42;  { sqlite3.h:1244 }
  SQLITE_ACCESS_EXISTS = 0;  { sqlite3.h:1524 }
  SQLITE_ACCESS_READWRITE = 1;  { sqlite3.h:1525 }
  SQLITE_ACCESS_READ = 2;  { sqlite3.h:1526 }
  SQLITE_SHM_UNLOCK = 1;  { sqlite3.h:1550 }
  SQLITE_SHM_LOCK = 2;  { sqlite3.h:1551 }
  SQLITE_SHM_SHARED = 4;  { sqlite3.h:1552 }
  SQLITE_SHM_EXCLUSIVE = 8;  { sqlite3.h:1553 }
  SQLITE_SHM_NLOCK = 8;  { sqlite3.h:1563 }
  SQLITE_CONFIG_SINGLETHREAD = 1;  { sqlite3.h:2149 }
  SQLITE_CONFIG_MULTITHREAD = 2;  { sqlite3.h:2150 }
  SQLITE_CONFIG_SERIALIZED = 3;  { sqlite3.h:2151 }
  SQLITE_CONFIG_MALLOC = 4;  { sqlite3.h:2152 }
  SQLITE_CONFIG_GETMALLOC = 5;  { sqlite3.h:2153 }
  SQLITE_CONFIG_SCRATCH = 6;  { sqlite3.h:2154 }
  SQLITE_CONFIG_PAGECACHE = 7;  { sqlite3.h:2155 }
  SQLITE_CONFIG_HEAP = 8;  { sqlite3.h:2156 }
  SQLITE_CONFIG_MEMSTATUS = 9;  { sqlite3.h:2157 }
  SQLITE_CONFIG_MUTEX = 10;  { sqlite3.h:2158 }
  SQLITE_CONFIG_GETMUTEX = 11;  { sqlite3.h:2159 }
  SQLITE_CONFIG_LOOKASIDE = 13;  { sqlite3.h:2161 }
  SQLITE_CONFIG_PCACHE = 14;  { sqlite3.h:2162 }
  SQLITE_CONFIG_GETPCACHE = 15;  { sqlite3.h:2163 }
  SQLITE_CONFIG_LOG = 16;  { sqlite3.h:2164 }
  SQLITE_CONFIG_URI = 17;  { sqlite3.h:2165 }
  SQLITE_CONFIG_PCACHE2 = 18;  { sqlite3.h:2166 }
  SQLITE_CONFIG_GETPCACHE2 = 19;  { sqlite3.h:2167 }
  SQLITE_CONFIG_COVERING_INDEX_SCAN = 20;  { sqlite3.h:2168 }
  SQLITE_CONFIG_SQLLOG = 21;  { sqlite3.h:2169 }
  SQLITE_CONFIG_MMAP_SIZE = 22;  { sqlite3.h:2170 }
  SQLITE_CONFIG_WIN32_HEAPSIZE = 23;  { sqlite3.h:2171 }
  SQLITE_CONFIG_PCACHE_HDRSZ = 24;  { sqlite3.h:2172 }
  SQLITE_CONFIG_PMASZ = 25;  { sqlite3.h:2173 }
  SQLITE_CONFIG_STMTJRNL_SPILL = 26;  { sqlite3.h:2174 }
  SQLITE_CONFIG_SMALL_MALLOC = 27;  { sqlite3.h:2175 }
  SQLITE_CONFIG_SORTERREF_SIZE = 28;  { sqlite3.h:2176 }
  SQLITE_CONFIG_MEMDB_MAXSIZE = 29;  { sqlite3.h:2177 }
  SQLITE_DBCONFIG_MAINDBNAME = 1000;  { sqlite3.h:2516 }
  SQLITE_DBCONFIG_LOOKASIDE = 1001;  { sqlite3.h:2517 }
  SQLITE_DBCONFIG_ENABLE_FKEY = 1002;  { sqlite3.h:2518 }
  SQLITE_DBCONFIG_ENABLE_TRIGGER = 1003;  { sqlite3.h:2519 }
  SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004;  { sqlite3.h:2520 }
  SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005;  { sqlite3.h:2521 }
  SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE = 1006;  { sqlite3.h:2522 }
  SQLITE_DBCONFIG_ENABLE_QPSG = 1007;  { sqlite3.h:2523 }
  SQLITE_DBCONFIG_TRIGGER_EQP = 1008;  { sqlite3.h:2524 }
  SQLITE_DBCONFIG_RESET_DATABASE = 1009;  { sqlite3.h:2525 }
  SQLITE_DBCONFIG_DEFENSIVE = 1010;  { sqlite3.h:2526 }
  SQLITE_DBCONFIG_WRITABLE_SCHEMA = 1011;  { sqlite3.h:2527 }
  SQLITE_DBCONFIG_LEGACY_ALTER_TABLE = 1012;  { sqlite3.h:2528 }
  SQLITE_DBCONFIG_DQS_DML = 1013;  { sqlite3.h:2529 }
  SQLITE_DBCONFIG_DQS_DDL = 1014;  { sqlite3.h:2530 }
  SQLITE_DBCONFIG_ENABLE_VIEW = 1015;  { sqlite3.h:2531 }
  SQLITE_DBCONFIG_LEGACY_FILE_FORMAT = 1016;  { sqlite3.h:2532 }
  SQLITE_DBCONFIG_TRUSTED_SCHEMA = 1017;  { sqlite3.h:2533 }
  SQLITE_DBCONFIG_STMT_SCANSTATUS = 1018;  { sqlite3.h:2534 }
  SQLITE_DBCONFIG_REVERSE_SCANORDER = 1019;  { sqlite3.h:2535 }
  SQLITE_DBCONFIG_MAX = 1019;  { sqlite3.h:2536 }
  SQLITE_DENY = 1;  { sqlite3.h:3252 }
  SQLITE_IGNORE = 2;  { sqlite3.h:3253 }
  SQLITE_CREATE_INDEX = 1;  { sqlite3.h:3275 }
  SQLITE_CREATE_TABLE = 2;  { sqlite3.h:3276 }
  SQLITE_CREATE_TEMP_INDEX = 3;  { sqlite3.h:3277 }
  SQLITE_CREATE_TEMP_TABLE = 4;  { sqlite3.h:3278 }
  SQLITE_CREATE_TEMP_TRIGGER = 5;  { sqlite3.h:3279 }
  SQLITE_CREATE_TEMP_VIEW = 6;  { sqlite3.h:3280 }
  SQLITE_CREATE_TRIGGER = 7;  { sqlite3.h:3281 }
  SQLITE_CREATE_VIEW = 8;  { sqlite3.h:3282 }
  SQLITE_DELETE = 9;  { sqlite3.h:3283 }
  SQLITE_DROP_INDEX = 10;  { sqlite3.h:3284 }
  SQLITE_DROP_TABLE = 11;  { sqlite3.h:3285 }
  SQLITE_DROP_TEMP_INDEX = 12;  { sqlite3.h:3286 }
  SQLITE_DROP_TEMP_TABLE = 13;  { sqlite3.h:3287 }
  SQLITE_DROP_TEMP_TRIGGER = 14;  { sqlite3.h:3288 }
  SQLITE_DROP_TEMP_VIEW = 15;  { sqlite3.h:3289 }
  SQLITE_DROP_TRIGGER = 16;  { sqlite3.h:3290 }
  SQLITE_DROP_VIEW = 17;  { sqlite3.h:3291 }
  SQLITE_INSERT = 18;  { sqlite3.h:3292 }
  SQLITE_PRAGMA = 19;  { sqlite3.h:3293 }
  SQLITE_READ = 20;  { sqlite3.h:3294 }
  SQLITE_SELECT = 21;  { sqlite3.h:3295 }
  SQLITE_TRANSACTION = 22;  { sqlite3.h:3296 }
  SQLITE_UPDATE = 23;  { sqlite3.h:3297 }
  SQLITE_ATTACH = 24;  { sqlite3.h:3298 }
  SQLITE_DETACH = 25;  { sqlite3.h:3299 }
  SQLITE_ALTER_TABLE = 26;  { sqlite3.h:3300 }
  SQLITE_REINDEX = 27;  { sqlite3.h:3301 }
  SQLITE_ANALYZE = 28;  { sqlite3.h:3302 }
  SQLITE_CREATE_VTABLE = 29;  { sqlite3.h:3303 }
  SQLITE_DROP_VTABLE = 30;  { sqlite3.h:3304 }
  SQLITE_FUNCTION = 31;  { sqlite3.h:3305 }
  SQLITE_SAVEPOINT = 32;  { sqlite3.h:3306 }
  SQLITE_COPY = 0;  { sqlite3.h:3307 }
  SQLITE_RECURSIVE = 33;  { sqlite3.h:3308 }
  SQLITE_TRACE_STMT = $01;  { sqlite3.h:3399 }
  SQLITE_TRACE_PROFILE = $02;  { sqlite3.h:3400 }
  SQLITE_TRACE_ROW = $04;  { sqlite3.h:3401 }
  SQLITE_TRACE_CLOSE = $08;  { sqlite3.h:3402 }
  SQLITE_LIMIT_LENGTH = 0;  { sqlite3.h:4145 }
  SQLITE_LIMIT_SQL_LENGTH = 1;  { sqlite3.h:4146 }
  SQLITE_LIMIT_COLUMN = 2;  { sqlite3.h:4147 }
  SQLITE_LIMIT_EXPR_DEPTH = 3;  { sqlite3.h:4148 }
  SQLITE_LIMIT_COMPOUND_SELECT = 4;  { sqlite3.h:4149 }
  SQLITE_LIMIT_VDBE_OP = 5;  { sqlite3.h:4150 }
  SQLITE_LIMIT_FUNCTION_ARG = 6;  { sqlite3.h:4151 }
  SQLITE_LIMIT_ATTACHED = 7;  { sqlite3.h:4152 }
  SQLITE_LIMIT_LIKE_PATTERN_LENGTH = 8;  { sqlite3.h:4153 }
  SQLITE_LIMIT_VARIABLE_NUMBER = 9;  { sqlite3.h:4154 }
  SQLITE_LIMIT_TRIGGER_DEPTH = 10;  { sqlite3.h:4155 }
  SQLITE_LIMIT_WORKER_THREADS = 11;  { sqlite3.h:4156 }
  SQLITE_PREPARE_PERSISTENT = $01;  { sqlite3.h:4193 }
  SQLITE_PREPARE_NORMALIZE = $02;  { sqlite3.h:4194 }
  SQLITE_PREPARE_NO_VTAB = $04;  { sqlite3.h:4195 }
  SQLITE_INTEGER = 1;  { sqlite3.h:5051 }
  SQLITE_FLOAT = 2;  { sqlite3.h:5052 }
  SQLITE_BLOB = 4;  { sqlite3.h:5053 }
  SQLITE_NULL = 5;  { sqlite3.h:5054 }
  SQLITE_TEXT = 3;  { sqlite3.h:5058 }
  SQLITE3_TEXT = 3;  { sqlite3.h:5060 }
  SQLITE_UTF8 = 1;  { sqlite3.h:5527 }
  SQLITE_UTF16LE = 2;  { sqlite3.h:5528 }
  SQLITE_UTF16BE = 3;  { sqlite3.h:5529 }
  SQLITE_UTF16 = 4;  { sqlite3.h:5530 }
  SQLITE_ANY = 5;  { sqlite3.h:5531 }
  SQLITE_UTF16_ALIGNED = 8;  { sqlite3.h:5532 }
  SQLITE_DETERMINISTIC = $000000800;  { sqlite3.h:5624 }
  SQLITE_DIRECTONLY = $000080000;  { sqlite3.h:5625 }
  SQLITE_SUBTYPE = $000100000;  { sqlite3.h:5626 }
  SQLITE_INNOCUOUS = $000200000;  { sqlite3.h:5627 }
  SQLITE_RESULT_SUBTYPE = $001000000;  { sqlite3.h:5628 }
  SQLITE_WIN32_DATA_DIRECTORY_TYPE = 1;  { sqlite3.h:6572 }
  SQLITE_WIN32_TEMP_DIRECTORY_TYPE = 2;  { sqlite3.h:6573 }
  SQLITE_TXN_NONE = 0;  { sqlite3.h:6723 }
  SQLITE_TXN_READ = 1;  { sqlite3.h:6724 }
  SQLITE_TXN_WRITE = 2;  { sqlite3.h:6725 }
  SQLITE_INDEX_SCAN_UNIQUE = 1;  { sqlite3.h:7493 }
  SQLITE_INDEX_CONSTRAINT_EQ = 2;  { sqlite3.h:7533 }
  SQLITE_INDEX_CONSTRAINT_GT = 4;  { sqlite3.h:7534 }
  SQLITE_INDEX_CONSTRAINT_LE = 8;  { sqlite3.h:7535 }
  SQLITE_INDEX_CONSTRAINT_LT = 16;  { sqlite3.h:7536 }
  SQLITE_INDEX_CONSTRAINT_GE = 32;  { sqlite3.h:7537 }
  SQLITE_INDEX_CONSTRAINT_MATCH = 64;  { sqlite3.h:7538 }
  SQLITE_INDEX_CONSTRAINT_LIKE = 65;  { sqlite3.h:7539 }
  SQLITE_INDEX_CONSTRAINT_GLOB = 66;  { sqlite3.h:7540 }
  SQLITE_INDEX_CONSTRAINT_REGEXP = 67;  { sqlite3.h:7541 }
  SQLITE_INDEX_CONSTRAINT_NE = 68;  { sqlite3.h:7542 }
  SQLITE_INDEX_CONSTRAINT_ISNOT = 69;  { sqlite3.h:7543 }
  SQLITE_INDEX_CONSTRAINT_ISNOTNULL = 70;  { sqlite3.h:7544 }
  SQLITE_INDEX_CONSTRAINT_ISNULL = 71;  { sqlite3.h:7545 }
  SQLITE_INDEX_CONSTRAINT_IS = 72;  { sqlite3.h:7546 }
  SQLITE_INDEX_CONSTRAINT_LIMIT = 73;  { sqlite3.h:7547 }
  SQLITE_INDEX_CONSTRAINT_OFFSET = 74;  { sqlite3.h:7548 }
  SQLITE_INDEX_CONSTRAINT_FUNCTION = 150;  { sqlite3.h:7549 }
  SQLITE_MUTEX_FAST = 0;  { sqlite3.h:8209 }
  SQLITE_MUTEX_RECURSIVE = 1;  { sqlite3.h:8210 }
  SQLITE_MUTEX_STATIC_MAIN = 2;  { sqlite3.h:8211 }
  SQLITE_MUTEX_STATIC_MEM = 3;  { sqlite3.h:8212 }
  SQLITE_MUTEX_STATIC_MEM2 = 4;  { sqlite3.h:8213 }
  SQLITE_MUTEX_STATIC_OPEN = 4;  { sqlite3.h:8214 }
  SQLITE_MUTEX_STATIC_PRNG = 5;  { sqlite3.h:8215 }
  SQLITE_MUTEX_STATIC_LRU = 6;  { sqlite3.h:8216 }
  SQLITE_MUTEX_STATIC_LRU2 = 7;  { sqlite3.h:8217 }
  SQLITE_MUTEX_STATIC_PMEM = 7;  { sqlite3.h:8218 }
  SQLITE_MUTEX_STATIC_APP1 = 8;  { sqlite3.h:8219 }
  SQLITE_MUTEX_STATIC_APP2 = 9;  { sqlite3.h:8220 }
  SQLITE_MUTEX_STATIC_APP3 = 10;  { sqlite3.h:8221 }
  SQLITE_MUTEX_STATIC_VFS1 = 11;  { sqlite3.h:8222 }
  SQLITE_MUTEX_STATIC_VFS2 = 12;  { sqlite3.h:8223 }
  SQLITE_MUTEX_STATIC_VFS3 = 13;  { sqlite3.h:8224 }
  SQLITE_MUTEX_STATIC_MASTER = 2;  { sqlite3.h:8227 }
  SQLITE_TESTCTRL_FIRST = 5;  { sqlite3.h:8315 }
  SQLITE_TESTCTRL_PRNG_SAVE = 5;  { sqlite3.h:8316 }
  SQLITE_TESTCTRL_PRNG_RESTORE = 6;  { sqlite3.h:8317 }
  SQLITE_TESTCTRL_PRNG_RESET = 7;  { sqlite3.h:8318 }
  SQLITE_TESTCTRL_FK_NO_ACTION = 7;  { sqlite3.h:8319 }
  SQLITE_TESTCTRL_BITVEC_TEST = 8;  { sqlite3.h:8320 }
  SQLITE_TESTCTRL_FAULT_INSTALL = 9;  { sqlite3.h:8321 }
  SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS = 10;  { sqlite3.h:8322 }
  SQLITE_TESTCTRL_PENDING_BYTE = 11;  { sqlite3.h:8323 }
  SQLITE_TESTCTRL_ASSERT = 12;  { sqlite3.h:8324 }
  SQLITE_TESTCTRL_ALWAYS = 13;  { sqlite3.h:8325 }
  SQLITE_TESTCTRL_RESERVE = 14;  { sqlite3.h:8326 }
  SQLITE_TESTCTRL_JSON_SELFCHECK = 14;  { sqlite3.h:8327 }
  SQLITE_TESTCTRL_OPTIMIZATIONS = 15;  { sqlite3.h:8328 }
  SQLITE_TESTCTRL_ISKEYWORD = 16;  { sqlite3.h:8329 }
  SQLITE_TESTCTRL_SCRATCHMALLOC = 17;  { sqlite3.h:8330 }
  SQLITE_TESTCTRL_INTERNAL_FUNCTIONS = 17;  { sqlite3.h:8331 }
  SQLITE_TESTCTRL_LOCALTIME_FAULT = 18;  { sqlite3.h:8332 }
  SQLITE_TESTCTRL_EXPLAIN_STMT = 19;  { sqlite3.h:8333 }
  SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD = 19;  { sqlite3.h:8334 }
  SQLITE_TESTCTRL_NEVER_CORRUPT = 20;  { sqlite3.h:8335 }
  SQLITE_TESTCTRL_VDBE_COVERAGE = 21;  { sqlite3.h:8336 }
  SQLITE_TESTCTRL_BYTEORDER = 22;  { sqlite3.h:8337 }
  SQLITE_TESTCTRL_ISINIT = 23;  { sqlite3.h:8338 }
  SQLITE_TESTCTRL_SORTER_MMAP = 24;  { sqlite3.h:8339 }
  SQLITE_TESTCTRL_IMPOSTER = 25;  { sqlite3.h:8340 }
  SQLITE_TESTCTRL_PARSER_COVERAGE = 26;  { sqlite3.h:8341 }
  SQLITE_TESTCTRL_RESULT_INTREAL = 27;  { sqlite3.h:8342 }
  SQLITE_TESTCTRL_PRNG_SEED = 28;  { sqlite3.h:8343 }
  SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS = 29;  { sqlite3.h:8344 }
  SQLITE_TESTCTRL_SEEK_COUNT = 30;  { sqlite3.h:8345 }
  SQLITE_TESTCTRL_TRACEFLAGS = 31;  { sqlite3.h:8346 }
  SQLITE_TESTCTRL_TUNE = 32;  { sqlite3.h:8347 }
  SQLITE_TESTCTRL_LOGEST = 33;  { sqlite3.h:8348 }
  SQLITE_TESTCTRL_USELONGDOUBLE = 34;  { sqlite3.h:8349 }
  SQLITE_TESTCTRL_LAST = 34;  { sqlite3.h:8350 }
  SQLITE_STATUS_MEMORY_USED = 0;  { sqlite3.h:8637 }
  SQLITE_STATUS_PAGECACHE_USED = 1;  { sqlite3.h:8638 }
  SQLITE_STATUS_PAGECACHE_OVERFLOW = 2;  { sqlite3.h:8639 }
  SQLITE_STATUS_SCRATCH_USED = 3;  { sqlite3.h:8640 }
  SQLITE_STATUS_SCRATCH_OVERFLOW = 4;  { sqlite3.h:8641 }
  SQLITE_STATUS_MALLOC_SIZE = 5;  { sqlite3.h:8642 }
  SQLITE_STATUS_PARSER_STACK = 6;  { sqlite3.h:8643 }
  SQLITE_STATUS_PAGECACHE_SIZE = 7;  { sqlite3.h:8644 }
  SQLITE_STATUS_SCRATCH_SIZE = 8;  { sqlite3.h:8645 }
  SQLITE_STATUS_MALLOC_COUNT = 9;  { sqlite3.h:8646 }
  SQLITE_DBSTATUS_LOOKASIDE_USED = 0;  { sqlite3.h:8784 }
  SQLITE_DBSTATUS_CACHE_USED = 1;  { sqlite3.h:8785 }
  SQLITE_DBSTATUS_SCHEMA_USED = 2;  { sqlite3.h:8786 }
  SQLITE_DBSTATUS_STMT_USED = 3;  { sqlite3.h:8787 }
  SQLITE_DBSTATUS_LOOKASIDE_HIT = 4;  { sqlite3.h:8788 }
  SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE = 5;  { sqlite3.h:8789 }
  SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL = 6;  { sqlite3.h:8790 }
  SQLITE_DBSTATUS_CACHE_HIT = 7;  { sqlite3.h:8791 }
  SQLITE_DBSTATUS_CACHE_MISS = 8;  { sqlite3.h:8792 }
  SQLITE_DBSTATUS_CACHE_WRITE = 9;  { sqlite3.h:8793 }
  SQLITE_DBSTATUS_DEFERRED_FKS = 10;  { sqlite3.h:8794 }
  SQLITE_DBSTATUS_CACHE_USED_SHARED = 11;  { sqlite3.h:8795 }
  SQLITE_DBSTATUS_CACHE_SPILL = 12;  { sqlite3.h:8796 }
  SQLITE_DBSTATUS_MAX = 12;  { sqlite3.h:8797 }
  SQLITE_STMTSTATUS_FULLSCAN_STEP = 1;  { sqlite3.h:8891 }
  SQLITE_STMTSTATUS_SORT = 2;  { sqlite3.h:8892 }
  SQLITE_STMTSTATUS_AUTOINDEX = 3;  { sqlite3.h:8893 }
  SQLITE_STMTSTATUS_VM_STEP = 4;  { sqlite3.h:8894 }
  SQLITE_STMTSTATUS_REPREPARE = 5;  { sqlite3.h:8895 }
  SQLITE_STMTSTATUS_RUN = 6;  { sqlite3.h:8896 }
  SQLITE_STMTSTATUS_FILTER_MISS = 7;  { sqlite3.h:8897 }
  SQLITE_STMTSTATUS_FILTER_HIT = 8;  { sqlite3.h:8898 }
  SQLITE_STMTSTATUS_MEMUSED = 99;  { sqlite3.h:8899 }
  SQLITE_CHECKPOINT_PASSIVE = 0;  { sqlite3.h:9736 }
  SQLITE_CHECKPOINT_FULL = 1;  { sqlite3.h:9737 }
  SQLITE_CHECKPOINT_RESTART = 2;  { sqlite3.h:9738 }
  SQLITE_CHECKPOINT_TRUNCATE = 3;  { sqlite3.h:9739 }
  SQLITE_VTAB_CONSTRAINT_SUPPORT = 1;  { sqlite3.h:9832 }
  SQLITE_VTAB_INNOCUOUS = 2;  { sqlite3.h:9833 }
  SQLITE_VTAB_DIRECTONLY = 3;  { sqlite3.h:9834 }
  SQLITE_VTAB_USES_ALL_SCHEMAS = 4;  { sqlite3.h:9835 }
  SQLITE_ROLLBACK = 1;  { sqlite3.h:10158 }
  SQLITE_FAIL = 3;  { sqlite3.h:10160 }
  SQLITE_REPLACE = 5;  { sqlite3.h:10162 }
  SQLITE_SCANSTAT_NLOOP = 0;  { sqlite3.h:10227 }
  SQLITE_SCANSTAT_NVISIT = 1;  { sqlite3.h:10228 }
  SQLITE_SCANSTAT_EST = 2;  { sqlite3.h:10229 }
  SQLITE_SCANSTAT_NAME = 3;  { sqlite3.h:10230 }
  SQLITE_SCANSTAT_EXPLAIN = 4;  { sqlite3.h:10231 }
  SQLITE_SCANSTAT_SELECTID = 5;  { sqlite3.h:10232 }
  SQLITE_SCANSTAT_PARENTID = 6;  { sqlite3.h:10233 }
  SQLITE_SCANSTAT_NCYCLE = 7;  { sqlite3.h:10234 }
  SQLITE_SCANSTAT_COMPLEX = $0001;  { sqlite3.h:10291 }
  SQLITE_SERIALIZE_NOCOPY = $001;  { sqlite3.h:10721 }
  SQLITE_DESERIALIZE_FREEONCLOSE = 1;  { sqlite3.h:10796 }
  SQLITE_DESERIALIZE_RESIZEABLE = 2;  { sqlite3.h:10797 }
  SQLITE_DESERIALIZE_READONLY = 4;  { sqlite3.h:10798 }
  NOT_WITHIN = 0;  { sqlite3.h:10933 }
  PARTLY_WITHIN = 1;  { sqlite3.h:10934 }
  FULLY_WITHIN = 2;  { sqlite3.h:10935 }
  FTS5_TOKENIZE_QUERY = $0001;  { sqlite3.h:13320 }
  FTS5_TOKENIZE_PREFIX = $0002;  { sqlite3.h:13321 }
  FTS5_TOKENIZE_DOCUMENT = $0004;  { sqlite3.h:13322 }
  FTS5_TOKENIZE_AUX = $0008;  { sqlite3.h:13323 }
  FTS5_TOKEN_COLOCATED = $0001;  { sqlite3.h:13327 }

function sqlite3_libversion: PChar; external name 'sqlite3_libversion';  { sqlite3.h:186 }
function sqlite3_sourceid: PChar; external name 'sqlite3_sourceid';  { sqlite3.h:187 }
function sqlite3_libversion_number: Integer; external name 'sqlite3_libversion_number';  { sqlite3.h:188 }
function sqlite3_compileoption_used(zOptName: PChar): Integer; external name 'sqlite3_compileoption_used';  { sqlite3.h:213 }
function sqlite3_compileoption_get(N: Integer): PChar; external name 'sqlite3_compileoption_get';  { sqlite3.h:214 }
function sqlite3_threadsafe: Integer; external name 'sqlite3_threadsafe';  { sqlite3.h:256 }
function sqlite3_close(arg1: Psqlite3): Integer; external name 'sqlite3_close';  { sqlite3.h:353 }
function sqlite3_close_v2(arg1: Psqlite3): Integer; external name 'sqlite3_close_v2';  { sqlite3.h:354 }
function sqlite3_exec(arg1: Psqlite3; sql: PChar; callback: Pointer; arg4: Pointer; errmsg: PPChar): Integer; external name 'sqlite3_exec';  { sqlite3.h:425 }
function sqlite3_initialize: Integer; external name 'sqlite3_initialize';  { sqlite3.h:1641 }
function sqlite3_shutdown: Integer; external name 'sqlite3_shutdown';  { sqlite3.h:1642 }
function sqlite3_os_init: Integer; external name 'sqlite3_os_init';  { sqlite3.h:1643 }
function sqlite3_os_end: Integer; external name 'sqlite3_os_end';  { sqlite3.h:1644 }
function sqlite3_config(arg1: Integer): Integer; external name 'sqlite3_config'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { sqlite3.h:1680 }
function sqlite3_db_config(arg1: Psqlite3; op: Integer): Integer; external name 'sqlite3_db_config'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { sqlite3.h:1699 }
function sqlite3_extended_result_codes(arg1: Psqlite3; onoff: Integer): Integer; external name 'sqlite3_extended_result_codes';  { sqlite3.h:2546 }
function sqlite3_last_insert_rowid(arg1: Psqlite3): sqlite3_int64; external name 'sqlite3_last_insert_rowid';  { sqlite3.h:2608 }
procedure sqlite3_set_last_insert_rowid(arg1: Psqlite3; arg2: sqlite3_int64); external name 'sqlite3_set_last_insert_rowid';  { sqlite3.h:2618 }
function sqlite3_changes(arg1: Psqlite3): Integer; external name 'sqlite3_changes';  { sqlite3.h:2679 }
function sqlite3_changes64(arg1: Psqlite3): sqlite3_int64; external name 'sqlite3_changes64';  { sqlite3.h:2680 }
function sqlite3_total_changes(arg1: Psqlite3): Integer; external name 'sqlite3_total_changes';  { sqlite3.h:2721 }
function sqlite3_total_changes64(arg1: Psqlite3): sqlite3_int64; external name 'sqlite3_total_changes64';  { sqlite3.h:2722 }
procedure sqlite3_interrupt(arg1: Psqlite3); external name 'sqlite3_interrupt';  { sqlite3.h:2763 }
function sqlite3_is_interrupted(arg1: Psqlite3): Integer; external name 'sqlite3_is_interrupted';  { sqlite3.h:2764 }
function sqlite3_complete(sql: PChar): Integer; external name 'sqlite3_complete';  { sqlite3.h:2799 }
function sqlite3_complete16(sql: Pointer): Integer; external name 'sqlite3_complete16';  { sqlite3.h:2800 }
function sqlite3_busy_handler(arg1: Psqlite3; arg2: Pointer; arg3: Pointer): Integer; external name 'sqlite3_busy_handler';  { sqlite3.h:2861 }
function sqlite3_busy_timeout(arg1: Psqlite3; ms: Integer): Integer; external name 'sqlite3_busy_timeout';  { sqlite3.h:2884 }
function sqlite3_get_table(db: Psqlite3; zSql: PChar; pazResult: PPPChar; pnRow: PInteger; pnColumn: PInteger; pzErrmsg: PPChar): Integer; external name 'sqlite3_get_table';  { sqlite3.h:2959 }
procedure sqlite3_free_table(result_: PPChar); external name 'sqlite3_free_table';  { sqlite3.h:2967 }
function sqlite3_mprintf(arg1: PChar): PChar; external name 'sqlite3_mprintf'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { sqlite3.h:3009 }
function sqlite3_vmprintf(arg1: PChar; arg2: va_list): PChar; external name 'sqlite3_vmprintf';  { sqlite3.h:3010 }
function sqlite3_snprintf(arg1: Integer; arg2: PChar; arg3: PChar): PChar; external name 'sqlite3_snprintf'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { sqlite3.h:3011 }
function sqlite3_vsnprintf(arg1: Integer; arg2: PChar; arg3: PChar; arg4: va_list): PChar; external name 'sqlite3_vsnprintf';  { sqlite3.h:3012 }
function sqlite3_malloc(arg1: Integer): Pointer; external name 'sqlite3_malloc';  { sqlite3.h:3089 }
function sqlite3_malloc64(arg1: sqlite3_uint64): Pointer; external name 'sqlite3_malloc64';  { sqlite3.h:3090 }
function sqlite3_realloc(arg1: Pointer; arg2: Integer): Pointer; external name 'sqlite3_realloc';  { sqlite3.h:3091 }
function sqlite3_realloc64(arg1: Pointer; arg2: sqlite3_uint64): Pointer; external name 'sqlite3_realloc64';  { sqlite3.h:3092 }
procedure sqlite3_free(arg1: Pointer); external name 'sqlite3_free';  { sqlite3.h:3093 }
function sqlite3_msize(arg1: Pointer): sqlite3_uint64; external name 'sqlite3_msize';  { sqlite3.h:3094 }
function sqlite3_memory_used: sqlite3_int64; external name 'sqlite3_memory_used';  { sqlite3.h:3119 }
function sqlite3_memory_highwater(resetFlag: Integer): sqlite3_int64; external name 'sqlite3_memory_highwater';  { sqlite3.h:3120 }
procedure sqlite3_randomness(N: Integer; P: Pointer); external name 'sqlite3_randomness';  { sqlite3.h:3143 }
function sqlite3_set_authorizer(arg1: Psqlite3; xAuth: Pointer; pUserData: Pointer): Integer; external name 'sqlite3_set_authorizer';  { sqlite3.h:3234 }
function sqlite3_trace(arg1: Psqlite3; xTrace: Pointer; arg3: Pointer): Pointer; external name 'sqlite3_trace';  { sqlite3.h:3342 }
function sqlite3_profile(arg1: Psqlite3; xProfile: Pointer; arg3: Pointer): Pointer; external name 'sqlite3_profile';  { sqlite3.h:3344 }
function sqlite3_trace_v2(arg1: Psqlite3; uMask: Cardinal; xCallback: Pointer; pCtx: Pointer): Integer; external name 'sqlite3_trace_v2';  { sqlite3.h:3435 }
procedure sqlite3_progress_handler(arg1: Psqlite3; arg2: Integer; arg3: Pointer; arg4: Pointer); external name 'sqlite3_progress_handler';  { sqlite3.h:3481 }
function sqlite3_open(filename: PChar; ppDb: PPsqlite3): Integer; external name 'sqlite3_open';  { sqlite3.h:3761 }
function sqlite3_open16(filename: Pointer; ppDb: PPsqlite3): Integer; external name 'sqlite3_open16';  { sqlite3.h:3765 }
function sqlite3_open_v2(filename: PChar; ppDb: PPsqlite3; flags: Integer; zVfs: PChar): Integer; external name 'sqlite3_open_v2';  { sqlite3.h:3769 }
function sqlite3_uri_parameter(z: sqlite3_filename; zParam: PChar): PChar; external name 'sqlite3_uri_parameter';  { sqlite3.h:3842 }
function sqlite3_uri_boolean(z: sqlite3_filename; zParam: PChar; bDefault: Integer): Integer; external name 'sqlite3_uri_boolean';  { sqlite3.h:3843 }
function sqlite3_uri_int64(arg1: sqlite3_filename; arg2: PChar; arg3: sqlite3_int64): sqlite3_int64; external name 'sqlite3_uri_int64';  { sqlite3.h:3844 }
function sqlite3_uri_key(z: sqlite3_filename; N: Integer): PChar; external name 'sqlite3_uri_key';  { sqlite3.h:3845 }
function sqlite3_filename_database(arg1: sqlite3_filename): PChar; external name 'sqlite3_filename_database';  { sqlite3.h:3874 }
function sqlite3_filename_journal(arg1: sqlite3_filename): PChar; external name 'sqlite3_filename_journal';  { sqlite3.h:3875 }
function sqlite3_filename_wal(arg1: sqlite3_filename): PChar; external name 'sqlite3_filename_wal';  { sqlite3.h:3876 }
function sqlite3_database_file_object(arg1: PChar): Psqlite3_file; external name 'sqlite3_database_file_object';  { sqlite3.h:3895 }
function sqlite3_create_filename(zDatabase: PChar; zJournal: PChar; zWal: PChar; nParam: Integer; azParam: PPChar): sqlite3_filename; external name 'sqlite3_create_filename';  { sqlite3.h:3942 }
procedure sqlite3_free_filename(arg1: sqlite3_filename); external name 'sqlite3_free_filename';  { sqlite3.h:3949 }
function sqlite3_errcode(db: Psqlite3): Integer; external name 'sqlite3_errcode';  { sqlite3.h:4014 }
function sqlite3_extended_errcode(db: Psqlite3): Integer; external name 'sqlite3_extended_errcode';  { sqlite3.h:4015 }
function sqlite3_errmsg(arg1: Psqlite3): PChar; external name 'sqlite3_errmsg';  { sqlite3.h:4016 }
function sqlite3_errmsg16(arg1: Psqlite3): Pointer; external name 'sqlite3_errmsg16';  { sqlite3.h:4017 }
function sqlite3_errstr(arg1: Integer): PChar; external name 'sqlite3_errstr';  { sqlite3.h:4018 }
function sqlite3_error_offset(db: Psqlite3): Integer; external name 'sqlite3_error_offset';  { sqlite3.h:4019 }
function sqlite3_limit(arg1: Psqlite3; id: Integer; newVal: Integer): Integer; external name 'sqlite3_limit';  { sqlite3.h:4087 }
function sqlite3_prepare(db: Psqlite3; zSql: PChar; nByte: Integer; ppStmt: PPsqlite3_stmt; pzTail: PPChar): Integer; external name 'sqlite3_prepare';  { sqlite3.h:4297 }
function sqlite3_prepare_v2(db: Psqlite3; zSql: PChar; nByte: Integer; ppStmt: PPsqlite3_stmt; pzTail: PPChar): Integer; external name 'sqlite3_prepare_v2';  { sqlite3.h:4304 }
function sqlite3_prepare_v3(db: Psqlite3; zSql: PChar; nByte: Integer; prepFlags: Cardinal; ppStmt: PPsqlite3_stmt; pzTail: PPChar): Integer; external name 'sqlite3_prepare_v3';  { sqlite3.h:4311 }
function sqlite3_prepare16(db: Psqlite3; zSql: Pointer; nByte: Integer; ppStmt: PPsqlite3_stmt; pzTail: PPointer): Integer; external name 'sqlite3_prepare16';  { sqlite3.h:4319 }
function sqlite3_prepare16_v2(db: Psqlite3; zSql: Pointer; nByte: Integer; ppStmt: PPsqlite3_stmt; pzTail: PPointer): Integer; external name 'sqlite3_prepare16_v2';  { sqlite3.h:4326 }
function sqlite3_prepare16_v3(db: Psqlite3; zSql: Pointer; nByte: Integer; prepFlags: Cardinal; ppStmt: PPsqlite3_stmt; pzTail: PPointer): Integer; external name 'sqlite3_prepare16_v3';  { sqlite3.h:4333 }
function sqlite3_sql(pStmt: Psqlite3_stmt): PChar; external name 'sqlite3_sql';  { sqlite3.h:4383 }
function sqlite3_expanded_sql(pStmt: Psqlite3_stmt): PChar; external name 'sqlite3_expanded_sql';  { sqlite3.h:4384 }
function sqlite3_stmt_readonly(pStmt: Psqlite3_stmt): Integer; external name 'sqlite3_stmt_readonly';  { sqlite3.h:4436 }
function sqlite3_stmt_isexplain(pStmt: Psqlite3_stmt): Integer; external name 'sqlite3_stmt_isexplain';  { sqlite3.h:4448 }
function sqlite3_stmt_explain(pStmt: Psqlite3_stmt; eMode: Integer): Integer; external name 'sqlite3_stmt_explain';  { sqlite3.h:4483 }
function sqlite3_stmt_busy(arg1: Psqlite3_stmt): Integer; external name 'sqlite3_stmt_busy';  { sqlite3.h:4504 }
function sqlite3_bind_blob(arg1: Psqlite3_stmt; arg2: Integer; arg3: Pointer; n: Integer; arg5: Pointer): Integer; external name 'sqlite3_bind_blob';  { sqlite3.h:4704 }
function sqlite3_bind_blob64(arg1: Psqlite3_stmt; arg2: Integer; arg3: Pointer; arg4: sqlite3_uint64; arg5: Pointer): Integer; external name 'sqlite3_bind_blob64';  { sqlite3.h:4705 }
function sqlite3_bind_double(arg1: Psqlite3_stmt; arg2: Integer; arg3: Double): Integer; external name 'sqlite3_bind_double';  { sqlite3.h:4707 }
function sqlite3_bind_int(arg1: Psqlite3_stmt; arg2: Integer; arg3: Integer): Integer; external name 'sqlite3_bind_int';  { sqlite3.h:4708 }
function sqlite3_bind_int64(arg1: Psqlite3_stmt; arg2: Integer; arg3: sqlite3_int64): Integer; external name 'sqlite3_bind_int64';  { sqlite3.h:4709 }
function sqlite3_bind_null(arg1: Psqlite3_stmt; arg2: Integer): Integer; external name 'sqlite3_bind_null';  { sqlite3.h:4710 }
function sqlite3_bind_text(arg1: Psqlite3_stmt; arg2: Integer; arg3: PChar; arg4: Integer; arg5: Pointer): Integer; external name 'sqlite3_bind_text';  { sqlite3.h:4711 }
function sqlite3_bind_text16(arg1: Psqlite3_stmt; arg2: Integer; arg3: Pointer; arg4: Integer; arg5: Pointer): Integer; external name 'sqlite3_bind_text16';  { sqlite3.h:4712 }
function sqlite3_bind_text64(arg1: Psqlite3_stmt; arg2: Integer; arg3: PChar; arg4: sqlite3_uint64; arg5: Pointer; encoding: Byte): Integer; external name 'sqlite3_bind_text64';  { sqlite3.h:4713 }
function sqlite3_bind_value(arg1: Psqlite3_stmt; arg2: Integer; arg3: Psqlite3_value): Integer; external name 'sqlite3_bind_value';  { sqlite3.h:4715 }
function sqlite3_bind_pointer(arg1: Psqlite3_stmt; arg2: Integer; arg3: Pointer; arg4: PChar; arg5: Pointer): Integer; external name 'sqlite3_bind_pointer';  { sqlite3.h:4716 }
function sqlite3_bind_zeroblob(arg1: Psqlite3_stmt; arg2: Integer; n: Integer): Integer; external name 'sqlite3_bind_zeroblob';  { sqlite3.h:4717 }
function sqlite3_bind_zeroblob64(arg1: Psqlite3_stmt; arg2: Integer; arg3: sqlite3_uint64): Integer; external name 'sqlite3_bind_zeroblob64';  { sqlite3.h:4718 }
function sqlite3_bind_parameter_count(arg1: Psqlite3_stmt): Integer; external name 'sqlite3_bind_parameter_count';  { sqlite3.h:4739 }
function sqlite3_bind_parameter_name(arg1: Psqlite3_stmt; arg2: Integer): PChar; external name 'sqlite3_bind_parameter_name';  { sqlite3.h:4767 }
function sqlite3_bind_parameter_index(arg1: Psqlite3_stmt; zName: PChar): Integer; external name 'sqlite3_bind_parameter_index';  { sqlite3.h:4785 }
function sqlite3_clear_bindings(arg1: Psqlite3_stmt): Integer; external name 'sqlite3_clear_bindings';  { sqlite3.h:4795 }
function sqlite3_column_count(pStmt: Psqlite3_stmt): Integer; external name 'sqlite3_column_count';  { sqlite3.h:4811 }
function sqlite3_column_name(arg1: Psqlite3_stmt; N: Integer): PChar; external name 'sqlite3_column_name';  { sqlite3.h:4840 }
function sqlite3_column_name16(arg1: Psqlite3_stmt; N: Integer): Pointer; external name 'sqlite3_column_name16';  { sqlite3.h:4841 }
function sqlite3_column_database_name(arg1: Psqlite3_stmt; arg2: Integer): PChar; external name 'sqlite3_column_database_name';  { sqlite3.h:4885 }
function sqlite3_column_database_name16(arg1: Psqlite3_stmt; arg2: Integer): Pointer; external name 'sqlite3_column_database_name16';  { sqlite3.h:4886 }
function sqlite3_column_table_name(arg1: Psqlite3_stmt; arg2: Integer): PChar; external name 'sqlite3_column_table_name';  { sqlite3.h:4887 }
function sqlite3_column_table_name16(arg1: Psqlite3_stmt; arg2: Integer): Pointer; external name 'sqlite3_column_table_name16';  { sqlite3.h:4888 }
function sqlite3_column_origin_name(arg1: Psqlite3_stmt; arg2: Integer): PChar; external name 'sqlite3_column_origin_name';  { sqlite3.h:4889 }
function sqlite3_column_origin_name16(arg1: Psqlite3_stmt; arg2: Integer): Pointer; external name 'sqlite3_column_origin_name16';  { sqlite3.h:4890 }
function sqlite3_column_decltype(arg1: Psqlite3_stmt; arg2: Integer): PChar; external name 'sqlite3_column_decltype';  { sqlite3.h:4922 }
function sqlite3_column_decltype16(arg1: Psqlite3_stmt; arg2: Integer): Pointer; external name 'sqlite3_column_decltype16';  { sqlite3.h:4923 }
function sqlite3_step(arg1: Psqlite3_stmt): Integer; external name 'sqlite3_step';  { sqlite3.h:5007 }
function sqlite3_data_count(pStmt: Psqlite3_stmt): Integer; external name 'sqlite3_data_count';  { sqlite3.h:5028 }
function sqlite3_column_blob(arg1: Psqlite3_stmt; iCol: Integer): Pointer; external name 'sqlite3_column_blob';  { sqlite3.h:5275 }
function sqlite3_column_double(arg1: Psqlite3_stmt; iCol: Integer): Double; external name 'sqlite3_column_double';  { sqlite3.h:5276 }
function sqlite3_column_int(arg1: Psqlite3_stmt; iCol: Integer): Integer; external name 'sqlite3_column_int';  { sqlite3.h:5277 }
function sqlite3_column_int64(arg1: Psqlite3_stmt; iCol: Integer): sqlite3_int64; external name 'sqlite3_column_int64';  { sqlite3.h:5278 }
function sqlite3_column_text(arg1: Psqlite3_stmt; iCol: Integer): PByte; external name 'sqlite3_column_text';  { sqlite3.h:5279 }
function sqlite3_column_text16(arg1: Psqlite3_stmt; iCol: Integer): Pointer; external name 'sqlite3_column_text16';  { sqlite3.h:5280 }
function sqlite3_column_value(arg1: Psqlite3_stmt; iCol: Integer): Psqlite3_value; external name 'sqlite3_column_value';  { sqlite3.h:5281 }
function sqlite3_column_bytes(arg1: Psqlite3_stmt; iCol: Integer): Integer; external name 'sqlite3_column_bytes';  { sqlite3.h:5282 }
function sqlite3_column_bytes16(arg1: Psqlite3_stmt; iCol: Integer): Integer; external name 'sqlite3_column_bytes16';  { sqlite3.h:5283 }
function sqlite3_column_type(arg1: Psqlite3_stmt; iCol: Integer): Integer; external name 'sqlite3_column_type';  { sqlite3.h:5284 }
function sqlite3_finalize(pStmt: Psqlite3_stmt): Integer; external name 'sqlite3_finalize';  { sqlite3.h:5312 }
function sqlite3_reset(pStmt: Psqlite3_stmt): Integer; external name 'sqlite3_reset';  { sqlite3.h:5351 }
function sqlite3_create_function(db: Psqlite3; zFunctionName: PChar; nArg: Integer; eTextRep: Integer; pApp: Pointer; xFunc: Pointer; xStep: Pointer; xFinal: Pointer): Integer; external name 'sqlite3_create_function';  { sqlite3.h:5477 }
function sqlite3_create_function16(db: Psqlite3; zFunctionName: Pointer; nArg: Integer; eTextRep: Integer; pApp: Pointer; xFunc: Pointer; xStep: Pointer; xFinal: Pointer): Integer; external name 'sqlite3_create_function16';  { sqlite3.h:5487 }
function sqlite3_create_function_v2(db: Psqlite3; zFunctionName: PChar; nArg: Integer; eTextRep: Integer; pApp: Pointer; xFunc: Pointer; xStep: Pointer; xFinal: Pointer; xDestroy: Pointer): Integer; external name 'sqlite3_create_function_v2';  { sqlite3.h:5497 }
function sqlite3_create_window_function(db: Psqlite3; zFunctionName: PChar; nArg: Integer; eTextRep: Integer; pApp: Pointer; xStep: Pointer; xFinal: Pointer; xValue: Pointer; xInverse: Pointer; xDestroy: Pointer): Integer; external name 'sqlite3_create_window_function';  { sqlite3.h:5508 }
function sqlite3_aggregate_count(arg1: Psqlite3_context): Integer; external name 'sqlite3_aggregate_count';  { sqlite3.h:5641 }
function sqlite3_expired(arg1: Psqlite3_stmt): Integer; external name 'sqlite3_expired';  { sqlite3.h:5642 }
function sqlite3_transfer_bindings(arg1: Psqlite3_stmt; arg2: Psqlite3_stmt): Integer; external name 'sqlite3_transfer_bindings';  { sqlite3.h:5643 }
function sqlite3_global_recover: Integer; external name 'sqlite3_global_recover';  { sqlite3.h:5644 }
procedure sqlite3_thread_cleanup; external name 'sqlite3_thread_cleanup';  { sqlite3.h:5645 }
function sqlite3_memory_alarm(arg1: Pointer; arg2: Pointer; arg3: sqlite3_int64): Integer; external name 'sqlite3_memory_alarm';  { sqlite3.h:5646 }
function sqlite3_value_blob(arg1: Psqlite3_value): Pointer; external name 'sqlite3_value_blob';  { sqlite3.h:5778 }
function sqlite3_value_double(arg1: Psqlite3_value): Double; external name 'sqlite3_value_double';  { sqlite3.h:5779 }
function sqlite3_value_int(arg1: Psqlite3_value): Integer; external name 'sqlite3_value_int';  { sqlite3.h:5780 }
function sqlite3_value_int64(arg1: Psqlite3_value): sqlite3_int64; external name 'sqlite3_value_int64';  { sqlite3.h:5781 }
function sqlite3_value_pointer(arg1: Psqlite3_value; arg2: PChar): Pointer; external name 'sqlite3_value_pointer';  { sqlite3.h:5782 }
function sqlite3_value_text(arg1: Psqlite3_value): PByte; external name 'sqlite3_value_text';  { sqlite3.h:5783 }
function sqlite3_value_text16(arg1: Psqlite3_value): Pointer; external name 'sqlite3_value_text16';  { sqlite3.h:5784 }
function sqlite3_value_text16le(arg1: Psqlite3_value): Pointer; external name 'sqlite3_value_text16le';  { sqlite3.h:5785 }
function sqlite3_value_text16be(arg1: Psqlite3_value): Pointer; external name 'sqlite3_value_text16be';  { sqlite3.h:5786 }
function sqlite3_value_bytes(arg1: Psqlite3_value): Integer; external name 'sqlite3_value_bytes';  { sqlite3.h:5787 }
function sqlite3_value_bytes16(arg1: Psqlite3_value): Integer; external name 'sqlite3_value_bytes16';  { sqlite3.h:5788 }
function sqlite3_value_type(arg1: Psqlite3_value): Integer; external name 'sqlite3_value_type';  { sqlite3.h:5789 }
function sqlite3_value_numeric_type(arg1: Psqlite3_value): Integer; external name 'sqlite3_value_numeric_type';  { sqlite3.h:5790 }
function sqlite3_value_nochange(arg1: Psqlite3_value): Integer; external name 'sqlite3_value_nochange';  { sqlite3.h:5791 }
function sqlite3_value_frombind(arg1: Psqlite3_value): Integer; external name 'sqlite3_value_frombind';  { sqlite3.h:5792 }
function sqlite3_value_encoding(arg1: Psqlite3_value): Integer; external name 'sqlite3_value_encoding';  { sqlite3.h:5814 }
function sqlite3_value_subtype(arg1: Psqlite3_value): Cardinal; external name 'sqlite3_value_subtype';  { sqlite3.h:5832 }
function sqlite3_value_dup(arg1: Psqlite3_value): Psqlite3_value; external name 'sqlite3_value_dup';  { sqlite3.h:5849 }
procedure sqlite3_value_free(arg1: Psqlite3_value); external name 'sqlite3_value_free';  { sqlite3.h:5850 }
function sqlite3_aggregate_context(arg1: Psqlite3_context; nBytes: Integer): Pointer; external name 'sqlite3_aggregate_context';  { sqlite3.h:5895 }
function sqlite3_user_data(arg1: Psqlite3_context): Pointer; external name 'sqlite3_user_data';  { sqlite3.h:5910 }
function sqlite3_context_db_handle(arg1: Psqlite3_context): Psqlite3; external name 'sqlite3_context_db_handle';  { sqlite3.h:5922 }
function sqlite3_get_auxdata(arg1: Psqlite3_context; N: Integer): Pointer; external name 'sqlite3_get_auxdata';  { sqlite3.h:5991 }
procedure sqlite3_set_auxdata(arg1: Psqlite3_context; N: Integer; arg3: Pointer; arg4: Pointer); external name 'sqlite3_set_auxdata';  { sqlite3.h:5992 }
function sqlite3_get_clientdata(arg1: Psqlite3; arg2: PChar): Pointer; external name 'sqlite3_get_clientdata';  { sqlite3.h:6047 }
function sqlite3_set_clientdata(arg1: Psqlite3; arg2: PChar; arg3: Pointer; arg4: Pointer): Integer; external name 'sqlite3_set_clientdata';  { sqlite3.h:6048 }
procedure sqlite3_result_blob(arg1: Psqlite3_context; arg2: Pointer; arg3: Integer; arg4: Pointer); external name 'sqlite3_result_blob';  { sqlite3.h:6215 }
procedure sqlite3_result_blob64(arg1: Psqlite3_context; arg2: Pointer; arg3: sqlite3_uint64; arg4: Pointer); external name 'sqlite3_result_blob64';  { sqlite3.h:6216 }
procedure sqlite3_result_double(arg1: Psqlite3_context; arg2: Double); external name 'sqlite3_result_double';  { sqlite3.h:6218 }
procedure sqlite3_result_error(arg1: Psqlite3_context; arg2: PChar; arg3: Integer); external name 'sqlite3_result_error';  { sqlite3.h:6219 }
procedure sqlite3_result_error16(arg1: Psqlite3_context; arg2: Pointer; arg3: Integer); external name 'sqlite3_result_error16';  { sqlite3.h:6220 }
procedure sqlite3_result_error_toobig(arg1: Psqlite3_context); external name 'sqlite3_result_error_toobig';  { sqlite3.h:6221 }
procedure sqlite3_result_error_nomem(arg1: Psqlite3_context); external name 'sqlite3_result_error_nomem';  { sqlite3.h:6222 }
procedure sqlite3_result_error_code(arg1: Psqlite3_context; arg2: Integer); external name 'sqlite3_result_error_code';  { sqlite3.h:6223 }
procedure sqlite3_result_int(arg1: Psqlite3_context; arg2: Integer); external name 'sqlite3_result_int';  { sqlite3.h:6224 }
procedure sqlite3_result_int64(arg1: Psqlite3_context; arg2: sqlite3_int64); external name 'sqlite3_result_int64';  { sqlite3.h:6225 }
procedure sqlite3_result_null(arg1: Psqlite3_context); external name 'sqlite3_result_null';  { sqlite3.h:6226 }
procedure sqlite3_result_text(arg1: Psqlite3_context; arg2: PChar; arg3: Integer; arg4: Pointer); external name 'sqlite3_result_text';  { sqlite3.h:6227 }
procedure sqlite3_result_text64(arg1: Psqlite3_context; arg2: PChar; arg3: sqlite3_uint64; arg4: Pointer; encoding: Byte); external name 'sqlite3_result_text64';  { sqlite3.h:6228 }
procedure sqlite3_result_text16(arg1: Psqlite3_context; arg2: Pointer; arg3: Integer; arg4: Pointer); external name 'sqlite3_result_text16';  { sqlite3.h:6230 }
procedure sqlite3_result_text16le(arg1: Psqlite3_context; arg2: Pointer; arg3: Integer; arg4: Pointer); external name 'sqlite3_result_text16le';  { sqlite3.h:6231 }
procedure sqlite3_result_text16be(arg1: Psqlite3_context; arg2: Pointer; arg3: Integer; arg4: Pointer); external name 'sqlite3_result_text16be';  { sqlite3.h:6232 }
procedure sqlite3_result_value(arg1: Psqlite3_context; arg2: Psqlite3_value); external name 'sqlite3_result_value';  { sqlite3.h:6233 }
procedure sqlite3_result_pointer(arg1: Psqlite3_context; arg2: Pointer; arg3: PChar; arg4: Pointer); external name 'sqlite3_result_pointer';  { sqlite3.h:6234 }
procedure sqlite3_result_zeroblob(arg1: Psqlite3_context; n: Integer); external name 'sqlite3_result_zeroblob';  { sqlite3.h:6235 }
function sqlite3_result_zeroblob64(arg1: Psqlite3_context; n: sqlite3_uint64): Integer; external name 'sqlite3_result_zeroblob64';  { sqlite3.h:6236 }
procedure sqlite3_result_subtype(arg1: Psqlite3_context; arg2: Cardinal); external name 'sqlite3_result_subtype';  { sqlite3.h:6265 }
function sqlite3_create_collation(arg1: Psqlite3; zName: PChar; eTextRep: Integer; pArg: Pointer; xCompare: Pointer): Integer; external name 'sqlite3_create_collation';  { sqlite3.h:6348 }
function sqlite3_create_collation_v2(arg1: Psqlite3; zName: PChar; eTextRep: Integer; pArg: Pointer; xCompare: Pointer; xDestroy: Pointer): Integer; external name 'sqlite3_create_collation_v2';  { sqlite3.h:6355 }
function sqlite3_create_collation16(arg1: Psqlite3; zName: Pointer; eTextRep: Integer; pArg: Pointer; xCompare: Pointer): Integer; external name 'sqlite3_create_collation16';  { sqlite3.h:6363 }
function sqlite3_collation_needed(arg1: Psqlite3; arg2: Pointer; arg3: Pointer): Integer; external name 'sqlite3_collation_needed';  { sqlite3.h:6398 }
function sqlite3_collation_needed16(arg1: Psqlite3; arg2: Pointer; arg3: Pointer): Integer; external name 'sqlite3_collation_needed16';  { sqlite3.h:6403 }
function sqlite3_sleep(arg1: Integer): Integer; external name 'sqlite3_sleep';  { sqlite3.h:6443 }
function sqlite3_win32_set_directory(type_: UInt64; zValue: Pointer): Integer; external name 'sqlite3_win32_set_directory';  { sqlite3.h:6559 }
function sqlite3_win32_set_directory8(type_: UInt64; zValue: PChar): Integer; external name 'sqlite3_win32_set_directory8';  { sqlite3.h:6563 }
function sqlite3_win32_set_directory16(type_: UInt64; zValue: Pointer): Integer; external name 'sqlite3_win32_set_directory16';  { sqlite3.h:6564 }
function sqlite3_get_autocommit(arg1: Psqlite3): Integer; external name 'sqlite3_get_autocommit';  { sqlite3.h:6597 }
function sqlite3_db_handle(arg1: Psqlite3_stmt): Psqlite3; external name 'sqlite3_db_handle';  { sqlite3.h:6610 }
function sqlite3_db_name(db: Psqlite3; N: Integer): PChar; external name 'sqlite3_db_name';  { sqlite3.h:6632 }
function sqlite3_db_filename(db: Psqlite3; zDbName: PChar): sqlite3_filename; external name 'sqlite3_db_filename';  { sqlite3.h:6664 }
function sqlite3_db_readonly(db: Psqlite3; zDbName: PChar): Integer; external name 'sqlite3_db_readonly';  { sqlite3.h:6674 }
function sqlite3_txn_state(arg1: Psqlite3; zSchema: PChar): Integer; external name 'sqlite3_txn_state';  { sqlite3.h:6692 }
function sqlite3_next_stmt(pDb: Psqlite3; pStmt: Psqlite3_stmt): Psqlite3_stmt; external name 'sqlite3_next_stmt';  { sqlite3.h:6741 }
function sqlite3_commit_hook(arg1: Psqlite3; arg2: Pointer; arg3: Pointer): Pointer; external name 'sqlite3_commit_hook';  { sqlite3.h:6790 }
function sqlite3_rollback_hook(arg1: Psqlite3; arg2: Pointer; arg3: Pointer): Pointer; external name 'sqlite3_rollback_hook';  { sqlite3.h:6791 }
function sqlite3_autovacuum_pages(db: Psqlite3; arg2: Pointer; arg3: Pointer; arg4: Pointer): Integer; external name 'sqlite3_autovacuum_pages';  { sqlite3.h:6851 }
function sqlite3_update_hook(arg1: Psqlite3; arg2: Pointer; arg3: Pointer): Pointer; external name 'sqlite3_update_hook';  { sqlite3.h:6908 }
function sqlite3_enable_shared_cache(arg1: Integer): Integer; external name 'sqlite3_enable_shared_cache';  { sqlite3.h:6958 }
function sqlite3_release_memory(arg1: Integer): Integer; external name 'sqlite3_release_memory';  { sqlite3.h:6974 }
function sqlite3_db_release_memory(arg1: Psqlite3): Integer; external name 'sqlite3_db_release_memory';  { sqlite3.h:6988 }
function sqlite3_soft_heap_limit64(N: sqlite3_int64): sqlite3_int64; external name 'sqlite3_soft_heap_limit64';  { sqlite3.h:7054 }
function sqlite3_hard_heap_limit64(N: sqlite3_int64): sqlite3_int64; external name 'sqlite3_hard_heap_limit64';  { sqlite3.h:7055 }
procedure sqlite3_soft_heap_limit(N: Integer); external name 'sqlite3_soft_heap_limit';  { sqlite3.h:7066 }
function sqlite3_table_column_metadata(db: Psqlite3; zDbName: PChar; zTableName: PChar; zColumnName: PChar; pzDataType: PPChar; pzCollSeq: PPChar; pNotNull: PInteger; pPrimaryKey: PInteger; pAutoinc: PInteger): Integer; external name 'sqlite3_table_column_metadata';  { sqlite3.h:7138 }
function sqlite3_load_extension(db: Psqlite3; zFile: PChar; zProc: PChar; pzErrMsg: PPChar): Integer; external name 'sqlite3_load_extension';  { sqlite3.h:7194 }
function sqlite3_enable_load_extension(db: Psqlite3; onoff: Integer): Integer; external name 'sqlite3_enable_load_extension';  { sqlite3.h:7226 }
function sqlite3_auto_extension(xEntryPoint: Pointer): Integer; external name 'sqlite3_auto_extension';  { sqlite3.h:7264 }
function sqlite3_cancel_auto_extension(xEntryPoint: Pointer): Integer; external name 'sqlite3_cancel_auto_extension';  { sqlite3.h:7276 }
procedure sqlite3_reset_auto_extension; external name 'sqlite3_reset_auto_extension';  { sqlite3.h:7284 }
function sqlite3_create_module(db: Psqlite3; zName: PChar; p: Psqlite3_module; pClientData: Pointer): Integer; external name 'sqlite3_create_module';  { sqlite3.h:7583 }
function sqlite3_create_module_v2(db: Psqlite3; zName: PChar; p: Psqlite3_module; pClientData: Pointer; xDestroy: Pointer): Integer; external name 'sqlite3_create_module_v2';  { sqlite3.h:7589 }
function sqlite3_drop_modules(db: Psqlite3; azKeep: PPChar): Integer; external name 'sqlite3_drop_modules';  { sqlite3.h:7609 }
function sqlite3_declare_vtab(arg1: Psqlite3; zSQL: PChar): Integer; external name 'sqlite3_declare_vtab';  { sqlite3.h:7669 }
function sqlite3_overload_function(arg1: Psqlite3; zFuncName: PChar; nArg: Integer): Integer; external name 'sqlite3_overload_function';  { sqlite3.h:7688 }
function sqlite3_blob_open(arg1: Psqlite3; zDb: PChar; zTable: PChar; zColumn: PChar; iRow: sqlite3_int64; flags: Integer; ppBlob: PPsqlite3_blob): Integer; external name 'sqlite3_blob_open';  { sqlite3.h:7787 }
function sqlite3_blob_reopen(arg1: Psqlite3_blob; arg2: sqlite3_int64): Integer; external name 'sqlite3_blob_reopen';  { sqlite3.h:7820 }
function sqlite3_blob_close(arg1: Psqlite3_blob): Integer; external name 'sqlite3_blob_close';  { sqlite3.h:7843 }
function sqlite3_blob_bytes(arg1: Psqlite3_blob): Integer; external name 'sqlite3_blob_bytes';  { sqlite3.h:7859 }
function sqlite3_blob_read(arg1: Psqlite3_blob; Z: Pointer; N: Integer; iOffset: Integer): Integer; external name 'sqlite3_blob_read';  { sqlite3.h:7888 }
function sqlite3_blob_write(arg1: Psqlite3_blob; z: Pointer; n: Integer; iOffset: Integer): Integer; external name 'sqlite3_blob_write';  { sqlite3.h:7930 }
function sqlite3_vfs_find(zVfsName: PChar): Psqlite3_vfs; external name 'sqlite3_vfs_find';  { sqlite3.h:7961 }
function sqlite3_vfs_register(arg1: Psqlite3_vfs; makeDflt: Integer): Integer; external name 'sqlite3_vfs_register';  { sqlite3.h:7962 }
function sqlite3_vfs_unregister(arg1: Psqlite3_vfs): Integer; external name 'sqlite3_vfs_unregister';  { sqlite3.h:7963 }
function sqlite3_mutex_alloc(arg1: Integer): Psqlite3_mutex; external name 'sqlite3_mutex_alloc';  { sqlite3.h:8081 }
procedure sqlite3_mutex_free(arg1: Psqlite3_mutex); external name 'sqlite3_mutex_free';  { sqlite3.h:8082 }
procedure sqlite3_mutex_enter(arg1: Psqlite3_mutex); external name 'sqlite3_mutex_enter';  { sqlite3.h:8083 }
function sqlite3_mutex_try(arg1: Psqlite3_mutex): Integer; external name 'sqlite3_mutex_try';  { sqlite3.h:8084 }
procedure sqlite3_mutex_leave(arg1: Psqlite3_mutex); external name 'sqlite3_mutex_leave';  { sqlite3.h:8085 }
function sqlite3_mutex_held(arg1: Psqlite3_mutex): Integer; external name 'sqlite3_mutex_held';  { sqlite3.h:8195 }
function sqlite3_mutex_notheld(arg1: Psqlite3_mutex): Integer; external name 'sqlite3_mutex_notheld';  { sqlite3.h:8196 }
function sqlite3_db_mutex(arg1: Psqlite3): Psqlite3_mutex; external name 'sqlite3_db_mutex';  { sqlite3.h:8240 }
function sqlite3_file_control(arg1: Psqlite3; zDbName: PChar; op: Integer; arg4: Pointer): Integer; external name 'sqlite3_file_control';  { sqlite3.h:8283 }
function sqlite3_test_control(op: Integer): Integer; external name 'sqlite3_test_control'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { sqlite3.h:8302 }
function sqlite3_keyword_count: Integer; external name 'sqlite3_keyword_count';  { sqlite3.h:8399 }
function sqlite3_keyword_name(arg1: Integer; arg2: PPChar; arg3: PInteger): Integer; external name 'sqlite3_keyword_name';  { sqlite3.h:8400 }
function sqlite3_keyword_check(arg1: PChar; arg2: Integer): Integer; external name 'sqlite3_keyword_check';  { sqlite3.h:8401 }
function sqlite3_str_new(arg1: Psqlite3): Psqlite3_str; external name 'sqlite3_str_new';  { sqlite3.h:8446 }
function sqlite3_str_finish(arg1: Psqlite3_str): PChar; external name 'sqlite3_str_finish';  { sqlite3.h:8461 }
procedure sqlite3_str_appendf(arg1: Psqlite3_str; zFormat: PChar); external name 'sqlite3_str_appendf'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { sqlite3.h:8495 }
procedure sqlite3_str_vappendf(arg1: Psqlite3_str; zFormat: PChar; arg3: va_list); external name 'sqlite3_str_vappendf';  { sqlite3.h:8496 }
procedure sqlite3_str_append(arg1: Psqlite3_str; zIn: PChar; N: Integer); external name 'sqlite3_str_append';  { sqlite3.h:8497 }
procedure sqlite3_str_appendall(arg1: Psqlite3_str; zIn: PChar); external name 'sqlite3_str_appendall';  { sqlite3.h:8498 }
procedure sqlite3_str_appendchar(arg1: Psqlite3_str; N: Integer; C: Byte); external name 'sqlite3_str_appendchar';  { sqlite3.h:8499 }
procedure sqlite3_str_reset(arg1: Psqlite3_str); external name 'sqlite3_str_reset';  { sqlite3.h:8500 }
function sqlite3_str_errcode(arg1: Psqlite3_str): Integer; external name 'sqlite3_str_errcode';  { sqlite3.h:8531 }
function sqlite3_str_length(arg1: Psqlite3_str): Integer; external name 'sqlite3_str_length';  { sqlite3.h:8532 }
function sqlite3_str_value(arg1: Psqlite3_str): PChar; external name 'sqlite3_str_value';  { sqlite3.h:8533 }
function sqlite3_status(op: Integer; pCurrent: PInteger; pHighwater: PInteger; resetFlag: Integer): Integer; external name 'sqlite3_status';  { sqlite3.h:8561 }
function sqlite3_status64(op: Integer; pCurrent: Psqlite3_int64; pHighwater: Psqlite3_int64; resetFlag: Integer): Integer; external name 'sqlite3_status64';  { sqlite3.h:8562 }
function sqlite3_db_status(arg1: Psqlite3; op: Integer; pCur: PInteger; pHiwtr: PInteger; resetFlg: Integer): Integer; external name 'sqlite3_db_status';  { sqlite3.h:8671 }
function sqlite3_stmt_status(arg1: Psqlite3_stmt; op: Integer; resetFlg: Integer): Integer; external name 'sqlite3_stmt_status';  { sqlite3.h:8824 }
function sqlite3_backup_init(pDest: Psqlite3; zDestName: PChar; pSource: Psqlite3; zSourceName: PChar): Psqlite3_backup; external name 'sqlite3_backup_init';  { sqlite3.h:9326 }
function sqlite3_backup_step(p: Psqlite3_backup; nPage: Integer): Integer; external name 'sqlite3_backup_step';  { sqlite3.h:9332 }
function sqlite3_backup_finish(p: Psqlite3_backup): Integer; external name 'sqlite3_backup_finish';  { sqlite3.h:9333 }
function sqlite3_backup_remaining(p: Psqlite3_backup): Integer; external name 'sqlite3_backup_remaining';  { sqlite3.h:9334 }
function sqlite3_backup_pagecount(p: Psqlite3_backup): Integer; external name 'sqlite3_backup_pagecount';  { sqlite3.h:9335 }
function sqlite3_unlock_notify(pBlocked: Psqlite3; xNotify: Pointer; pNotifyArg: Pointer): Integer; external name 'sqlite3_unlock_notify';  { sqlite3.h:9452 }
function sqlite3_stricmp(arg1: PChar; arg2: PChar): Integer; external name 'sqlite3_stricmp';  { sqlite3.h:9467 }
function sqlite3_strnicmp(arg1: PChar; arg2: PChar; arg3: Integer): Integer; external name 'sqlite3_strnicmp';  { sqlite3.h:9468 }
function sqlite3_strglob(zGlob: PChar; zStr: PChar): Integer; external name 'sqlite3_strglob';  { sqlite3.h:9485 }
function sqlite3_strlike(zGlob: PChar; zStr: PChar; cEsc: Cardinal): Integer; external name 'sqlite3_strlike';  { sqlite3.h:9508 }
procedure sqlite3_log(iErrCode: Integer; zFormat: PChar); external name 'sqlite3_log'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { sqlite3.h:9531 }
function sqlite3_wal_hook(arg1: Psqlite3; arg2: Pointer; arg3: Pointer): Pointer; external name 'sqlite3_wal_hook';  { sqlite3.h:9568 }
function sqlite3_wal_autocheckpoint(db: Psqlite3; N: Integer): Integer; external name 'sqlite3_wal_autocheckpoint';  { sqlite3.h:9603 }
function sqlite3_wal_checkpoint(db: Psqlite3; zDb: PChar): Integer; external name 'sqlite3_wal_checkpoint';  { sqlite3.h:9625 }
function sqlite3_wal_checkpoint_v2(db: Psqlite3; zDb: PChar; eMode: Integer; pnLog: PInteger; pnCkpt: PInteger): Integer; external name 'sqlite3_wal_checkpoint_v2';  { sqlite3.h:9719 }
function sqlite3_vtab_config(arg1: Psqlite3; op: Integer): Integer; external name 'sqlite3_vtab_config'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { sqlite3.h:9759 }
function sqlite3_vtab_on_conflict(arg1: Psqlite3): Integer; external name 'sqlite3_vtab_on_conflict';  { sqlite3.h:9847 }
function sqlite3_vtab_nochange(arg1: Psqlite3_context): Integer; external name 'sqlite3_vtab_nochange';  { sqlite3.h:9873 }
function sqlite3_vtab_collation(arg1: Psqlite3_index_info; arg2: Integer): PChar; external name 'sqlite3_vtab_collation';  { sqlite3.h:9908 }
function sqlite3_vtab_distinct(arg1: Psqlite3_index_info): Integer; external name 'sqlite3_vtab_distinct';  { sqlite3.h:9981 }
function sqlite3_vtab_in(arg1: Psqlite3_index_info; iCons: Integer; bHandle: Integer): Integer; external name 'sqlite3_vtab_in';  { sqlite3.h:10054 }
function sqlite3_vtab_in_first(pVal: Psqlite3_value; ppOut: PPsqlite3_value): Integer; external name 'sqlite3_vtab_in_first';  { sqlite3.h:10101 }
function sqlite3_vtab_in_next(pVal: Psqlite3_value; ppOut: PPsqlite3_value): Integer; external name 'sqlite3_vtab_in_next';  { sqlite3.h:10102 }
function sqlite3_vtab_rhs_value(arg1: Psqlite3_index_info; arg2: Integer; ppVal: PPsqlite3_value): Integer; external name 'sqlite3_vtab_rhs_value';  { sqlite3.h:10144 }
function sqlite3_stmt_scanstatus(pStmt: Psqlite3_stmt; idx: Integer; iScanStatusOp: Integer; pOut: Pointer): Integer; external name 'sqlite3_stmt_scanstatus';  { sqlite3.h:10273 }
function sqlite3_stmt_scanstatus_v2(pStmt: Psqlite3_stmt; idx: Integer; iScanStatusOp: Integer; flags: Integer; pOut: Pointer): Integer; external name 'sqlite3_stmt_scanstatus_v2';  { sqlite3.h:10279 }
procedure sqlite3_stmt_scanstatus_reset(arg1: Psqlite3_stmt); external name 'sqlite3_stmt_scanstatus_reset';  { sqlite3.h:10302 }
function sqlite3_db_cacheflush(arg1: Psqlite3): Integer; external name 'sqlite3_db_cacheflush';  { sqlite3.h:10335 }
function sqlite3_system_errno(arg1: Psqlite3): Integer; external name 'sqlite3_system_errno';  { sqlite3.h:10465 }
function sqlite3_snapshot_get(db: Psqlite3; zSchema: PChar; ppSnapshot: PPsqlite3_snapshot): Integer; external name 'sqlite3_snapshot_get';  { sqlite3.h:10534 }
function sqlite3_snapshot_open(db: Psqlite3; zSchema: PChar; pSnapshot: Psqlite3_snapshot): Integer; external name 'sqlite3_snapshot_open';  { sqlite3.h:10583 }
procedure sqlite3_snapshot_free(arg1: Psqlite3_snapshot); external name 'sqlite3_snapshot_free';  { sqlite3.h:10600 }
function sqlite3_snapshot_cmp(p1: Psqlite3_snapshot; p2: Psqlite3_snapshot): Integer; external name 'sqlite3_snapshot_cmp';  { sqlite3.h:10627 }
function sqlite3_snapshot_recover(db: Psqlite3; zDb: PChar): Integer; external name 'sqlite3_snapshot_recover';  { sqlite3.h:10655 }
function sqlite3_serialize(db: Psqlite3; zSchema: PChar; piSize: Psqlite3_int64; mFlags: Cardinal): PByte; external name 'sqlite3_serialize';  { sqlite3.h:10700 }
function sqlite3_deserialize(db: Psqlite3; zSchema: PChar; pData: PByte; szDb: sqlite3_int64; szBuf: sqlite3_int64; mFlags: Cardinal): Integer; external name 'sqlite3_deserialize';  { sqlite3.h:10766 }
function sqlite3_rtree_geometry_callback(db: Psqlite3; zGeom: PChar; xGeom: Pointer; pContext: Pointer): Integer; external name 'sqlite3_rtree_geometry_callback';  { sqlite3.h:10866 }
function sqlite3_rtree_query_callback(db: Psqlite3; zQueryFunc: PChar; xQueryFunc: Pointer; pContext: Pointer; xDestructor: Pointer): Integer; external name 'sqlite3_rtree_query_callback';  { sqlite3.h:10892 }

implementation

end.
