{ DO NOT EDIT — generated by pascal_bindgen (Blaise dialect).
  source: /tmp/win_demo.h
  library: kernel32   -- informational; Blaise resolves externs at link time
}

unit win_demo;

interface

type
  PDWORD = ^DWORD;
  PFILETIME = ^FILETIME;
  HANDLE = Pointer;  { win_demo.h:3 }
  DWORD = Cardinal;  { win_demo.h:4 }
  BOOL = Integer;  { win_demo.h:5 }
  _FILETIME = record  { win_demo.h:6 }
    dwLowDateTime: DWORD;
    dwHighDateTime: DWORD;
  end;
  FILETIME = _FILETIME;  { win_demo.h:9 }

function GetStdHandle(nStdHandle: DWORD): HANDLE; external name 'GetStdHandle';  { win_demo.h:11 }
function WriteFile_(h: HANDLE; buf: Pointer; n: DWORD; written: PDWORD; ov: Pointer): BOOL; external name 'WriteFile';  { win_demo.h:12 }
procedure GetSystemTimeAsFileTime(lpSystemTimeAsFileTime: PFILETIME); external name 'GetSystemTimeAsFileTime';  { win_demo.h:13 }
procedure Sleep_(ms: DWORD); external name 'Sleep';  { win_demo.h:14 }
procedure ExitProcess(code: DWORD); external name 'ExitProcess';  { win_demo.h:15 }

implementation

end.
