{ DO NOT EDIT — generated by pascal_bindgen (Blaise dialect).
  source: examples/blaise-windows/win_gui.h
  library: user32   -- informational; Blaise resolves externs at link time
}

unit win_gui;

interface

type
  PINITCOMMONCONTROLSEX = ^INITCOMMONCONTROLSEX;
  PMSG = ^MSG;
  PPAINTSTRUCT = ^PAINTSTRUCT;
  PRECT = ^RECT;
  PWCHAR = ^WCHAR;
  PWNDCLASSEXW = ^WNDCLASSEXW;
  PWord = ^Word;
  HANDLE = Pointer;  { win_gui.h:4 }
  HWND = Pointer;  { win_gui.h:5 }
  HMENU = Pointer;  { win_gui.h:6 }
  HINSTANCE = Pointer;  { win_gui.h:7 }
  HICON = Pointer;  { win_gui.h:8 }
  HCURSOR = Pointer;  { win_gui.h:9 }
  HBRUSH = Pointer;  { win_gui.h:10 }
  HDC = Pointer;  { win_gui.h:11 }
  HGDIOBJ = Pointer;  { win_gui.h:12 }
  WCHAR = Word;  { win_gui.h:13 }
  LPCWSTR = ^Word;  { win_gui.h:14 }
  LPWSTR = ^WCHAR;  { win_gui.h:15 }
  UINT = Cardinal;  { win_gui.h:16 }
  DWORD = Cardinal;  { win_gui.h:17 }
  BOOL = Integer;  { win_gui.h:18 }
  ULONG_PTR = UInt64;  { win_gui.h:19 }
  WPARAM = ULONG_PTR;  { win_gui.h:20 }
  LPARAM = Int64;  { win_gui.h:21 }
  LRESULT = Int64;  { win_gui.h:22 }
  UINT_PTR = UInt64;  { win_gui.h:23 }
  LONG = Integer;  { win_gui.h:24 }
  ATOM = Word;  { win_gui.h:26 }
  WNDPROC = function(arg1: Pointer; arg2: Cardinal; arg3: UInt64; arg4: Int64): Int64;  { win_gui.h:28 }
  TIMERPROC = procedure(arg1: Pointer; arg2: Cardinal; arg3: UInt64; arg4: Cardinal);  { win_gui.h:29 }
  tagRECT = record  { win_gui.h:31 }
    left: LONG;
    top: LONG;
    right: LONG;
    bottom: LONG;
  end;
  RECT = tagRECT;  { win_gui.h:36 }
  tagPOINT = record  { win_gui.h:38 }
    x: LONG;
    y: LONG;
  end;
  POINT = tagPOINT;  { win_gui.h:41 }
  tagMSG = record  { win_gui.h:43 }
    hwnd: HWND;
    message: UINT;
    wParam: WPARAM;
    lParam: LPARAM;
    time: DWORD;
    pt: POINT;
    lPrivate: DWORD;
  end;
  MSG = tagMSG;  { win_gui.h:51 }
  tagPAINTSTRUCT = record  { win_gui.h:53 }
    hdc: HDC;
    fErase: BOOL;
    rcPaint: RECT;
    fRestore: BOOL;
    fIncUpdate: BOOL;
    rgbReserved: array[0..31] of Byte;
  end;
  PAINTSTRUCT = tagPAINTSTRUCT;  { win_gui.h:60 }
  tagWNDCLASSEXW = record  { win_gui.h:62 }
    cbSize: UINT;
    style: UINT;
    lpfnWndProc: WNDPROC;
    cbClsExtra: Integer;
    cbWndExtra: Integer;
    hInstance: HINSTANCE;
    hIcon: HICON;
    hCursor: HCURSOR;
    hbrBackground: HBRUSH;
    lpszMenuName: LPCWSTR;
    lpszClassName: LPCWSTR;
    hIconSm: HICON;
  end;
  WNDCLASSEXW = tagWNDCLASSEXW;  { win_gui.h:75 }
  tagINITCOMMONCONTROLSEX = record  { win_gui.h:94 }
    dwSize: DWORD;
    dwICC: DWORD;
  end;
  INITCOMMONCONTROLSEX = tagINITCOMMONCONTROLSEX;  { win_gui.h:97 }

const
  WS_OVERLAPPEDWINDOW = $00CF0000;  { win_gui.h:77 }
  WS_VISIBLE = $10000000;  { win_gui.h:78 }
  WS_CHILD = $40000000;  { win_gui.h:79 }
  BS_DEFPUSHBUTTON = $00000001;  { win_gui.h:80 }
  SW_SHOW = 5;  { win_gui.h:81 }
  WM_DESTROY = $0002;  { win_gui.h:82 }
  WM_PAINT = $000F;  { win_gui.h:83 }
  WM_CLOSE = $0010;  { win_gui.h:84 }
  WM_TIMER = $0113;  { win_gui.h:85 }
  WM_COMMAND = $0111;  { win_gui.h:86 }
  BN_CLICKED = 0;  { win_gui.h:87 }
  IDC_ARROW = 32512;  { win_gui.h:88 }
  COLOR_WINDOW = 5;  { win_gui.h:90 }
  ICC_STANDARD_CLASSES = $4000;  { win_gui.h:92 }

function InitCommonControlsEx_(picce: PINITCOMMONCONTROLSEX): BOOL; external name 'InitCommonControlsEx';  { win_gui.h:99 }
function RegisterClassExW(lpWndClass: PWNDCLASSEXW): ATOM; external name 'RegisterClassExW';  { win_gui.h:101 }
function CreateWindowExW(exStyle: DWORD; cls: LPCWSTR; title: LPCWSTR; style: DWORD; x: Integer; y: Integer; w: Integer; h: Integer; parent: HWND; menu: HMENU; hInst: HINSTANCE; lpParam: Pointer): HWND; external name 'CreateWindowExW';  { win_gui.h:102 }
function DefWindowProcW(h: HWND; m: UINT; w: WPARAM; l: LPARAM): LRESULT; external name 'DefWindowProcW';  { win_gui.h:105 }
function ShowWindow(h: HWND; nCmdShow: Integer): BOOL; external name 'ShowWindow';  { win_gui.h:106 }
function UpdateWindow(h: HWND): BOOL; external name 'UpdateWindow';  { win_gui.h:107 }
function InvalidateRect(h: HWND; r: PRECT; erase: BOOL): BOOL; external name 'InvalidateRect';  { win_gui.h:108 }
function GetMessageW(msg: PMSG; h: HWND; min: UINT; max: UINT): Integer; external name 'GetMessageW';  { win_gui.h:109 }
function TranslateMessage(msg: PMSG): BOOL; external name 'TranslateMessage';  { win_gui.h:110 }
function DispatchMessageW(msg: PMSG): LRESULT; external name 'DispatchMessageW';  { win_gui.h:111 }
procedure PostQuitMessage(nExitCode: Integer); external name 'PostQuitMessage';  { win_gui.h:112 }
function DestroyWindow(h: HWND): BOOL; external name 'DestroyWindow';  { win_gui.h:113 }
function BeginPaint(h: HWND; ps: PPAINTSTRUCT): HDC; external name 'BeginPaint';  { win_gui.h:114 }
function EndPaint(h: HWND; ps: PPAINTSTRUCT): BOOL; external name 'EndPaint';  { win_gui.h:115 }
function TextOutW(dc: HDC; x: Integer; y: Integer; s: LPCWSTR; n: Integer): BOOL; external name 'TextOutW';  { win_gui.h:116 }
function SetWindowTextW(h: HWND; s: LPCWSTR): BOOL; external name 'SetWindowTextW';  { win_gui.h:117 }
function SetTimer(h: HWND; id: UINT_PTR; period: UINT; cb: TIMERPROC): UINT_PTR; external name 'SetTimer';  { win_gui.h:118 }
function KillTimer(h: HWND; id: UINT_PTR): BOOL; external name 'KillTimer';  { win_gui.h:119 }
function LoadCursorW(h: HINSTANCE; name: LPCWSTR): HCURSOR; external name 'LoadCursorW';  { win_gui.h:120 }
function MessageBoxW(hwnd: HWND; text: LPCWSTR; caption: LPCWSTR; type_: UINT): Integer; external name 'MessageBoxW';  { win_gui.h:121 }

implementation

end.
