{ DO NOT EDIT — generated by pascal_bindgen (Blaise dialect).
  source: /usr/include/zlib.h
  library: libz   -- informational; Blaise resolves externs at link time
}

unit zlib_blaise;

interface

type
  z_size_t = size_t;  { zconf.h:255 }
  uInt = Cardinal;  { zconf.h:403 }
  uLong = UInt64;  { zconf.h:404 }
  Bytef = Byte;  { zconf.h:410 }
  charf = AnsiChar;  { zconf.h:412 }
  intf = Integer;  { zconf.h:413 }
  uIntf = uInt;  { zconf.h:414 }
  uLongf = uLong;  { zconf.h:415 }
  voidpc = Pointer;  { zconf.h:418 }
  voidpf = Pointer;  { zconf.h:419 }
  voidp = Pointer;  { zconf.h:420 }
  z_crc_t = Cardinal;  { zconf.h:439 }
  alloc_func = function(arg1: Pointer; arg2: Cardinal; arg3: Cardinal): Pointer;  { zlib.h:81 }
  free_func = procedure(arg1: Pointer; arg2: Pointer);  { zlib.h:82 }
  internal_state = record  { zlib.h:84 }
  end;
  z_stream_s = record  { zlib.h:86 }
    next_in: ^Bytef;
    avail_in: uInt;
    total_in: uLong;
    next_out: ^Bytef;
    avail_out: uInt;
    total_out: uLong;
    msg: PChar;
    state: ^internal_state;
    zalloc: alloc_func;
    zfree: free_func;
    opaque: voidpf;
    data_type: Integer;
    adler: uLong;
    reserved: uLong;
  end;
  z_stream = z_stream_s;  { zlib.h:106 }
  z_streamp = ^z_stream;  { zlib.h:108 }
  gz_header_s = record  { zlib.h:114 }
    text: Integer;
    time: uLong;
    xflags: Integer;
    os: Integer;
    extra: ^Bytef;
    extra_len: uInt;
    extra_max: uInt;
    name: ^Bytef;
    name_max: uInt;
    comment: ^Bytef;
    comm_max: uInt;
    hcrc: Integer;
    done: Integer;
  end;
  gz_header = gz_header_s;  { zlib.h:129 }
  gz_headerp = ^gz_header;  { zlib.h:131 }
  in_func = function(arg1: Pointer; arg2: ^^Byte): Cardinal;  { zlib.h:1097 }
  out_func = function(arg1: Pointer; arg2: ^Byte; arg3: Cardinal): Integer;  { zlib.h:1099 }
  gzFile_s = record  { zlib.h:1305 }
  end;
  gzFile = ^gzFile_s;  { zlib.h:1305 }

const
  MAX_MEM_LEVEL = 9;  { zconf.h:267 }
  MAX_WBITS = 15;  { zconf.h:277 }
  ZLIB_VERNUM = $1300;  { zlib.h:41 }
  ZLIB_VER_MAJOR = 1;  { zlib.h:42 }
  ZLIB_VER_MINOR = 3;  { zlib.h:43 }
  ZLIB_VER_REVISION = 0;  { zlib.h:44 }
  ZLIB_VER_SUBREVISION = 0;  { zlib.h:45 }
  Z_NO_FLUSH = 0;  { zlib.h:168 }
  Z_PARTIAL_FLUSH = 1;  { zlib.h:169 }
  Z_SYNC_FLUSH = 2;  { zlib.h:170 }
  Z_FULL_FLUSH = 3;  { zlib.h:171 }
  Z_FINISH = 4;  { zlib.h:172 }
  Z_BLOCK = 5;  { zlib.h:173 }
  Z_TREES = 6;  { zlib.h:174 }
  Z_OK = 0;  { zlib.h:177 }
  Z_STREAM_END = 1;  { zlib.h:178 }
  Z_NEED_DICT = 2;  { zlib.h:179 }
  Z_NO_COMPRESSION = 0;  { zlib.h:190 }
  Z_BEST_SPEED = 1;  { zlib.h:191 }
  Z_BEST_COMPRESSION = 9;  { zlib.h:192 }
  Z_FILTERED = 1;  { zlib.h:196 }
  Z_HUFFMAN_ONLY = 2;  { zlib.h:197 }
  Z_RLE = 3;  { zlib.h:198 }
  Z_FIXED = 4;  { zlib.h:199 }
  Z_DEFAULT_STRATEGY = 0;  { zlib.h:200 }
  Z_BINARY = 0;  { zlib.h:203 }
  Z_TEXT = 1;  { zlib.h:204 }
  Z_UNKNOWN = 2;  { zlib.h:206 }
  Z_DEFLATED = 8;  { zlib.h:209 }
  Z_NULL = 0;  { zlib.h:212 }

function zlibVersion: PChar; external name 'zlibVersion';  { zlib.h:220 }
function deflate(strm: z_streamp; flush: Integer): Integer; external name 'deflate';  { zlib.h:250 }
function deflateEnd(strm: z_streamp): Integer; external name 'deflateEnd';  { zlib.h:363 }
function inflate(strm: z_streamp; flush: Integer): Integer; external name 'inflate';  { zlib.h:401 }
function inflateEnd(strm: z_streamp): Integer; external name 'inflateEnd';  { zlib.h:521 }
function deflateSetDictionary(strm: z_streamp; dictionary: ^Byte; dictLength: uInt): Integer; external name 'deflateSetDictionary';  { zlib.h:611 }
function deflateGetDictionary(strm: z_streamp; dictionary: ^Bytef; dictLength: ^uInt): Integer; external name 'deflateGetDictionary';  { zlib.h:655 }
function deflateCopy(dest: z_streamp; source: z_streamp): Integer; external name 'deflateCopy';  { zlib.h:677 }
function deflateReset(strm: z_streamp): Integer; external name 'deflateReset';  { zlib.h:695 }
function deflateParams(strm: z_streamp; level: Integer; strategy: Integer): Integer; external name 'deflateParams';  { zlib.h:706 }
function deflateTune(strm: z_streamp; good_length: Integer; max_lazy: Integer; nice_length: Integer; max_chain: Integer): Integer; external name 'deflateTune';  { zlib.h:744 }
function deflateBound(strm: z_streamp; sourceLen: uLong): uLong; external name 'deflateBound';  { zlib.h:761 }
function deflatePending(strm: z_streamp; pending: ^Cardinal; bits: ^Integer): Integer; external name 'deflatePending';  { zlib.h:776 }
function deflatePrime(strm: z_streamp; bits: Integer; value: Integer): Integer; external name 'deflatePrime';  { zlib.h:791 }
function deflateSetHeader(strm: z_streamp; head: gz_headerp): Integer; external name 'deflateSetHeader';  { zlib.h:808 }
function inflateSetDictionary(strm: z_streamp; dictionary: ^Byte; dictLength: uInt): Integer; external name 'inflateSetDictionary';  { zlib.h:888 }
function inflateGetDictionary(strm: z_streamp; dictionary: ^Bytef; dictLength: ^uInt): Integer; external name 'inflateGetDictionary';  { zlib.h:911 }
function inflateSync(strm: z_streamp): Integer; external name 'inflateSync';  { zlib.h:926 }
function inflateCopy(dest: z_streamp; source: z_streamp): Integer; external name 'inflateCopy';  { zlib.h:945 }
function inflateReset(strm: z_streamp): Integer; external name 'inflateReset';  { zlib.h:961 }
function inflateReset2(strm: z_streamp; windowBits: Integer): Integer; external name 'inflateReset2';  { zlib.h:972 }
function inflatePrime(strm: z_streamp; bits: Integer; value: Integer): Integer; external name 'inflatePrime';  { zlib.h:986 }
function inflateMark(strm: z_streamp): Int64; external name 'inflateMark';  { zlib.h:1007 }
function inflateGetHeader(strm: z_streamp; head: gz_headerp): Integer; external name 'inflateGetHeader';  { zlib.h:1035 }
function inflateBack(strm: z_streamp; in: in_func; in_desc: Pointer; out: out_func; out_desc: Pointer): Integer; external name 'inflateBack';  { zlib.h:1101 }
function inflateBackEnd(strm: z_streamp): Integer; external name 'inflateBackEnd';  { zlib.h:1171 }
function zlibCompileFlags: uLong; external name 'zlibCompileFlags';  { zlib.h:1179 }
function compress(dest: ^Bytef; destLen: ^uLongf; source: ^Byte; sourceLen: uLong): Integer; external name 'compress';  { zlib.h:1232 }
function compress2(dest: ^Bytef; destLen: ^uLongf; source: ^Byte; sourceLen: uLong; level: Integer): Integer; external name 'compress2';  { zlib.h:1247 }
function compressBound(sourceLen: uLong): uLong; external name 'compressBound';  { zlib.h:1263 }
function uncompress(dest: ^Bytef; destLen: ^uLongf; source: ^Byte; sourceLen: uLong): Integer; external name 'uncompress';  { zlib.h:1270 }
function uncompress2(dest: ^Bytef; destLen: ^uLongf; source: ^Byte; sourceLen: ^uLong): Integer; external name 'uncompress2';  { zlib.h:1288 }
function gzdopen(fd: Integer; mode: PChar): gzFile; external name 'gzdopen';  { zlib.h:1345 }
function gzbuffer(file: gzFile; size: Cardinal): Integer; external name 'gzbuffer';  { zlib.h:1368 }
function gzsetparams(file: gzFile; level: Integer; strategy: Integer): Integer; external name 'gzsetparams';  { zlib.h:1384 }
function gzread(file: gzFile; buf: voidp; len: Cardinal): Integer; external name 'gzread';  { zlib.h:1395 }
function gzfread(buf: voidp; size: z_size_t; nitems: z_size_t; file: gzFile): z_size_t; external name 'gzfread';  { zlib.h:1425 }
function gzwrite(file: gzFile; buf: voidpc; len: Cardinal): Integer; external name 'gzwrite';  { zlib.h:1451 }
function gzfwrite(buf: voidpc; size: z_size_t; nitems: z_size_t; file: gzFile): z_size_t; external name 'gzfwrite';  { zlib.h:1457 }
function gzprintf(file: gzFile; format: PChar): Integer; external name 'gzprintf'  { varargs — Blaise has no varargs syntax yet, call via wrapper };  { zlib.h:1471 }
function gzputs(file: gzFile; s: PChar): Integer; external name 'gzputs';  { zlib.h:1486 }
function gzgets(file: gzFile; buf: PChar; len: Integer): PChar; external name 'gzgets';  { zlib.h:1494 }
function gzputc(file: gzFile; c: Integer): Integer; external name 'gzputc';  { zlib.h:1508 }
function gzgetc(file: gzFile): Integer; external name 'gzgetc';  { zlib.h:1514 }
function gzungetc(c: Integer; file: gzFile): Integer; external name 'gzungetc';  { zlib.h:1523 }
function gzflush(file: gzFile; flush: Integer): Integer; external name 'gzflush';  { zlib.h:1535 }
function gzrewind(file: gzFile): Integer; external name 'gzrewind';  { zlib.h:1570 }
function gzeof(file: gzFile): Integer; external name 'gzeof';  { zlib.h:1598 }
function gzdirect(file: gzFile): Integer; external name 'gzdirect';  { zlib.h:1613 }
function gzclose(file: gzFile): Integer; external name 'gzclose';  { zlib.h:1634 }
function gzclose_r(file: gzFile): Integer; external name 'gzclose_r';  { zlib.h:1647 }
function gzclose_w(file: gzFile): Integer; external name 'gzclose_w';  { zlib.h:1648 }
function gzerror(file: gzFile; errnum: ^Integer): PChar; external name 'gzerror';  { zlib.h:1659 }
procedure gzclearerr(file: gzFile); external name 'gzclearerr';  { zlib.h:1675 }
function adler32(adler: uLong; buf: ^Byte; len: uInt): uLong; external name 'adler32';  { zlib.h:1692 }
function adler32_z(adler: uLong; buf: ^Byte; len: z_size_t): uLong; external name 'adler32_z';  { zlib.h:1712 }
function crc32(crc: uLong; buf: ^Byte; len: uInt): uLong; external name 'crc32';  { zlib.h:1730 }
function crc32_z(crc: uLong; buf: ^Byte; len: z_size_t): uLong; external name 'crc32_z';  { zlib.h:1748 }
function crc32_combine_op(crc1: uLong; crc2: uLong; op: uLong): uLong; external name 'crc32_combine_op';  { zlib.h:1771 }
function deflateInit_(strm: z_streamp; level: Integer; version: PChar; stream_size: Integer): Integer; external name 'deflateInit_';  { zlib.h:1784 }
function inflateInit_(strm: z_streamp; version: PChar; stream_size: Integer): Integer; external name 'inflateInit_';  { zlib.h:1786 }
function deflateInit2_(strm: z_streamp; level: Integer; method: Integer; windowBits: Integer; memLevel: Integer; strategy: Integer; version: PChar; stream_size: Integer): Integer; external name 'deflateInit2_';  { zlib.h:1788 }
function inflateInit2_(strm: z_streamp; windowBits: Integer; version: PChar; stream_size: Integer): Integer; external name 'inflateInit2_';  { zlib.h:1792 }
function inflateBackInit_(strm: z_streamp; windowBits: Integer; window: ^Byte; version: PChar; stream_size: Integer): Integer; external name 'inflateBackInit_';  { zlib.h:1794 }
function gzgetc_(file: gzFile): Integer; external name 'gzgetc_';  { zlib.h:1842 }
function gzopen(arg1: PChar; arg2: PChar): gzFile; external name 'gzopen';  { zlib.h:1896 }
function gzseek(arg1: gzFile; arg2: off_t; arg3: Integer): off_t; external name 'gzseek';  { zlib.h:1897 }
function gztell(arg1: gzFile): off_t; external name 'gztell';  { zlib.h:1898 }
function gzoffset(arg1: gzFile): off_t; external name 'gzoffset';  { zlib.h:1899 }
function adler32_combine(arg1: uLong; arg2: uLong; arg3: off_t): uLong; external name 'adler32_combine';  { zlib.h:1900 }
function crc32_combine(arg1: uLong; arg2: uLong; arg3: off_t): uLong; external name 'crc32_combine';  { zlib.h:1901 }
function crc32_combine_gen(arg1: off_t): uLong; external name 'crc32_combine_gen';  { zlib.h:1902 }
function zError(arg1: Integer): PChar; external name 'zError';  { zlib.h:1914 }
function inflateSyncPoint(arg1: z_streamp): Integer; external name 'inflateSyncPoint';  { zlib.h:1915 }
function get_crc_table: ^Cardinal; external name 'get_crc_table';  { zlib.h:1916 }
function inflateUndermine(arg1: z_streamp; arg2: Integer): Integer; external name 'inflateUndermine';  { zlib.h:1917 }
function inflateValidate(arg1: z_streamp; arg2: Integer): Integer; external name 'inflateValidate';  { zlib.h:1918 }
function inflateCodesUsed(arg1: z_streamp): UInt64; external name 'inflateCodesUsed';  { zlib.h:1919 }
function inflateResetKeep(arg1: z_streamp): Integer; external name 'inflateResetKeep';  { zlib.h:1920 }
function deflateResetKeep(arg1: z_streamp): Integer; external name 'deflateResetKeep';  { zlib.h:1921 }

implementation

end.
