' demo_rqbasic.bas — spinning 3D triangle. Immediate-mode OpenGL via
' the gl + freeglut bindings generated by pascal_bindgen --rqbasic.
'
'   - GLUT supplies the window, GL context, event loop, and the
'     timer that drives the animation tick.
'   - We render in the display callback: clear, push a rotation
'     onto the modelview matrix, draw a colour-blended triangle in
'     immediate mode, swap.
'   - A glutTimerFunc tick re-arms itself every 16ms (~60Hz),
'     bumps the angle, and posts a redisplay.

$INCLUDE "gl_rqbasic.bas"
$INCLUDE "glut_rqbasic.bas"

DIM angle AS SINGLE

SUB Display
  glClear(GL_COLOR_BUFFER_BIT)

  glMatrixMode(GL_PROJECTION)
  glLoadIdentity
  glOrtho(-1.5, 1.5, -1.5, 1.5, -2.0, 2.0)

  glMatrixMode(GL_MODELVIEW)
  glLoadIdentity
  glRotatef(angle, 0.3, 1.0, 0.2)

  glBegin(GL_TRIANGLES)
    glColor3f(1.0, 0.2, 0.2): glVertex3f( 0.0,  1.0, 0.0)
    glColor3f(0.2, 1.0, 0.2): glVertex3f(-1.0, -1.0, 0.0)
    glColor3f(0.2, 0.4, 1.0): glVertex3f( 1.0, -1.0, 0.0)
  glEnd

  glutSwapBuffers
END SUB

' glutTimerFunc fires once per call; re-arm here so the wheel keeps
' turning. The integer argument is whatever we passed in — unused.
SUB Tick (val AS INTEGER)
  angle = angle + 1.5
  IF angle > 360.0 THEN angle = angle - 360.0
  glutPostRedisplay
  glutTimerFunc(16, @Tick, 0)
END SUB

SUB Reshape (w AS INTEGER, h AS INTEGER)
  glViewport(0, 0, w, h)
END SUB

' glutInit wants `int *argcp, char **argv`. We pass a stand-in argc
' of 0 and null for argv — GLUT tolerates both for non-X-resource
' configuration. argv would need a typed PPCHAR to wire up cleanly;
' rqbasic doesn't grow that today.
DIM argc AS INTEGER
argc = 0

glutInit(VARPTR(argc), null)
glutInitDisplayMode(GLUT_DOUBLE OR GLUT_RGB OR GLUT_DEPTH)
glutInitWindowSize(640, 480)
glutCreateWindow(PCHAR("rqbasic + OpenGL — spinning triangle"))

glClearColor(0.07, 0.07, 0.09, 1.0)

glutDisplayFunc(@Display)
glutReshapeFunc(@Reshape)
glutTimerFunc(16, @Tick, 0)

glutMainLoop
