' demo_rqbasic.bas — spinning 3D triangle. Immediate-mode OpenGL via
' the gl + freeglut bindings generated by pascal_bindgen --rqbasic.
'
'   - GLUT supplies the window, GL context, event loop, and the
'     timer that drives the animation tick.
'   - We render in the display callback: clear, push a rotation
'     onto the modelview matrix, draw a colour-blended triangle in
'     immediate mode, swap.
'   - A glutTimerFunc tick re-arms itself every 16ms (~60Hz),
'     bumps the angle, and posts a redisplay.

$INCLUDE "gl_rqbasic.bas"
$INCLUDE "glut_rqbasic.bas"

' rapidq's SINGLE-by-value FFI is currently broken — the float bits
' don't reach C correctly (verified with libm sinf). Use the *d
' (double) variants of every GL call to sidestep it.
DIM angle AS DOUBLE

SUB Display
  glClear(GL_COLOR_BUFFER_BIT)

  ' Set projection here every frame — saves us from depending on
  ' Reshape having fired before the first Display. Ortho keeps the
  ' rendering pipeline trivial: NDC is [-2,2] in x/y and [-2,2] in z
  ' (so the rotating triangle stays inside clip space at any angle).
  glMatrixMode(GL_PROJECTION)
  glLoadIdentity
  glOrtho(-1.5, 1.5, -1.5, 1.5, -2.0, 2.0)

  glMatrixMode(GL_MODELVIEW)
  glLoadIdentity
  glRotated(angle, 0.3, 1.0, 0.2)

  glBegin(GL_TRIANGLES)
    glColor3d(1.0, 0.2, 0.2): glVertex3d( 0.0,  1.0, 0.0)
    glColor3d(0.2, 1.0, 0.2): glVertex3d(-1.0, -1.0, 0.0)
    glColor3d(0.2, 0.4, 1.0): glVertex3d( 1.0, -1.0, 0.0)
  glEnd

  glutSwapBuffers
END SUB

' glutTimerFunc fires once per call; re-arm here so the wheel keeps
' turning. The integer argument is whatever we passed in — unused.
SUB Tick (val AS INTEGER)
  angle = angle + 1.5
  IF angle > 360.0 THEN angle = angle - 360.0
  glutPostRedisplay
  glutTimerFunc(16, @Tick, 0)
END SUB

SUB Reshape (w AS INTEGER, h AS INTEGER)
  glViewport(0, 0, w, h)
END SUB

' glutInit wants `int *argcp, char **argv`. We pass a stand-in argc
' of 0 and null for argv — GLUT tolerates both for non-X-resource
' configuration. argv would need a typed PPCHAR to wire up cleanly;
' rqbasic doesn't grow that today.
DIM argc AS INTEGER
argc = 0

glutInit(VARPTR(argc), null)
glutInitDisplayMode(GLUT_DOUBLE OR GLUT_RGB OR GLUT_DEPTH)
glutInitWindowSize(640, 480)
glutCreateWindow(PCHAR("rqbasic + OpenGL — spinning triangle"))

' Default clear color (black) is fine here. glClearColor would take
' four SINGLEs and trip the same FFI bug.

glutDisplayFunc(@Display)
glutReshapeFunc(@Reshape)
glutTimerFunc(16, @Tick, 0)

glutMainLoop
