'DO NOT EDIT — generated by pascal_bindgen (RapidQ BASIC dialect).
'  source: /usr/include/GL/freeglut.h
'  library: glut

$CALLING CDECL

'typedef GLUTproc = POINTER  (' aliased — referenced inline)

CONST FREEGLUT = 1
CONST GLUT_API_VERSION = 4
CONST GLUT_XLIB_IMPLEMENTATION = 13
CONST FREEGLUT_VERSION_2_0 = 1
CONST GLUT_KEY_F1 = &H0001
CONST GLUT_KEY_F2 = &H0002
CONST GLUT_KEY_F3 = &H0003
CONST GLUT_KEY_F4 = &H0004
CONST GLUT_KEY_F5 = &H0005
CONST GLUT_KEY_F6 = &H0006
CONST GLUT_KEY_F7 = &H0007
CONST GLUT_KEY_F8 = &H0008
CONST GLUT_KEY_F9 = &H0009
CONST GLUT_KEY_F10 = &H000A
CONST GLUT_KEY_F11 = &H000B
CONST GLUT_KEY_F12 = &H000C
CONST GLUT_KEY_LEFT = &H0064
CONST GLUT_KEY_UP = &H0065
CONST GLUT_KEY_RIGHT = &H0066
CONST GLUT_KEY_DOWN = &H0067
CONST GLUT_KEY_PAGE_UP = &H0068
CONST GLUT_KEY_PAGE_DOWN = &H0069
CONST GLUT_KEY_HOME = &H006A
CONST GLUT_KEY_END = &H006B
CONST GLUT_KEY_INSERT = &H006C
CONST GLUT_LEFT_BUTTON = &H0000
CONST GLUT_MIDDLE_BUTTON = &H0001
CONST GLUT_RIGHT_BUTTON = &H0002
CONST GLUT_DOWN = &H0000
CONST GLUT_UP = &H0001
CONST GLUT_LEFT = &H0000
CONST GLUT_ENTERED = &H0001
CONST GLUT_RGB = &H0000
CONST GLUT_RGBA = &H0000
CONST GLUT_INDEX = &H0001
CONST GLUT_SINGLE = &H0000
CONST GLUT_DOUBLE = &H0002
CONST GLUT_ACCUM = &H0004
CONST GLUT_ALPHA = &H0008
CONST GLUT_DEPTH = &H0010
CONST GLUT_STENCIL = &H0020
CONST GLUT_MULTISAMPLE = &H0080
CONST GLUT_STEREO = &H0100
CONST GLUT_LUMINANCE = &H0200
CONST GLUT_MENU_NOT_IN_USE = &H0000
CONST GLUT_MENU_IN_USE = &H0001
CONST GLUT_NOT_VISIBLE = &H0000
CONST GLUT_VISIBLE = &H0001
CONST GLUT_HIDDEN = &H0000
CONST GLUT_FULLY_RETAINED = &H0001
CONST GLUT_PARTIALLY_RETAINED = &H0002
CONST GLUT_FULLY_COVERED = &H0003
CONST GLUT_WINDOW_X = &H0064
CONST GLUT_WINDOW_Y = &H0065
CONST GLUT_WINDOW_WIDTH = &H0066
CONST GLUT_WINDOW_HEIGHT = &H0067
CONST GLUT_WINDOW_BUFFER_SIZE = &H0068
CONST GLUT_WINDOW_STENCIL_SIZE = &H0069
CONST GLUT_WINDOW_DEPTH_SIZE = &H006A
CONST GLUT_WINDOW_RED_SIZE = &H006B
CONST GLUT_WINDOW_GREEN_SIZE = &H006C
CONST GLUT_WINDOW_BLUE_SIZE = &H006D
CONST GLUT_WINDOW_ALPHA_SIZE = &H006E
CONST GLUT_WINDOW_ACCUM_RED_SIZE = &H006F
CONST GLUT_WINDOW_ACCUM_GREEN_SIZE = &H0070
CONST GLUT_WINDOW_ACCUM_BLUE_SIZE = &H0071
CONST GLUT_WINDOW_ACCUM_ALPHA_SIZE = &H0072
CONST GLUT_WINDOW_DOUBLEBUFFER = &H0073
CONST GLUT_WINDOW_RGBA = &H0074
CONST GLUT_WINDOW_PARENT = &H0075
CONST GLUT_WINDOW_NUM_CHILDREN = &H0076
CONST GLUT_WINDOW_COLORMAP_SIZE = &H0077
CONST GLUT_WINDOW_NUM_SAMPLES = &H0078
CONST GLUT_WINDOW_STEREO = &H0079
CONST GLUT_WINDOW_CURSOR = &H007A
CONST GLUT_SCREEN_WIDTH = &H00C8
CONST GLUT_SCREEN_HEIGHT = &H00C9
CONST GLUT_SCREEN_WIDTH_MM = &H00CA
CONST GLUT_SCREEN_HEIGHT_MM = &H00CB
CONST GLUT_MENU_NUM_ITEMS = &H012C
CONST GLUT_DISPLAY_MODE_POSSIBLE = &H0190
CONST GLUT_INIT_WINDOW_X = &H01F4
CONST GLUT_INIT_WINDOW_Y = &H01F5
CONST GLUT_INIT_WINDOW_WIDTH = &H01F6
CONST GLUT_INIT_WINDOW_HEIGHT = &H01F7
CONST GLUT_INIT_DISPLAY_MODE = &H01F8
CONST GLUT_ELAPSED_TIME = &H02BC
CONST GLUT_WINDOW_FORMAT_ID = &H007B
CONST GLUT_HAS_KEYBOARD = &H0258
CONST GLUT_HAS_MOUSE = &H0259
CONST GLUT_HAS_SPACEBALL = &H025A
CONST GLUT_HAS_DIAL_AND_BUTTON_BOX = &H025B
CONST GLUT_HAS_TABLET = &H025C
CONST GLUT_NUM_MOUSE_BUTTONS = &H025D
CONST GLUT_NUM_SPACEBALL_BUTTONS = &H025E
CONST GLUT_NUM_BUTTON_BOX_BUTTONS = &H025F
CONST GLUT_NUM_DIALS = &H0260
CONST GLUT_NUM_TABLET_BUTTONS = &H0261
CONST GLUT_DEVICE_IGNORE_KEY_REPEAT = &H0262
CONST GLUT_DEVICE_KEY_REPEAT = &H0263
CONST GLUT_HAS_JOYSTICK = &H0264
CONST GLUT_OWNS_JOYSTICK = &H0265
CONST GLUT_JOYSTICK_BUTTONS = &H0266
CONST GLUT_JOYSTICK_AXES = &H0267
CONST GLUT_JOYSTICK_POLL_RATE = &H0268
CONST GLUT_OVERLAY_POSSIBLE = &H0320
CONST GLUT_LAYER_IN_USE = &H0321
CONST GLUT_HAS_OVERLAY = &H0322
CONST GLUT_TRANSPARENT_INDEX = &H0323
CONST GLUT_NORMAL_DAMAGED = &H0324
CONST GLUT_OVERLAY_DAMAGED = &H0325
CONST GLUT_VIDEO_RESIZE_POSSIBLE = &H0384
CONST GLUT_VIDEO_RESIZE_IN_USE = &H0385
CONST GLUT_VIDEO_RESIZE_X_DELTA = &H0386
CONST GLUT_VIDEO_RESIZE_Y_DELTA = &H0387
CONST GLUT_VIDEO_RESIZE_WIDTH_DELTA = &H0388
CONST GLUT_VIDEO_RESIZE_HEIGHT_DELTA = &H0389
CONST GLUT_VIDEO_RESIZE_X = &H038A
CONST GLUT_VIDEO_RESIZE_Y = &H038B
CONST GLUT_VIDEO_RESIZE_WIDTH = &H038C
CONST GLUT_VIDEO_RESIZE_HEIGHT = &H038D
CONST GLUT_NORMAL = &H0000
CONST GLUT_OVERLAY = &H0001
CONST GLUT_ACTIVE_SHIFT = &H0001
CONST GLUT_ACTIVE_CTRL = &H0002
CONST GLUT_ACTIVE_ALT = &H0004
CONST GLUT_CURSOR_RIGHT_ARROW = &H0000
CONST GLUT_CURSOR_LEFT_ARROW = &H0001
CONST GLUT_CURSOR_INFO = &H0002
CONST GLUT_CURSOR_DESTROY = &H0003
CONST GLUT_CURSOR_HELP = &H0004
CONST GLUT_CURSOR_CYCLE = &H0005
CONST GLUT_CURSOR_SPRAY = &H0006
CONST GLUT_CURSOR_WAIT = &H0007
CONST GLUT_CURSOR_TEXT = &H0008
CONST GLUT_CURSOR_CROSSHAIR = &H0009
CONST GLUT_CURSOR_UP_DOWN = &H000A
CONST GLUT_CURSOR_LEFT_RIGHT = &H000B
CONST GLUT_CURSOR_TOP_SIDE = &H000C
CONST GLUT_CURSOR_BOTTOM_SIDE = &H000D
CONST GLUT_CURSOR_LEFT_SIDE = &H000E
CONST GLUT_CURSOR_RIGHT_SIDE = &H000F
CONST GLUT_CURSOR_TOP_LEFT_CORNER = &H0010
CONST GLUT_CURSOR_TOP_RIGHT_CORNER = &H0011
CONST GLUT_CURSOR_BOTTOM_RIGHT_CORNER = &H0012
CONST GLUT_CURSOR_BOTTOM_LEFT_CORNER = &H0013
CONST GLUT_CURSOR_INHERIT = &H0064
CONST GLUT_CURSOR_NONE = &H0065
CONST GLUT_CURSOR_FULL_CROSSHAIR = &H0066
CONST GLUT_RED = &H0000
CONST GLUT_GREEN = &H0001
CONST GLUT_BLUE = &H0002
CONST GLUT_KEY_REPEAT_OFF = &H0000
CONST GLUT_KEY_REPEAT_ON = &H0001
CONST GLUT_KEY_REPEAT_DEFAULT = &H0002
CONST GLUT_JOYSTICK_BUTTON_A = &H0001
CONST GLUT_JOYSTICK_BUTTON_B = &H0002
CONST GLUT_JOYSTICK_BUTTON_C = &H0004
CONST GLUT_JOYSTICK_BUTTON_D = &H0008
CONST GLUT_GAME_MODE_ACTIVE = &H0000
CONST GLUT_GAME_MODE_POSSIBLE = &H0001
CONST GLUT_GAME_MODE_WIDTH = &H0002
CONST GLUT_GAME_MODE_HEIGHT = &H0003
CONST GLUT_GAME_MODE_PIXEL_DEPTH = &H0004
CONST GLUT_GAME_MODE_REFRESH_RATE = &H0005
CONST GLUT_GAME_MODE_DISPLAY_CHANGED = &H0006
CONST GLUT_KEY_NUM_LOCK = &H006D
CONST GLUT_KEY_BEGIN = &H006E
CONST GLUT_KEY_DELETE = &H006F
CONST GLUT_KEY_SHIFT_L = &H0070
CONST GLUT_KEY_SHIFT_R = &H0071
CONST GLUT_KEY_CTRL_L = &H0072
CONST GLUT_KEY_CTRL_R = &H0073
CONST GLUT_KEY_ALT_L = &H0074
CONST GLUT_KEY_ALT_R = &H0075
CONST GLUT_KEY_SUPER_L = &H0076
CONST GLUT_KEY_SUPER_R = &H0077
CONST GLUT_ACTIVE_SUPER = &H0008
CONST GLUT_ACTION_EXIT = 0
CONST GLUT_ACTION_GLUTMAINLOOP_RETURNS = 1
CONST GLUT_ACTION_CONTINUE_EXECUTION = 2
CONST GLUT_CREATE_NEW_CONTEXT = 0
CONST GLUT_USE_CURRENT_CONTEXT = 1
CONST GLUT_FORCE_INDIRECT_CONTEXT = 0
CONST GLUT_ALLOW_DIRECT_CONTEXT = 1
CONST GLUT_TRY_DIRECT_CONTEXT = 2
CONST GLUT_FORCE_DIRECT_CONTEXT = 3
CONST GLUT_INIT_STATE = &H007C
CONST GLUT_ACTION_ON_WINDOW_CLOSE = &H01F9
CONST GLUT_WINDOW_BORDER_WIDTH = &H01FA
CONST GLUT_WINDOW_BORDER_HEIGHT = &H01FB
CONST GLUT_WINDOW_HEADER_HEIGHT = &H01FB
CONST GLUT_VERSION = &H01FC
CONST GLUT_RENDERING_CONTEXT = &H01FD
CONST GLUT_DIRECT_RENDERING = &H01FE
CONST GLUT_FULL_SCREEN = &H01FF
CONST GLUT_SKIP_STALE_MOTION_EVENTS = &H0204
CONST GLUT_GEOMETRY_VISUALIZE_NORMALS = &H0205
CONST GLUT_STROKE_FONT_DRAW_JOIN_DOTS = &H0206
CONST GLUT_ALLOW_NEGATIVE_WINDOW_POSITION = &H0207
CONST GLUT_WINDOW_SRGB = &H007D
CONST GLUT_AUX = &H1000
CONST GLUT_AUX1 = &H1000
CONST GLUT_AUX2 = &H2000
CONST GLUT_AUX3 = &H4000
CONST GLUT_AUX4 = &H8000
CONST GLUT_INIT_MAJOR_VERSION = &H0200
CONST GLUT_INIT_MINOR_VERSION = &H0201
CONST GLUT_INIT_FLAGS = &H0202
CONST GLUT_INIT_PROFILE = &H0203
CONST GLUT_DEBUG = &H0001
CONST GLUT_FORWARD_COMPATIBLE = &H0002
CONST GLUT_CORE_PROFILE = &H0001
CONST GLUT_COMPATIBILITY_PROFILE = &H0002
CONST GLUT_SPACEBALL_BUTTON_A = &H0001
CONST GLUT_SPACEBALL_BUTTON_B = &H0002
CONST GLUT_SPACEBALL_BUTTON_C = &H0004
CONST GLUT_SPACEBALL_BUTTON_D = &H0008
CONST GLUT_SPACEBALL_BUTTON_E = &H0010
CONST GLUT_HAS_MULTI = 1
CONST GLUT_APPSTATUS_PAUSE = &H0001
CONST GLUT_APPSTATUS_RESUME = &H0002
CONST GLUT_CAPTIONLESS = &H0400
CONST GLUT_BORDERLESS = &H0800
CONST GLUT_SRGB = &H1000

DECLARE SUB      glutInit LIB "glut" ALIAS "glutInit" (pargc AS POINTER, argv AS POINTER)
DECLARE SUB      glutInitWindowPosition LIB "glut" ALIAS "glutInitWindowPosition" (x AS INTEGER, y AS INTEGER)
DECLARE SUB      glutInitWindowSize LIB "glut" ALIAS "glutInitWindowSize" (width AS INTEGER, height AS INTEGER)
DECLARE SUB      glutInitDisplayMode LIB "glut" ALIAS "glutInitDisplayMode" (displayMode AS DWORD)
DECLARE SUB      glutInitDisplayString LIB "glut" ALIAS "glutInitDisplayString" (displayMode AS POINTER)
DECLARE SUB      glutMainLoop LIB "glut" ALIAS "glutMainLoop" ()
DECLARE FUNCTION glutCreateWindow LIB "glut" ALIAS "glutCreateWindow" (title AS POINTER) AS INTEGER
DECLARE FUNCTION glutCreateSubWindow LIB "glut" ALIAS "glutCreateSubWindow" (window AS INTEGER, x AS INTEGER, y AS INTEGER, width AS INTEGER, height AS INTEGER) AS INTEGER
DECLARE SUB      glutDestroyWindow LIB "glut" ALIAS "glutDestroyWindow" (window AS INTEGER)
DECLARE SUB      glutSetWindow LIB "glut" ALIAS "glutSetWindow" (window AS INTEGER)
DECLARE FUNCTION glutGetWindow LIB "glut" ALIAS "glutGetWindow" () AS INTEGER
DECLARE SUB      glutSetWindowTitle LIB "glut" ALIAS "glutSetWindowTitle" (title AS POINTER)
DECLARE SUB      glutSetIconTitle LIB "glut" ALIAS "glutSetIconTitle" (title AS POINTER)
DECLARE SUB      glutReshapeWindow LIB "glut" ALIAS "glutReshapeWindow" (width AS INTEGER, height AS INTEGER)
DECLARE SUB      glutPositionWindow LIB "glut" ALIAS "glutPositionWindow" (x AS INTEGER, y AS INTEGER)
DECLARE SUB      glutShowWindow LIB "glut" ALIAS "glutShowWindow" ()
DECLARE SUB      glutHideWindow LIB "glut" ALIAS "glutHideWindow" ()
DECLARE SUB      glutIconifyWindow LIB "glut" ALIAS "glutIconifyWindow" ()
DECLARE SUB      glutPushWindow LIB "glut" ALIAS "glutPushWindow" ()
DECLARE SUB      glutPopWindow LIB "glut" ALIAS "glutPopWindow" ()
DECLARE SUB      glutFullScreen LIB "glut" ALIAS "glutFullScreen" ()
DECLARE SUB      glutPostWindowRedisplay LIB "glut" ALIAS "glutPostWindowRedisplay" (window AS INTEGER)
DECLARE SUB      glutPostRedisplay LIB "glut" ALIAS "glutPostRedisplay" ()
DECLARE SUB      glutSwapBuffers LIB "glut" ALIAS "glutSwapBuffers" ()
DECLARE SUB      glutWarpPointer LIB "glut" ALIAS "glutWarpPointer" (x AS INTEGER, y AS INTEGER)
DECLARE SUB      glutSetCursor LIB "glut" ALIAS "glutSetCursor" (cursor AS INTEGER)
DECLARE SUB      glutEstablishOverlay LIB "glut" ALIAS "glutEstablishOverlay" ()
DECLARE SUB      glutRemoveOverlay LIB "glut" ALIAS "glutRemoveOverlay" ()
DECLARE SUB      glutUseLayer LIB "glut" ALIAS "glutUseLayer" (layer AS DWORD)
DECLARE SUB      glutPostOverlayRedisplay LIB "glut" ALIAS "glutPostOverlayRedisplay" ()
DECLARE SUB      glutPostWindowOverlayRedisplay LIB "glut" ALIAS "glutPostWindowOverlayRedisplay" (window AS INTEGER)
DECLARE SUB      glutShowOverlay LIB "glut" ALIAS "glutShowOverlay" ()
DECLARE SUB      glutHideOverlay LIB "glut" ALIAS "glutHideOverlay" ()
DECLARE FUNCTION glutCreateMenu LIB "glut" ALIAS "glutCreateMenu" (callback AS POINTER) AS INTEGER
DECLARE SUB      glutDestroyMenu LIB "glut" ALIAS "glutDestroyMenu" (menu AS INTEGER)
DECLARE FUNCTION glutGetMenu LIB "glut" ALIAS "glutGetMenu" () AS INTEGER
DECLARE SUB      glutSetMenu LIB "glut" ALIAS "glutSetMenu" (menu AS INTEGER)
DECLARE SUB      glutAddMenuEntry LIB "glut" ALIAS "glutAddMenuEntry" (label AS POINTER, value AS INTEGER)
DECLARE SUB      glutAddSubMenu LIB "glut" ALIAS "glutAddSubMenu" (label AS POINTER, subMenu AS INTEGER)
DECLARE SUB      glutChangeToMenuEntry LIB "glut" ALIAS "glutChangeToMenuEntry" (item AS INTEGER, label AS POINTER, value AS INTEGER)
DECLARE SUB      glutChangeToSubMenu LIB "glut" ALIAS "glutChangeToSubMenu" (item AS INTEGER, label AS POINTER, value AS INTEGER)
DECLARE SUB      glutRemoveMenuItem LIB "glut" ALIAS "glutRemoveMenuItem" (item AS INTEGER)
DECLARE SUB      glutAttachMenu LIB "glut" ALIAS "glutAttachMenu" (button AS INTEGER)
DECLARE SUB      glutDetachMenu LIB "glut" ALIAS "glutDetachMenu" (button AS INTEGER)
DECLARE SUB      glutTimerFunc LIB "glut" ALIAS "glutTimerFunc" (time AS DWORD, callback AS POINTER, value AS INTEGER)
DECLARE SUB      glutIdleFunc LIB "glut" ALIAS "glutIdleFunc" (callback AS POINTER)
DECLARE SUB      glutKeyboardFunc LIB "glut" ALIAS "glutKeyboardFunc" (callback AS POINTER)
DECLARE SUB      glutSpecialFunc LIB "glut" ALIAS "glutSpecialFunc" (callback AS POINTER)
DECLARE SUB      glutReshapeFunc LIB "glut" ALIAS "glutReshapeFunc" (callback AS POINTER)
DECLARE SUB      glutVisibilityFunc LIB "glut" ALIAS "glutVisibilityFunc" (callback AS POINTER)
DECLARE SUB      glutDisplayFunc LIB "glut" ALIAS "glutDisplayFunc" (callback AS POINTER)
DECLARE SUB      glutMouseFunc LIB "glut" ALIAS "glutMouseFunc" (callback AS POINTER)
DECLARE SUB      glutMotionFunc LIB "glut" ALIAS "glutMotionFunc" (callback AS POINTER)
DECLARE SUB      glutPassiveMotionFunc LIB "glut" ALIAS "glutPassiveMotionFunc" (callback AS POINTER)
DECLARE SUB      glutEntryFunc LIB "glut" ALIAS "glutEntryFunc" (callback AS POINTER)
DECLARE SUB      glutKeyboardUpFunc LIB "glut" ALIAS "glutKeyboardUpFunc" (callback AS POINTER)
DECLARE SUB      glutSpecialUpFunc LIB "glut" ALIAS "glutSpecialUpFunc" (callback AS POINTER)
DECLARE SUB      glutJoystickFunc LIB "glut" ALIAS "glutJoystickFunc" (callback AS POINTER, pollInterval AS INTEGER)
DECLARE SUB      glutMenuStateFunc LIB "glut" ALIAS "glutMenuStateFunc" (callback AS POINTER)
DECLARE SUB      glutMenuStatusFunc LIB "glut" ALIAS "glutMenuStatusFunc" (callback AS POINTER)
DECLARE SUB      glutOverlayDisplayFunc LIB "glut" ALIAS "glutOverlayDisplayFunc" (callback AS POINTER)
DECLARE SUB      glutWindowStatusFunc LIB "glut" ALIAS "glutWindowStatusFunc" (callback AS POINTER)
DECLARE SUB      glutSpaceballMotionFunc LIB "glut" ALIAS "glutSpaceballMotionFunc" (callback AS POINTER)
DECLARE SUB      glutSpaceballRotateFunc LIB "glut" ALIAS "glutSpaceballRotateFunc" (callback AS POINTER)
DECLARE SUB      glutSpaceballButtonFunc LIB "glut" ALIAS "glutSpaceballButtonFunc" (callback AS POINTER)
DECLARE SUB      glutButtonBoxFunc LIB "glut" ALIAS "glutButtonBoxFunc" (callback AS POINTER)
DECLARE SUB      glutDialsFunc LIB "glut" ALIAS "glutDialsFunc" (callback AS POINTER)
DECLARE SUB      glutTabletMotionFunc LIB "glut" ALIAS "glutTabletMotionFunc" (callback AS POINTER)
DECLARE SUB      glutTabletButtonFunc LIB "glut" ALIAS "glutTabletButtonFunc" (callback AS POINTER)
DECLARE FUNCTION glutGet LIB "glut" ALIAS "glutGet" (query AS DWORD) AS INTEGER
DECLARE FUNCTION glutDeviceGet LIB "glut" ALIAS "glutDeviceGet" (query AS DWORD) AS INTEGER
DECLARE FUNCTION glutGetModifiers LIB "glut" ALIAS "glutGetModifiers" () AS INTEGER
DECLARE FUNCTION glutLayerGet LIB "glut" ALIAS "glutLayerGet" (query AS DWORD) AS INTEGER
DECLARE SUB      glutBitmapCharacter LIB "glut" ALIAS "glutBitmapCharacter" (font AS POINTER, character AS INTEGER)
DECLARE FUNCTION glutBitmapWidth LIB "glut" ALIAS "glutBitmapWidth" (font AS POINTER, character AS INTEGER) AS INTEGER
DECLARE SUB      glutStrokeCharacter LIB "glut" ALIAS "glutStrokeCharacter" (font AS POINTER, character AS INTEGER)
DECLARE FUNCTION glutStrokeWidth LIB "glut" ALIAS "glutStrokeWidth" (font AS POINTER, character AS INTEGER) AS INTEGER
DECLARE FUNCTION glutStrokeWidthf LIB "glut" ALIAS "glutStrokeWidthf" (font AS POINTER, character AS INTEGER) AS SINGLE
DECLARE FUNCTION glutBitmapLength LIB "glut" ALIAS "glutBitmapLength" (font AS POINTER, string_ AS POINTER) AS INTEGER
DECLARE FUNCTION glutStrokeLength LIB "glut" ALIAS "glutStrokeLength" (font AS POINTER, string_ AS POINTER) AS INTEGER
DECLARE FUNCTION glutStrokeLengthf LIB "glut" ALIAS "glutStrokeLengthf" (font AS POINTER, string_ AS POINTER) AS SINGLE
DECLARE SUB      glutWireCube LIB "glut" ALIAS "glutWireCube" (size AS DOUBLE)
DECLARE SUB      glutSolidCube LIB "glut" ALIAS "glutSolidCube" (size AS DOUBLE)
DECLARE SUB      glutWireSphere LIB "glut" ALIAS "glutWireSphere" (radius AS DOUBLE, slices AS INTEGER, stacks AS INTEGER)
DECLARE SUB      glutSolidSphere LIB "glut" ALIAS "glutSolidSphere" (radius AS DOUBLE, slices AS INTEGER, stacks AS INTEGER)
DECLARE SUB      glutWireCone LIB "glut" ALIAS "glutWireCone" (base_ AS DOUBLE, height AS DOUBLE, slices AS INTEGER, stacks AS INTEGER)
DECLARE SUB      glutSolidCone LIB "glut" ALIAS "glutSolidCone" (base_ AS DOUBLE, height AS DOUBLE, slices AS INTEGER, stacks AS INTEGER)
DECLARE SUB      glutWireTorus LIB "glut" ALIAS "glutWireTorus" (innerRadius AS DOUBLE, outerRadius AS DOUBLE, sides AS INTEGER, rings AS INTEGER)
DECLARE SUB      glutSolidTorus LIB "glut" ALIAS "glutSolidTorus" (innerRadius AS DOUBLE, outerRadius AS DOUBLE, sides AS INTEGER, rings AS INTEGER)
DECLARE SUB      glutWireDodecahedron LIB "glut" ALIAS "glutWireDodecahedron" ()
DECLARE SUB      glutSolidDodecahedron LIB "glut" ALIAS "glutSolidDodecahedron" ()
DECLARE SUB      glutWireOctahedron LIB "glut" ALIAS "glutWireOctahedron" ()
DECLARE SUB      glutSolidOctahedron LIB "glut" ALIAS "glutSolidOctahedron" ()
DECLARE SUB      glutWireTetrahedron LIB "glut" ALIAS "glutWireTetrahedron" ()
DECLARE SUB      glutSolidTetrahedron LIB "glut" ALIAS "glutSolidTetrahedron" ()
DECLARE SUB      glutWireIcosahedron LIB "glut" ALIAS "glutWireIcosahedron" ()
DECLARE SUB      glutSolidIcosahedron LIB "glut" ALIAS "glutSolidIcosahedron" ()
DECLARE SUB      glutWireTeapot LIB "glut" ALIAS "glutWireTeapot" (size AS DOUBLE)
DECLARE SUB      glutSolidTeapot LIB "glut" ALIAS "glutSolidTeapot" (size AS DOUBLE)
DECLARE SUB      glutGameModeString LIB "glut" ALIAS "glutGameModeString" (string_ AS POINTER)
DECLARE FUNCTION glutEnterGameMode LIB "glut" ALIAS "glutEnterGameMode" () AS INTEGER
DECLARE SUB      glutLeaveGameMode LIB "glut" ALIAS "glutLeaveGameMode" ()
DECLARE FUNCTION glutGameModeGet LIB "glut" ALIAS "glutGameModeGet" (query AS DWORD) AS INTEGER
DECLARE FUNCTION glutVideoResizeGet LIB "glut" ALIAS "glutVideoResizeGet" (query AS DWORD) AS INTEGER
DECLARE SUB      glutSetupVideoResizing LIB "glut" ALIAS "glutSetupVideoResizing" ()
DECLARE SUB      glutStopVideoResizing LIB "glut" ALIAS "glutStopVideoResizing" ()
DECLARE SUB      glutVideoResize LIB "glut" ALIAS "glutVideoResize" (x AS INTEGER, y AS INTEGER, width AS INTEGER, height AS INTEGER)
DECLARE SUB      glutVideoPan LIB "glut" ALIAS "glutVideoPan" (x AS INTEGER, y AS INTEGER, width AS INTEGER, height AS INTEGER)
DECLARE SUB      glutSetColor LIB "glut" ALIAS "glutSetColor" (color_ AS INTEGER, red AS SINGLE, green AS SINGLE, blue AS SINGLE)
DECLARE FUNCTION glutGetColor LIB "glut" ALIAS "glutGetColor" (color_ AS INTEGER, component AS INTEGER) AS SINGLE
DECLARE SUB      glutCopyColormap LIB "glut" ALIAS "glutCopyColormap" (window AS INTEGER)
DECLARE SUB      glutIgnoreKeyRepeat LIB "glut" ALIAS "glutIgnoreKeyRepeat" (ignore AS INTEGER)
DECLARE SUB      glutSetKeyRepeat LIB "glut" ALIAS "glutSetKeyRepeat" (repeatMode AS INTEGER)
DECLARE SUB      glutForceJoystickFunc LIB "glut" ALIAS "glutForceJoystickFunc" ()
DECLARE FUNCTION glutExtensionSupported LIB "glut" ALIAS "glutExtensionSupported" (extension AS POINTER) AS INTEGER
DECLARE SUB      glutReportErrors LIB "glut" ALIAS "glutReportErrors" ()
DECLARE SUB      glutMainLoopEvent LIB "glut" ALIAS "glutMainLoopEvent" ()
DECLARE SUB      glutLeaveMainLoop LIB "glut" ALIAS "glutLeaveMainLoop" ()
DECLARE SUB      glutExit LIB "glut" ALIAS "glutExit" ()
DECLARE SUB      glutFullScreenToggle LIB "glut" ALIAS "glutFullScreenToggle" ()
DECLARE SUB      glutLeaveFullScreen LIB "glut" ALIAS "glutLeaveFullScreen" ()
DECLARE SUB      glutSetMenuFont LIB "glut" ALIAS "glutSetMenuFont" (menuID AS INTEGER, font AS POINTER)
DECLARE SUB      glutMouseWheelFunc LIB "glut" ALIAS "glutMouseWheelFunc" (callback AS POINTER)
DECLARE SUB      glutPositionFunc LIB "glut" ALIAS "glutPositionFunc" (callback AS POINTER)
DECLARE SUB      glutCloseFunc LIB "glut" ALIAS "glutCloseFunc" (callback AS POINTER)
DECLARE SUB      glutWMCloseFunc LIB "glut" ALIAS "glutWMCloseFunc" (callback AS POINTER)
DECLARE SUB      glutMenuDestroyFunc LIB "glut" ALIAS "glutMenuDestroyFunc" (callback AS POINTER)
DECLARE SUB      glutSetOption LIB "glut" ALIAS "glutSetOption" (option_flag AS DWORD, value AS INTEGER)
DECLARE FUNCTION glutGetModeValues LIB "glut" ALIAS "glutGetModeValues" (mode AS DWORD, size AS POINTER) AS POINTER
DECLARE FUNCTION glutGetWindowData LIB "glut" ALIAS "glutGetWindowData" () AS POINTER
DECLARE SUB      glutSetWindowData LIB "glut" ALIAS "glutSetWindowData" (data AS POINTER)
DECLARE FUNCTION glutGetMenuData LIB "glut" ALIAS "glutGetMenuData" () AS POINTER
DECLARE SUB      glutSetMenuData LIB "glut" ALIAS "glutSetMenuData" (data AS POINTER)
DECLARE FUNCTION glutBitmapHeight LIB "glut" ALIAS "glutBitmapHeight" (font AS POINTER) AS INTEGER
DECLARE FUNCTION glutStrokeHeight LIB "glut" ALIAS "glutStrokeHeight" (font AS POINTER) AS SINGLE
DECLARE SUB      glutBitmapString LIB "glut" ALIAS "glutBitmapString" (font AS POINTER, string_ AS POINTER)
DECLARE SUB      glutStrokeString LIB "glut" ALIAS "glutStrokeString" (font AS POINTER, string_ AS POINTER)
DECLARE SUB      glutWireRhombicDodecahedron LIB "glut" ALIAS "glutWireRhombicDodecahedron" ()
DECLARE SUB      glutSolidRhombicDodecahedron LIB "glut" ALIAS "glutSolidRhombicDodecahedron" ()
DECLARE SUB      glutWireSierpinskiSponge LIB "glut" ALIAS "glutWireSierpinskiSponge" (num_levels AS INTEGER, offset AS DOUBLE(2), scale AS DOUBLE)
DECLARE SUB      glutSolidSierpinskiSponge LIB "glut" ALIAS "glutSolidSierpinskiSponge" (num_levels AS INTEGER, offset AS DOUBLE(2), scale AS DOUBLE)
DECLARE SUB      glutWireCylinder LIB "glut" ALIAS "glutWireCylinder" (radius AS DOUBLE, height AS DOUBLE, slices AS INTEGER, stacks AS INTEGER)
DECLARE SUB      glutSolidCylinder LIB "glut" ALIAS "glutSolidCylinder" (radius AS DOUBLE, height AS DOUBLE, slices AS INTEGER, stacks AS INTEGER)
DECLARE SUB      glutWireTeacup LIB "glut" ALIAS "glutWireTeacup" (size AS DOUBLE)
DECLARE SUB      glutSolidTeacup LIB "glut" ALIAS "glutSolidTeacup" (size AS DOUBLE)
DECLARE SUB      glutWireTeaspoon LIB "glut" ALIAS "glutWireTeaspoon" (size AS DOUBLE)
DECLARE SUB      glutSolidTeaspoon LIB "glut" ALIAS "glutSolidTeaspoon" (size AS DOUBLE)
DECLARE FUNCTION glutGetProcAddress LIB "glut" ALIAS "glutGetProcAddress" (procName AS POINTER) AS POINTER
DECLARE SUB      glutMultiEntryFunc LIB "glut" ALIAS "glutMultiEntryFunc" (callback AS POINTER)
DECLARE SUB      glutMultiButtonFunc LIB "glut" ALIAS "glutMultiButtonFunc" (callback AS POINTER)
DECLARE SUB      glutMultiMotionFunc LIB "glut" ALIAS "glutMultiMotionFunc" (callback AS POINTER)
DECLARE SUB      glutMultiPassiveFunc LIB "glut" ALIAS "glutMultiPassiveFunc" (callback AS POINTER)
DECLARE FUNCTION glutJoystickGetNumAxes LIB "glut" ALIAS "glutJoystickGetNumAxes" (ident AS INTEGER) AS INTEGER
DECLARE FUNCTION glutJoystickGetNumButtons LIB "glut" ALIAS "glutJoystickGetNumButtons" (ident AS INTEGER) AS INTEGER
DECLARE FUNCTION glutJoystickNotWorking LIB "glut" ALIAS "glutJoystickNotWorking" (ident AS INTEGER) AS INTEGER
DECLARE FUNCTION glutJoystickGetDeadBand LIB "glut" ALIAS "glutJoystickGetDeadBand" (ident AS INTEGER, axis AS INTEGER) AS SINGLE
DECLARE SUB      glutJoystickSetDeadBand LIB "glut" ALIAS "glutJoystickSetDeadBand" (ident AS INTEGER, axis AS INTEGER, db AS SINGLE)
DECLARE FUNCTION glutJoystickGetSaturation LIB "glut" ALIAS "glutJoystickGetSaturation" (ident AS INTEGER, axis AS INTEGER) AS SINGLE
DECLARE SUB      glutJoystickSetSaturation LIB "glut" ALIAS "glutJoystickSetSaturation" (ident AS INTEGER, axis AS INTEGER, st AS SINGLE)
DECLARE SUB      glutJoystickSetMinRange LIB "glut" ALIAS "glutJoystickSetMinRange" (ident AS INTEGER, axes AS POINTER)
DECLARE SUB      glutJoystickSetMaxRange LIB "glut" ALIAS "glutJoystickSetMaxRange" (ident AS INTEGER, axes AS POINTER)
DECLARE SUB      glutJoystickSetCenter LIB "glut" ALIAS "glutJoystickSetCenter" (ident AS INTEGER, axes AS POINTER)
DECLARE SUB      glutJoystickGetMinRange LIB "glut" ALIAS "glutJoystickGetMinRange" (ident AS INTEGER, axes AS POINTER)
DECLARE SUB      glutJoystickGetMaxRange LIB "glut" ALIAS "glutJoystickGetMaxRange" (ident AS INTEGER, axes AS POINTER)
DECLARE SUB      glutJoystickGetCenter LIB "glut" ALIAS "glutJoystickGetCenter" (ident AS INTEGER, axes AS POINTER)
DECLARE SUB      glutInitContextVersion LIB "glut" ALIAS "glutInitContextVersion" (majorVersion AS INTEGER, minorVersion AS INTEGER)
DECLARE SUB      glutInitContextFlags LIB "glut" ALIAS "glutInitContextFlags" (flags AS INTEGER)
DECLARE SUB      glutInitContextProfile LIB "glut" ALIAS "glutInitContextProfile" (profile AS INTEGER)
DECLARE SUB      glutInitErrorFunc LIB "glut" ALIAS "glutInitErrorFunc" (callback AS POINTER)
DECLARE SUB      glutInitWarningFunc LIB "glut" ALIAS "glutInitWarningFunc" (callback AS POINTER)
DECLARE SUB      glutSetVertexAttribCoord3 LIB "glut" ALIAS "glutSetVertexAttribCoord3" (attrib AS INTEGER)
DECLARE SUB      glutSetVertexAttribNormal LIB "glut" ALIAS "glutSetVertexAttribNormal" (attrib AS INTEGER)
DECLARE SUB      glutSetVertexAttribTexCoord2 LIB "glut" ALIAS "glutSetVertexAttribTexCoord2" (attrib AS INTEGER)
DECLARE SUB      glutInitContextFunc LIB "glut" ALIAS "glutInitContextFunc" (callback AS POINTER)
DECLARE SUB      glutAppStatusFunc LIB "glut" ALIAS "glutAppStatusFunc" (callback AS POINTER)
DECLARE FUNCTION glutCreateMenuUcall LIB "glut" ALIAS "glutCreateMenuUcall" (callback AS POINTER, user_data AS POINTER) AS INTEGER
DECLARE SUB      glutTimerFuncUcall LIB "glut" ALIAS "glutTimerFuncUcall" (time AS DWORD, callback AS POINTER, value AS INTEGER, user_data AS POINTER)
DECLARE SUB      glutIdleFuncUcall LIB "glut" ALIAS "glutIdleFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutKeyboardFuncUcall LIB "glut" ALIAS "glutKeyboardFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutSpecialFuncUcall LIB "glut" ALIAS "glutSpecialFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutReshapeFuncUcall LIB "glut" ALIAS "glutReshapeFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutVisibilityFuncUcall LIB "glut" ALIAS "glutVisibilityFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutDisplayFuncUcall LIB "glut" ALIAS "glutDisplayFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutMouseFuncUcall LIB "glut" ALIAS "glutMouseFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutMotionFuncUcall LIB "glut" ALIAS "glutMotionFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutPassiveMotionFuncUcall LIB "glut" ALIAS "glutPassiveMotionFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutEntryFuncUcall LIB "glut" ALIAS "glutEntryFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutKeyboardUpFuncUcall LIB "glut" ALIAS "glutKeyboardUpFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutSpecialUpFuncUcall LIB "glut" ALIAS "glutSpecialUpFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutJoystickFuncUcall LIB "glut" ALIAS "glutJoystickFuncUcall" (callback AS POINTER, pollInterval AS INTEGER, user_data AS POINTER)
DECLARE SUB      glutMenuStatusFuncUcall LIB "glut" ALIAS "glutMenuStatusFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutOverlayDisplayFuncUcall LIB "glut" ALIAS "glutOverlayDisplayFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutWindowStatusFuncUcall LIB "glut" ALIAS "glutWindowStatusFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutSpaceballMotionFuncUcall LIB "glut" ALIAS "glutSpaceballMotionFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutSpaceballRotateFuncUcall LIB "glut" ALIAS "glutSpaceballRotateFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutSpaceballButtonFuncUcall LIB "glut" ALIAS "glutSpaceballButtonFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutButtonBoxFuncUcall LIB "glut" ALIAS "glutButtonBoxFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutDialsFuncUcall LIB "glut" ALIAS "glutDialsFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutTabletMotionFuncUcall LIB "glut" ALIAS "glutTabletMotionFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutTabletButtonFuncUcall LIB "glut" ALIAS "glutTabletButtonFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutMouseWheelFuncUcall LIB "glut" ALIAS "glutMouseWheelFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutPositionFuncUcall LIB "glut" ALIAS "glutPositionFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutCloseFuncUcall LIB "glut" ALIAS "glutCloseFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutWMCloseFuncUcall LIB "glut" ALIAS "glutWMCloseFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutMenuDestroyFuncUcall LIB "glut" ALIAS "glutMenuDestroyFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutMultiEntryFuncUcall LIB "glut" ALIAS "glutMultiEntryFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutMultiButtonFuncUcall LIB "glut" ALIAS "glutMultiButtonFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutMultiMotionFuncUcall LIB "glut" ALIAS "glutMultiMotionFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutMultiPassiveFuncUcall LIB "glut" ALIAS "glutMultiPassiveFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutInitErrorFuncUcall LIB "glut" ALIAS "glutInitErrorFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutInitWarningFuncUcall LIB "glut" ALIAS "glutInitWarningFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutInitContextFuncUcall LIB "glut" ALIAS "glutInitContextFuncUcall" (callback AS POINTER, user_data AS POINTER)
DECLARE SUB      glutAppStatusFuncUcall LIB "glut" ALIAS "glutAppStatusFuncUcall" (callback AS POINTER, user_data AS POINTER)
